### PR TITLE
Removed observing after death

### PR DESCRIPTION
**Pull request by KionX**
Issues: #2447, #2259, #2141, #1752

Used with "hook_ObserverFix.cpp" from https://github.com/FAETHER/FA-Binary-Patches/pull/8
Can not be accept separately.

### CODE REVIEW

**Comment by shalkya** [comment]
so this would allow people dying to only see the what allies can see, even if observers are allowed ?
If that's the case, i see benefit in tournament when we need to allow observers on to let streamer in.
But i think the drawback would be in FFA for example, when people want to see what's happening in the game when they died. (if i'm right would it be possible to make people see the whole map in case their team has been defeated ?).

**Comment by shalkya** [comment]
didn't seems to work : 
I hosted a game with an ai ally vs an ai. Observers were on. When i ctrl k i can see whole map even if ally is still alive.

**Comment by KionX** [comment]
This only works if the ally is human.

**Comment by shalkya** [comment]
doesn't work with only human in the game

**Comment by KionX** [comment]
When playing with players, I did not find any errors

**Comment by shalkya** [comment]
image

**Comment by KionX** [comment]
Sandbox mode should be disabled

**Comment by KionX** [comment]
I can not reproduce the error, I need more details

**Comment by shalkya** [comment]
it seems to be related to some ui mods. I will investigate it more in detail later.

**Comment by shalkya** [comment]
ok so i figured out there is a conflict with supreme score board, which make allow people having the mod to see the whole map as usual when they die.

**Comment by shalkya** [comment]
so i understand this is a bandage fix while waiting for engine fix.
issue is that this bandage/fix can be dodged by doing alt-f2 and switching view (so intentional decision) or by having ui mods like SSB, which is a quite common one (unintentional abuse).
This introduce inconsistency and can give advantages to a team (that know how to abuse or have the SSB mod) and thus be game breaking. 
I'm for closing it.

**Comment by KionX** [comment]
I have already created a engine patch and will update PR soon.

**Comment by KionX** [comment]
Updated to full-featured version.

**Comment by KionX** [comment]
Finally tested version:)

**Comment by shalkya** [comment]
from what i understood this change is completely different from the exe one, and the exe change doesn't require this one. Correct me if i'm wrong.
I tested once again, this PR gives an unfair advantage to player using SSB. I won't merge a PR that can lead to unfair (and important) advantages.

**Comment by KionX** [comment]
The description says what is required https://github.com/FAETHER/FA-Binary-Patches/pull/8

**Comment by shalkya** [comment]
image

**Comment by KionX** [comment]
Modification exe allows you to control the behavior of observers from lua. Therefore, changes to lua are necessary.

**Comment by shalkya** [comment]
tested by strogo.

**Pull request merged**
