### PR TITLE
Overhaul preset system

### PR DESCRIPTION
**Pull request by ChrisKitching**
Working towards resolving our two outstanding issues with the preset system:
\#399 and \#402

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Ostensibly also fixes #421, but proper testing needed.

**Comment by aeoncleanse** [comment]
#399 not fixed yet. 

Things which need to happen: 
Entering presets with no presets should have a popup forcing you to declare one
Cancel button replaced with X in top right
Cancel button re-tasked as create new
New Preset writing in column bye-bye

**Comment by ChrisKitching** [comment]
... Absolutely none of which are mentioned in the issue.

Create a new issue for these enhancements: they're a lower priority than the remaining bugs blocking the 2.6.1 release.
Right now, it works, and it handles mods. The UI is still a bit clunky. We'll get there.

**Comment by Sheeo** [comment]
:+1:

**Pull request merged**
