### PR TITLE
Adding merge RULEUCC_Pause to nukesubs and sera battleship II

### PR DESCRIPTION
**Pull request by Uveso**
#1324 for Hussar :)

This fix will add RULEUCC_Pause = true to strategig missile subs and seraphim battle ship.
Nuke can now be paused so save energy etc.

(using merge now)

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
Good job @Uveso

**Comment by aeoncleanse** [comment]
Depends on #1339

**Comment by aeoncleanse** [comment]
So yes, sorry, but can we have this shadowing please? Import old files one commit, cleanup, then make changes.

**Comment by Uveso** [comment]
new PR is here: #1361 :)

**Pull request closed without merging**
