### PR TITLE
Fix HP Regen Buff Caluculation

### LINKED ISSUE #899: Seraphim acu restoration field BUG
Seraphim ACU restoration field has a bug that it lowers hp regeneration of units in range which have more HP regen then 200. For example SACU upgraded with nano regen should have 265 hp regen stock, and when in range of acu restoration field it should be like ~450 hp/s regen, but in reality it is only less then 200 hp/s - the ACU effect overrides the nano effect. The situation is worse as now the restoration field affect allies.

This might ring the bell:
BuffType = 'COMMANDERAURA', Stacks = 'REPLACE',

### PR DESCRIPTION
**Pull request by aeoncleanse**
Merges the two subcategories of regen to stop them interfering, and removes the floor/ceil mechanic (Only used by Seraphim Regen Aura) because it's going to be a constant pain in the butt, interfering with other legit buffs left right and center.

This *should* fix #899 and #923 (The latter when combined with @duk3luk3 's #976 )

Hopefully that stupid upgrade will never bother us again...

### CODE REVIEW

**Comment by ppipp** [comment]
What do you mean by removing the "stupid ceiling mechanic"? It's not stupid at all, it prevents the ability to be completely op with high HP units and have it significant for ones with low hp.

**Comment by aeoncleanse** [comment]
It's stupid because it didn't work. Moreover, the way buffs are done, it *can* never work. Particularly the 15/s on the first one, as soon as you come into range of anything with legit higher regen than that (A large number of things!) poof! It's gone.

The field with the 200 cap has a mult of 0.0111111. 200 / 0.1111111 = 18000, which means only things with 18000 HP + are going to be affected anyway, which is just SCUs, which happen to have a built in regen upgrade which goes higher than that. The whole situation is poor game design. 

What we want is to have a ceiling which affects only the bit of regen applied by the field, but the way the buffs are calculated, I don't see a way to sensibly do that. I'm looking though.

**Comment by aeoncleanse** [comment]
Made it work after all

**Comment by aeoncleanse** [comment]
Retargeting

**Pull request closed without merging**
