### PR TITLE
Remove SessionEndGame when leaving game

### PR DESCRIPTION
**Pull request by Crotalus**
Found this old branch sitting around, not sure it's completely legit though. Have a vague memory that I saw illegal command (OP_CallEndGame) inserted in replay command stream, or at least sent via network command, can't remember which.

In any case, it could be worth a shot to try it out, the code it removes certainly didn't mitigate the desync issues (but maybe not causing any either)

### CODE REVIEW

**Comment by ChrisKitching** [comment]
The original goal of the code that this removes is to make disconnects never lead to a timeout countdown. Before I added this, if someone just does ALT+F4 (ragequit :D) then the game would often behave as if their connection timed out. Everyone would stop, have to wait through the 1:45 countdown, and then eject them. It was extremely annoying because people would routinely do this when they were close to losing, making completing a game a painful experience.

I don't know what `ConExecute('ren_oblivion true')` or `ConExecute('ren_ui false')` are doing here: those were added since I originally did the work and I'm not sure what they're aiming for. I guess preventing people from pressing buttons?

Anyway: this code was never intended to "mitigate desync". We should probably become more confident about whether or not it's doing harm before we straight-up remove it, because (unless something else has changed...?) as written this PR will cause a rather annoying regression.

**Comment by aeoncleanse** [comment]
Needs rebasing and further investigation as per @ChrisKitching

**Comment by Uveso** [comment]
Since i updated the game behavior on exit to FAF / desktop, the function SafeQuit() is used in 19 places.
Are you sure the "safe" way is not needed in all 19 cases ?
#2081

**Comment by Strogoo** [comment]
```I saw illegal command (OP_CallEndGame) inserted in replay command stream```

@Crotalus what parser do you use to see this stuff in replay? Contact Dragonite (FAF slack) if you have time and desire to help. He is working on new replay server and your advices would be really useful. ty

**Pull request closed without merging**
