### PR TITLE
Props ancient-earth

### PR DESCRIPTION
**Pull request by Garanas**
Adds in the props from Madmax, Thacon and Biass. 

Checklist for Biass:
 - [x] Checked ancient-earth props
 - [x] Checked Thacon props
 - [x] Change texture of the gate

Props to add:
 - [x] crystals

~~Note: do _not_ merge this (yet)!~~
Ready for review!

### CODE REVIEW

**Comment by Garanas** [comment]
Note from speed2: you can use the old models by having a relative path to them in the .bp file

**Comment by Garanas** [comment]
This is a map with all the props on it:
 - https://we.tl/t-9HGAjjzjXc

**Comment by Garanas** [comment]
Only thing remaining is the gate being pretty messed up pathing wise (CTRL + ALT + O).

**Comment by Garanas** [comment]
@shalkya I think it is ready for review

**Comment by shalkya** [comment]
Yeah so I looked into it, mostly it's fine. I just have some doubt on the reclaim amount of the props worth 300 reclaim. It's seems a bit high, in comparison to their look.

**Comment by Garanas** [comment]
I agree - according to biass this is what they are in vanilla too. I can't ping him here, but I'll message him

**Comment by Garanas** [comment]
@shalkya it should be all good now! I've checked it with the default props

**Comment by shalkya** [comment]
tested again, approved

**Pull request merged**
