### PR TITLE
Fixed restricted commander upgrade issue #1047

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
this is a fix for high sim bug

### CODE REVIEW

**Comment by Crotalus** [comment]
Nice work with the PR, it's pointing to `develop` instead of `release/3652` though. I'll rebase and merge your changes.

I'll add some additional commits also to fix the fact that EnhCommon.GetRestricted() is never set/used. The restriction table should be synced from simside so we are able to change the restrictions on the fly in a game.

**Comment by Crotalus** [comment]
Merged here:
267313f45ac56853071a5684e3a2a8914954eeda..e78ecdfa42ccc777d08226f0645ae5ab1c087158

**Comment by Sheeo** [comment]
On another note: In the future please use consistent indentation settings -- we use spaces in this project.

**Comment by HUSSAR-mtrela** [comment]
@Sheeo I'm sorry for the indentation issue and I usually use spaces but I forgot to set this setting in notepad++ after I upgraded to Win8. I will make sure my future changes also use spaces to indent code.

**Pull request closed without merging**
