### PR TITLE
Fix same unit stats being reported for all players

### LINKED ISSUE #1362: Unit stats same for all players
I observed that the same unit stats are reported for all players.
Fix is known

### PR DESCRIPTION
**Pull request by micheljung**
I would love to have this deployed ASAP so we can reset the stats
Fixes #1362

### CODE REVIEW

**Comment by Crotalus** [comment]
@micheljung Cherry-pick this e6f43001f0445514014ab510c5a4871ae1c55a9d into your PR to get it fully working (was a typo with unitStats reference)

Then ask some other slacker / noob with mojo to merge / review this and the other 30 open PRs, I don't have merge powers to `develop` it seems.

**Comment by HUSSAR-mtrela** [comment]
nice fix... I really like to finally be able to use these stats in my SSB mod. 
However, I think that it would be better if stats for individual blueprints were saved in a separate table:
```
for unitId, stats in brain:GetUnitStats() do
    if ArmyScore[index].bps[unitId] == nil then
        ArmyScore[index].bps[unitId] = {}
    end
    for statName, value in stats do   
        ArmyScore[index].bps[unitId][statName] = value  
    end
end 
```
instead of:
```
for unitId, stats in brain:GetUnitStats() do
    if ArmyScore[index].units[unitId] == nil then
        ArmyScore[index].units[unitId] = {}
    end
    for statName, value in stats do   
        ArmyScore[index].units[unitId][statName] = value  
    end
end 
```
because it is a bit difficult to get stats for each blueprint and distinguish them from the rest of stats since I need to check if "key" in ArmyScore[index].units[key] is a valid blueprint ID and not a categoryName that is saved by:
```
for categoryName, category in categoriesToCollect do
    ArmyScore[index].units[categoryName]['kills'] = brain:GetBlueprintStat("Enemies_Killed", category)
    ArmyScore[index].units[categoryName]['built'] = brain:GetBlueprintStat("Units_History", category)
    ArmyScore[index].units[categoryName]['lost'] = brain:GetBlueprintStat("Units_Killed", category)
end
```

Also, last time I checked there was related issue with unit stats ( ArmyScore[index].units[unitId] ) that were populated with info about destroyed units (wreckage that are placed on some maps, e.g. middle of Seton) when the game was loading. In other words, all players should have zeros for unit stats after the game finished loading a map but that was not the case for some players.

**Comment by aeoncleanse** [comment]
Good work @Crotalus . @micheljung can I get you to look into the benefit of Hussar's proposal?

**Comment by HUSSAR-mtrela** [comment]
the benefit is that processing/analysis of stats for individual blueprints can be done without checking if unit statistic is for a blueprint or is it for units class (e.g. land). That being said, my proposed improvements will have no/low risk of breaking anything. In fact, we are not using  ArmyScore[index].units[unitId] part of units stats anywhere. As far I know, we are not using this part of stats in the score results displayed at the end of game. With my proposed small tweak any analysis tool (e.g. replay parser, score data parser on server side) or Supreme Score Board mod will be a bit faster while processing score data.

**Comment by micheljung** [comment]
@HUSSAR-mtrela thx I updated it; see d6e0a4f
For the wreck issue, can you please create a separate issue?

**Comment by HUSSAR-mtrela** [comment]
@micheljung thanks for making this correction and I created a separate issue (#1377) for wrecks
@aeoncleanse please let me know when you merge this PR

**Pull request merged**
