### PR TITLE
Fix Czar missing carrier auto deploy functionality

### PR DESCRIPTION
**Pull request by lL1l1**
## Issue
CZAR does not have the `CARRIER` category, so `blueprints-units.lua` external factory processing for carriers does not pick it up:
https://github.com/FAForever/fa/blob/3f034d13505450b406994746590d6668ed322826/lua/system/blueprints-units.lua#L675-L698

## Description of the proposed changes

- Manually add in the order override and stat toggle added by `blueprints-units.lua`.
- Fix type annotation of the `StatToggles` blueprint field. Not sure why it was incorrectly written in #5581 5dcaac5771cc26d84ec0326de72707e47d4a13d4

## Testing done on the proposed changes

The button's description is corrected, and when you right click it gets highlighted and constructed units automatically deploy.
{E107CE8C-0027-4862-99E4-93C3A9E0314A}
{E6F41DE5-5E96-4EB5-A765-5367404447B9}

## Additional context

This is the second bug I've seen because of CZAR being a flying carrier, the first being that intel/counterintel remains enabled for units inside the CZAR because its base class is that of an air transport and not a (naval) aircraft carrier.

## Checklist
- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
What would be the downside of giving it the `CARRIER` category? What are the side effects?

**Comment by lL1l1** [comment]
`CARRIER` is frequently used as if it is implicitly a naval unit category. It's more like the `DESTROYER`, `CRUISER`, and `BATTLESHIP` categories where it signals a rather specific type of unit than the general ability to carry aircraft.

**Comment by Garanas** [comment]
I understand. It may also mess up existing category queries where they expect naval-based carriers, but do not specify the naval category.

**Review by Garanas — APPROVED** [review]

**Comment by lL1l1** [comment]
I don't remember why I closed this. I guess because it already has the CARRIER category?

**Pull request closed without merging**
