### PR TITLE
upscaled textures

### PR DESCRIPTION
**Pull request by MadMaxFAF**
1st attempt to upscale textures added textures to all factions battleships

### CODE REVIEW

**Review by 4z0t — CHANGES_REQUESTED** [review]
Can you provide us with some images of these?

**Comment by MrRowey** [comment]
> Can you provide us with some images of these?

they are in the discord via a thread but yes adding some images would be better

**Comment by MadMaxFAF** [comment]
in this image you can see how much sharper we can get things
image

this image shows that we still have issues with colour artefacts 
image

Old
image
image
image
image
image


New
image
image
image
image
image

pictures from jip

**Comment by MadMaxFAF** [comment]
image
 with normals and spec upscaled

**Comment by MadMaxFAF** [comment]
UES0302 with new textures 
image

**Comment by Garanas** [comment]
image

image

image

Along with fixing it normals, which got dropped from the repo for some reason.

**Review by 4z0t — APPROVED** [review]

**Comment by MadMaxFAF** [comment]
i would say the results so far are looking good can't wait to see it with the new pbr shaders

for the record this is the tool used 

https://github.com/AaronFeng753/Waifu2x-Extension-GUI

with these settings for everything barring sera albedo

settings aeon cyb uef all sera normals and spec 1
settings aeon cyb uef all sera normals and spec 2
settings aeon cyb uef all sera normals and spec 3

setting used for sera albedo

settings sera albedo 1
settings sera albedo 2
settings sera albedo 3

**Comment by MadMaxFAF** [comment]
actually i broke the sera albedo oops fix coming

**Comment by MadMaxFAF** [comment]
setting used for sera albedo

settings sera albedo 1
settings sera albedo 2
settings sera albedo 3

**Comment by MadMaxFAF** [comment]
image
image
new textures

image
image
old textures

**Comment by Garanas** [comment]
I'm closing this pull request. The better direction (for now) is https://github.com/FAForever/fa/pull/4247 , and fixing some of the broken textures (like we did for the summit). More about the last part later.

**Pull request closed without merging**
