### PR TITLE
Remove redundant functions

### LINKED ISSUE #3723: Remove empty functions
Description
-------------
There are a few functions scattered throughout the repository that look like this:

```lua
StructureUnit = Class(Unit) {

   -- (...)

    StopBuildingEffects = function(self, unitBeingBuilt)
        Unit.StopBuildingEffects(self, unitBeingBuilt)
    end,
    
   -- (...)

}
```

They add no value but they do introduce an additional table lookup and function call. These can be removed by removing the definition in the specification of the class. 

Course of action
------------------
Look through the class hierarchies for these empty functions and delete them. We're particularly interested in sim-related classes, such as units, projectiles, weapons and props. A few example files are:
 - `/lua/defaultunits.lua`
 - `/lua/terranunits.lua`
 - `/lua/cybranunits.lua`
 - `(...)`

Test plan
------------------
Use a single pull request. Make sure to list the files that you have checked. That makes it easier for the reviewer to confirm that you've gone through all the relevant files. If you're unsure about anything you can discuss it in the #game-repository channel on the [FAF Discord](https://discord.gg/mXahVSKGVb) (after giving yourself the tester role in the #role-selection channel) or you can make a comment in this issue.

Learning goals
------------------
Feel more comfortable working on the repository.

### PR DESCRIPTION
**Pull request by Hdt80bro**
This PR removes redundant code on a greater basis than that which just calls the parent method:
 * `aeonunits.lua` and `seraphimunits.lua` both use a helper class (`AFactoryUnit` and `SFactoryUnit`, respectively) for their other three factory class. These helper classes have had their manual calls removed and been implemented through inheritance.
 * `kirvesbeams.lua#UnstablePhasonLaserCollisionBeam.OnImpact` now no longer manually calls its super-parent's method `CollisionBeam.OnImpact`; it now delegates through `SCCollisionBeam.OnImpact` with no behavior change.

The only way this should affect mod compatibility is if a mod (for some reason) adds methods to `AFactoryUnit` and `SFactoryUnit` that now requires disambiguation, or overrides `SCCollisionBeam.OnImpact` to propagate down. These both seem highly unlikely.
Fixes #3723

### CODE REVIEW

**Comment by Garanas** [comment]
Interesting, from `defaultunits.lua`:

```lua
-- AIR FACTORY UNITS
AirFactoryUnit = Class(FactoryUnit) {}

-- LAND FACTORY UNITS
LandFactoryUnit = Class(FactoryUnit) {}

SeaFactoryUnit = Class(FactoryUnit) {
    DestroyUnitBeingBuilt = function(self)
        if self.UnitBeingBuilt and not self.UnitBeingBuilt.Dead and self.UnitBeingBuilt:GetFractionComplete() < 1 then
            self.UnitBeingBuilt:Destroy()
        end
    end,
}
```

They don't add anything on top of the default factory class.

**Comment by Garanas** [comment]
oh no, I made a mistake.

**Comment by Hdt80bro** [comment]
Heh heh, that's alright

**Comment by Hdt80bro** [comment]
Blergh, can't figure out `git reset`

**Comment by Hdt80bro** [comment]
Move to <https://github.com/FAForever/fa/pull/4015>

**Pull request closed without merging**
