### PR TITLE
[4295] Part zero - fix bugs found in luft.lua

### PR DESCRIPTION
**Pull request by Zjonn**
## Introduction
Please have in mind that this is my first contact with **Lua**.
I've started working on first task from #4295 and found out that `equal` function in Luft is not working (always returns `true`).
I created this PR to address found problems and provide potential improvements

### Luft
- `to.equal` node had assigned `test` function instead of `Test`, so testing function was not invoked, and tests using it returned `true` - fixed

- ~~Each `PathNode` in `Luft` has `To` field, I assume it was added to describe how nodes should be combined, e.g.:
`Test.expect().to.equal()` is correct
`Test.expect().to.equal.equal()` is not
The `PathNode:GetNext(word) -> PathNode` at the end of the function was always checking if there is matching `PathNode` for current word in list of all possible nodes instead of `To` nodes of the current node, so as long as there was some Node matching current word the sequence was correct. 
In the PR the check is removed.~~
- ~~Removed nonexisting nodes from PathNodes  `To` and added missing~~

### Colors
- After fixing equal funciton tests started failing, as I see:
  - in the unit tests `HSVtoHSLsimp` was incorrect - fixed
  - in the colors implmentation `HSLtoHSV` was incorrect - fixed

### CODE REVIEW

**Comment by Zjonn** [comment]
@Garanas please take a look

**Comment by Hdt80bro** [comment]
Oh this one is probably my fault then--I just rewrote the testing module :)

I'll take a look later tonight

**Comment by Hdt80bro** [comment]
Well done! These some good catches, and helped me find a couple other bugs too (such as the `total_module_` variables only updating at the start of a test). The only comment I have the new behavior (with the knowledge I have about how I wanted it to work) is that you've removed some of the natural language of English I intended to have in, but appear to have only partially implemented (some of it still needs fixing too like the "to not" paths). I'm curious if that's something we even want to have though, e.g. is doing
```lua
luft.expect(x).to.be.equal.to(y)
luft.expect(y).to.be.close.to(y)
luft.expect(y).to.be.an.integer()
```
more desirable than
```lua
luft.expect(x).to.be.equal(y)
luft.expect(y).to.be.close(y)
luft.expect(y).to.be.integer()
```

**Comment by Garanas** [comment]
I'm impartial on either approach, the only thing I can think of is that we shouldn't deviate too much from how other testing suites operate. That would make it more difficult to use.

**Comment by Zjonn** [comment]
Personally I prefer shorter statements, also less complexity in untesed module sounds helpfully.
But for now I will remove changes related to Nodes chaining and it will be up to you @Hdt80bro what to do with them next.

**Review by Hdt80bro — APPROVED** [review]

**Comment by Hdt80bro** [comment]
That's alright, I'll merge this and fix the other you revealed in a separate PR

**Pull request merged**
