### PR TITLE
Add render fire clock for Battleships & Battlecruiser

### PR DESCRIPTION
**Pull request by MrRowey**
Added the Render Fire Clock to the Percy & the other 3 faction BS as Summit allready has it as well as the Neptune. base of Issuse #2527

### CODE REVIEW

**Comment by Garanas** [comment]
I think this is also a balance PR. @Tagada14 , can you look into this?

**Comment by Garanas** [comment]
I thought I'd change base to the balance branch, but after seeing the explosion of additional commits I regretted my decision quite immediately.

**Comment by Tagada14** [comment]
For battleships it's fine but Percies are a no go.

**Comment by Garanas** [comment]
@MrRowey if you can make the changes before Sunday then I can test it and then it will be merged on Monday morning.

**Comment by MrRowey** [comment]
@Tagada14 So the BS and the BC are fine just remove Percy Change ? just want to fully clarify this before I make the changes

**Comment by Garanas** [comment]
This PR has been in FAF Develop for a bit and people got back to me about the usefulness of the reload bar for the Cybran and Seraphim battleships. Their reload times are rather short, making it look strange when turrets fire while it didn't 'reload' yet.

Also - what about the Tempest?

**Pull request merged**
