### PR TITLE
Integrate Advanced Key Actions

### PR DESCRIPTION
**Pull request by 4z0t**
Allows you to create key actions based on selected units' category.
```lua
CategoryMatcher("Enter OC mode / Transport / Toggle repeat build")
{
    CategoryAction(), -- do nothing if no selection
    CategoryAction(categories.TRANSPORTATION)
        :Action "StartCommandMode order RULEUCC_Transport",
    CategoryAction(categories.COMMAND + categories.SUBCOMMANDER)
        :Action(import('/lua/ui/game/orders.lua').EnterOverchargeMode),
    CategoryAction(categories.FACTORY * categories.STRUCTURE)
        :Action(import("/lua/keymap/misckeyactions.lua").ToggleRepeatBuild)
}
```

### CODE REVIEW

**Comment by Garanas** [comment]
@4z0t there's a hiccup in this implementation, if you rename the actions then the old actions 'linger' in the key actions menu:

image

Wouldn't it be better to support the standard syntax instead?

**Comment by 4z0t** [comment]
@Garanas this is because old ones are still present in your prefs file.

**Comment by 4z0t** [comment]
The key is made of description, there is no point in adding second string that will represent key in this table, it will only make it more complex for modders to use.

**Comment by Garanas** [comment]
What is new is that it is now in the repository. If we'd, for example, update one of the combined actions with one more additional action we'll also need to update the description. At that point, **all** players will have a lingering, not functioning hotkey in their preference file.

**Comment by Garanas** [comment]
You're not addressing the issue. A lingering, not-functioning hotkey is confusing for everyone involved.

**Comment by 4z0t** [comment]
How are you going to fix it? Clear all of them from prefs file? What if there are custom ones and people wanna keep them? And I'm not gonna fix it in this PR either.

**Comment by MrRowey** [comment]
Closing this Pr can be reopened to fix the issues with it.

**Pull request closed without merging**
