### PR TITLE
Added personal stealth unit desc to T2 torp launchers - aeon and sera

### PR DESCRIPTION
**Pull request by shalkya**
adding stealth in unitdb

### CODE REVIEW

**Comment by Sheeo** [comment]
Thanks for this, there is the slight problem that it is not valid lua code :) I'll take care of this when merging.

**Comment by Crotalus** [comment]
Interesting that Travis doesn't bork, we don't syntax-check bp-files I guess?

**Comment by Sheeo** [comment]
@Crotalus I fixed this here 371b226986a451dcda3f3691203f8698181be7c9

**Comment by Crotalus** [comment]
Ahhh, I looked at the already fixed script then :)

**Comment by shalkya** [comment]
yes sorry, i didn't know how it worked before. But i'm trying to change a mod, so i understand lua a little bit better now :)

**Comment by Crotalus** [comment]
6c7fafcba09f7e81521bfe33ebdadbffb1fdc56e

**Pull request closed without merging**
