### PR TITLE
Megalith underwater speed boost

### PR DESCRIPTION
**Pull request by bamboofats**
https://github.com/FAForever/fa/issues/860

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Why not just call OnLayerChange and delete all the duplicated logic?

**Comment by ChrisKitching** [comment]
(Also, verify that units _don't_ get a layer change event when they're built, I had assumed they did)

**Comment by bamboofats** [comment]
Im not too sure about the other ways, pardon me. But if you got a better approach do use it! 
I tested one megalith built on land, then sent underwater,   2nd one built underwater, 3rd one spawned umderwater.
Then set them on a race across the ocean. Only the one built on land moves faster than the other 2.

But spawning a cybran destroyer on land automatically triggers the layer change to land. For the megalith it doesnt work properly. (since vanilla, I checked)

**Comment by aeoncleanse** [comment]
Instead of duplicating logic,  just call layerchange from stopbeingbuilt?  No,  it doesnt call on build by default. Works for cybran because you aren't building it on land,  you're spawning it

**Comment by duk3luk3** [comment]
Triggering layer change from stopbeingbuilt sounds like the right[tm] fix, I hope I can have a look at this soon.

**Comment by Sheeo** [comment]
Looks like #872 supercedes this.

**Pull request closed without merging**
