### PR TITLE
Button for balancing teams

### PR DESCRIPTION
**Pull request by shalkya**
UI integration of #2887 

still need to make a special button for it.
also need to make it work.

image

### CODE REVIEW

**Comment by Garanas** [comment]
@shalkya what is the status on this PR?

**Comment by ageekhere** [comment]
I hope this PR can be finished.

**Comment by ageekhere** [comment]
What still needs to be to be done on fairestTeams.lua
1. Run as a coroutine to not lock the main thread
2. Better way to limit how long the search will last for (maybe 1 to 2 seconds)
3. Get real player data (temp data is being used atm so the script can be tested with AI players)
4. Read player data from fairestTeam table which holds the teams
5. Move players in the lobby to the new slot locations and assign them into the fairest teams found 
6. Improve script performance, maybe use a better k-Combinations method

**Comment by Garanas** [comment]
Closing as https://github.com/FAForever/fa/pull/3750 got merged.

**Pull request closed without merging**
