### PR TITLE
This will enable the game to load merged blueprints from ingamedirectory

### PR DESCRIPTION
**Pull request by Uveso**
I found a way to merge unitblueprints like the Hydrocarbon's from inside the gamedirectory.
I added a smal loop inside Blueprints.lua to load merge blueprints from the new "unitshook" folder.

### CODE REVIEW

**Comment by Uveso** [comment]
Adding multi id and category search to merge blueprint function.

originalmerge with merge = true and a single blueprint ID:
```LUA
UnitBlueprint {
    Merge = true,
    BlueprintId = "uab1102",
    General = {
        UnitName = 'Test Dummy',
    },
}
```

Also accepting multi unit ID's
```LUA
UnitBlueprint {
    Merge = true,
    BlueprintId = {
        uab1102=true,
        ueb1102=true,
        urb1102=true,
        xsb1102=true,
    },
    General = {
        UnitName = 'Test Dummy',
    },
}
```

And also accepted Category search: Merge = array, BlueprintID will be ignored
```LUA
UnitBlueprint {
    Merge = {
        'TECH1',
        'MASSEXTRACTION',
        'STRUCTURE',
    },
    BlueprintId = "",
    General = {
        UnitName = 'MassDummy',
    },
}
```

**Comment by aeoncleanse** [comment]
I cannot think of any reason I'd use the final one :/

**Comment by Uveso** [comment]
I cant tell you that. I also prefer the original style with single merge.
If i want to modify more Blueprints with the same value i would use ModBlueprint() or similar.

Its just an attempt to see, if this will fit Crotalus need with those inheritance.

I could use it, if its in the game, but i don't really need it.

**Comment by Crotalus** [comment]
A usage for "category filter merge" could be if you want to set some specific weapon targeting for all units within a certain category, on the other hand we risk a clear overview of where stuff is actually set (like the GSR stuff dynamically set).

With inheritance I more meant something like this:

abc/abc1103.bp:
```
UnitBlueprint {
<all common stuff between all mass extractors>
}
```

uab1103/uab1103.bp:
```
UnitBlueprint {
    Merge='abc1103'
    Categories = {
        'AEON',
    },
    Display = {
        -- aeon specific stuff here
    }
}

**Comment by Uveso** [comment]
ok i changed a little bit.

We need 2 blueprints:

Parent_unit.bp
```LUA
UnitBlueprint {
    Merge = "child",
    BlueprintId = "uab1102",
    General = {
        Icon = 'air',
    },
}
```
child_unit.bp
```LUA
UnitBlueprint {
    General = {
        UnitName = 'NamedFromChild',
    },
}
```
Merge = "child" will lead to merge everything from "child_unit.bp" to "unit uab1102", then
"Parent_unit.bp" will be merged as normal to "unit uab1102".

Now you can use the child as base and you can still overwrite things from child with the parent blueprint.

**Comment by aeoncleanse** [comment]
This parent child thing makes no sense to me. Why do we want all this complexity?

**Comment by Crotalus** [comment]
Tested the inheritance here:
https://github.com/FAForever/fa/compare/develop...Crotalus:bp-inheritance

Base ASF file:
https://github.com/FAForever/fa/blob/4eb824fa7c9fcdda0a6548df24c9a89b7ff6442c/units/base/asf_unit.bp

https://github.com/FAForever/fa/blob/4eb824fa7c9fcdda0a6548df24c9a89b7ff6442c/units/URA0303/URA0303_unit.bp

Seems to work fine, we could probably get rid of even more boilerplate from each separate race-bp, audio sources etc should be able to be autogenerated, maybe mesh stuff as well depending on how consistent the mesh paths are.

(For weapons we maybe should provide some new `DPS` or similar so you can specify that in a parent template and then get the correct value per shot calculated automatically depending on a child units RateOffire)

**Comment by Crotalus** [comment]
You don't see any sense in inheritance? Hmm, all base structures for instance use same blueprints value except the things that differ visually.

**Comment by Crotalus** [comment]
Yeah maybe you're right for once, it's probably pointless.

**Comment by Uveso** [comment]
Then back to the roots :)
I restored the StoreBlueprint function.
Now the PR only contains the ability to merge from UnitsHook folder.

Does it makes sense to make a new PR with only 1 Commit, then this one ?

**Comment by aeoncleanse** [comment]
Yeah probably rebase it into sensible commit history.

**Comment by Uveso** [comment]
closed and uploaded a clean PR here:  #1339

**Pull request closed without merging**
