### PR TITLE
Add support for UTF

### PR DESCRIPTION
**Pull request by aeoncleanse**
dk0x's work rebased onto the latest develop branch.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
@sheeo @ChrisKitching @dk0x - This is the new UTF PR

**Comment by dk0x** [comment]
Thx so much!

**Comment by aeoncleanse** [comment]
Once everything is ready, I'll crush this lot down into a handful of commits with nice informative messages.

**Comment by dk0x** [comment]
What we waiting?)

**Comment by aeoncleanse** [comment]
The sheer complexity of this change means I'd like at least @Sheeo to sign it off before merging, but he's extremely busy. Don't worry, it is not forgotten, and not unwanted. Just need to get it right without screwing something up :)

**Comment by Sheeo** [comment]
Code looks good, history doesn't -- is plan to squash it further?

**Comment by aeoncleanse** [comment]
Yes

**Comment by aeoncleanse** [comment]
Rebased onto newest develop and tested. I now get a "Too many upvalues" error in lobby.lua :/

**Pull request merged**
