### PR TITLE
Fix reclaim value of prop on EOTS

### PR DESCRIPTION
**Pull request by speed2CZ**
This one was the 300 mass bullshit near every starting position that is totally not obvious. Changed
it to 0.5 as other faction fence.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
:+1:

**Comment by Sheeo** [comment]
Let's not put this into 3652.

**Comment by aeoncleanse** [comment]
But it's soooooooo small...

**Comment by speed2CZ** [comment]
it's not a feautre, it's a bug fix and nothing can go wrong with it. I swear on IceDreamer's life

**Comment by speed2CZ** [comment]
why close? rejected?

**Comment by aeoncleanse** [comment]
No, the branch 3652 got deleted. Just retarget at a new branch, say develop at present

**Pull request closed without merging**
