### PR TITLE
Updated loading tips to reflect the OC changes correctly

### PR DESCRIPTION
**Pull request by FemtoZetta**
See title, just updating the tips to correct information.

### CODE REVIEW

**Comment by shalkya** [comment]
just tested, it cost me 60k e to oc at 15000 damage

**Comment by FemtoZetta** [comment]
Yes, but you should need 67k in your storage to be able to use 60k energy for OC, according to the formula. I guess it could be reworded to make that more clear...

**Comment by shalkya** [comment]
maybe "Overcharge can deal up to 15,000 damage to a unit, costing 60k energy, but it requires to have 67k energy capacity"
tell me if you prefer that, either way i will merge it

**Comment by FemtoZetta** [comment]
grafik
grafik

I found something weird... It only used like 44k energy to deal 15k damage.

**Comment by FemtoZetta** [comment]
I reworded it a bit, now it should be clearer.

**Pull request merged**
