### PR TITLE
Fix general tech level

### PR DESCRIPTION
**Pull request by Uveso**
On some units the General.Techlevel don't match the Category Techlevel.

```
Unit xra0105 (Light Gunship) Categories.TECH1 dont match TechLevel (RULEUTL_Advanced) 
Unit xsa0107 (Light Air Transport) Categories.TECH1 dont match TechLevel (RULEUTL_Advanced) 
Unit ura0107 (Light Air Transport) Categories.TECH1 dont match TechLevel (RULEUTL_Advanced) 
Unit uaa0107 (Light Air Transport) Categories.TECH1 dont match TechLevel (RULEUTL_Advanced) 
Unit uea0107 (Light Air Transport) Categories.TECH1 dont match TechLevel (RULEUTL_Advanced) 
Unit ueb1104 (Mass Fabricator) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xrb0104 (Engineering Station) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit uab1104 (Mass Fabricator) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xsa0202 (Fighter/Bomber) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xes0102 (Torpedo Boat) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xrl0302 (Mobile Bomb) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xas0204 (Submarine Hunter) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit dra0202 (Fighter/Bomber) Categories.TECH2 dont match TechLevel (RULEUTL_Secret) 
Unit xrb0304 (Engineering Station) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xrb0204 (Engineering Station) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xrs0205 (Counter-Intelligence Boat) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xrs0204 (Submarine Killer) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit daa0206 (Guided Missile) Categories.TECH2 dont match TechLevel (RULEUTL_Secret) 
Unit del0204 (Gatling Bot) Categories.TECH2 dont match TechLevel (RULEUTL_Secret) 
Unit dea0202 (Fighter/Bomber) Categories.TECH2 dont match TechLevel (RULEUTL_Secret) 
Unit xeb0104 (Engineering Station) Categories.TECH2 dont match TechLevel (RULEUTL_Secret) 
Unit urb1104 (Mass Fabricator) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit xsb1104 (Mass Fabricator) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit drl0204 (Rocket Bot) Categories.TECH2 dont match TechLevel (RULEUTL_Basic) 
Unit ueb1302 (Mass Extractor) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xrb2308 (Torpedo Ambushing System) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit uab1302 (Mass Extractor) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit dal0310 (Shield Disruptor) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit xrb3301 (Perimeter Monitoring System) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xeb2306 (Heavy Point Defense) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit xss0304 (Submarine Hunter) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit urb1302 (Mass Extractor) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xsb1302 (Mass Extractor) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xeb2402 (Experimental Satellite System) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit urs0305 (Sonar Platform) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xsl0307 (Mobile Shield Generator) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit uas0305 (Sonar Platform) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit ues0305 (Sonar Platform) Categories.TECH3 dont match TechLevel (RULEUTL_Basic) 
Unit xea0306 (Heavy Air Transport) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xab2307 (Rapid-Fire Artillery Installation) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit xel0306 (Mobile Missile Platform) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 
Unit ura0401 (Experimental Gunship) Categories.TECH3 dont match TechLevel (RULEUTL_Advanced) 

```

### CODE REVIEW

**Comment by speed2CZ** [comment]
What excatly does this techlevel do?

**Comment by Uveso** [comment]
Not much.
Former using of the techlevel was inside Construction.lua function OnSelection.
In relation with the unitGridPages Array;
```LUA
local unitGridPages = {
    RULEUTL_Basic = {Order = 0, Label = "<LOC CONSTRUCT_0000>T1"},
    RULEUTL_Advanced = {Order = 1, Label = "<LOC CONSTRUCT_0001>T2"},
    RULEUTL_Secret = {Order = 2, Label = "<LOC CONSTRUCT_0002>T3"},
    RULEUTL_Experimental = {Order = 3, Label = "<LOC CONSTRUCT_0003>Exp"},
    RULEUTL_Munition = {Order = 4, Label = "<LOC CONSTRUCT_0004>Munition"},   # note that this doesn't exist yet
}
```
it was used to get the sortorder for Unitselection.
But this was replaced with the following code while using CategoryFilter:
```LUA
        sortedOptions.t1 = EntityCategoryFilterDown(categories.TECH1-categories.CONSTRUCTIONSORTDOWN, buildableUnits)
        sortedOptions.t2 = EntityCategoryFilterDown(categories.TECH2-categories.CONSTRUCTIONSORTDOWN, buildableUnits)
        sortedOptions.t3 = EntityCategoryFilterDown(categories.TECH3-categories.CONSTRUCTIONSORTDOWN, buildableUnits)
        sortedOptions.t4 = EntityCategoryFilterDown(categories.EXPERIMENTAL-categories.CONSTRUCTIONSORTDOWN, buildableUnits)
```
This change was made in the early state of the game.

Actually the Techlevel is only used from some Mods, and i am using it to get the Techlevel of a unit without looping over the Categories Array.

This is more a cosmetic / compatibility fix.

(Its not used by the ForgedAlliance.exe)

**Comment by Uveso** [comment]
@Icedreamer.
Does it make sense to redo this with Blueprint merge instead of overwriting the whole files ?
Like the same way you did it with the Hydrocarbon's Icon fix.

**Comment by aeoncleanse** [comment]
I'm not sure this is even gonna get merged TBH, iot's a non-functional change right? Still, if you can re-do it so you import no new files (If the bp is already in FAF, just change the val) that would be great.

**Comment by Uveso** [comment]
Well i learned recently that merging those blueprints will not work. :)

Maybe we can delete those techlevels in general.
I have to check around 500 mods, this could take a while :)

I close this for now, and will have this in mind.

**Pull request closed without merging**
