### PR TITLE
Rename lobui_0592 to lobui_0692

### PR DESCRIPTION
**Pull request by CookieNoob**
fixes https://github.com/FAForever/fa/issues/1690

### CODE REVIEW

**Comment by speed2CZ** [comment]
Did you just take random number, because I can't find `lobui_0692` in loc files

**Comment by aeoncleanse** [comment]
Yeah it's not LOCed yet, but this works for now.

**Comment by speed2CZ** [comment]
So why not to take the next free one? Instead of random one and adding it into loc files so someone can translate it later,
or removing the loc tag from it...

I feel like this is just making more work for someone else who would decide to localize some strings in lobby and then runs into this one already taken while several before this were not... and ofc this not being in loc files.

**Comment by CookieNoob** [comment]
The first one that is free would be "lobui_0009" or "lobui_0620". I can change it to that if you want to. The real question is why did the guy who changed the other variable took one that was already taken imo.

**Comment by Exotic-Retard** [comment]
well we should keep the numbers in as sane an order as possible, maybe you could even write some commit that fixes his locs as well?

in any case i would take the next available number. probably 620 since you presumably have more space there and its in a more chronological order i guess

**Comment by aeoncleanse** [comment]
Ok. We take the next available slot, and reverse any damage done by the commit which caused all this. We make sure the new key is in all loc files. 

Soon, im gonna get uveso to write a script to sort the loc files out once and for all, splitting it by section into originals and faf.

**Comment by Uveso** [comment]
lobui_0769 is the next free lobui key

btw, all keys in the german translation file are in alphabetical order.
There you can find the next free key very easy.

The english translation file ist different from all other translations. 
This is because we have english text in strings.db, unitdescription.lua and keydescription.lua.
All other languages only have the strings.db file that contains all strings also from unit and key description.lua.
There is no clean way to sort or seperate the FAF from the normal translation. There are already to many keys deleted and reused for FAF. Try to use the FAF translation with the vanilla game, and you will see what i mean :)

But I can build a ingame debug function that can simply print all translation-keys to the logwindow.
This way you can find a free key in seconds.
(I already use this inside my debugmod for translations)

**Pull request merged**
