### PR TITLE
Remove UI rally points of factories

### PR DESCRIPTION
**Pull request by Garanas**
image
Rally points show up when you select a factory, but it is difficult to distinguish to which factory they belong

image
Best to just use the command overview, note that a rally point is **not** a command, it is just a mesh that follows the last command of a factory

### CODE REVIEW

**Comment by Penguin5** [comment]
Why not have both (the command overview, with the rally point at the end)?

**Comment by Hdt80bro** [comment]
Aww, I loved those. I understand your reasoning though. Could we leave in the rally point if there's just one factory selected?

**Comment by Garanas** [comment]
I wasn't aware of them until yesterday. Were you actively using them?

**Comment by Hdt80bro** [comment]
I'm just used to seeing them. There are times that showing the command graph would clutter the screen, so I'm happy to quickly see the rally point of a factory I select because I don't have to visually untangle any graphs--and also because it's immediate/automatic. It's also a really fast way to see if any of the factories are still using their default waypoints.

**Comment by Garanas** [comment]
Fair enough, then we'll leave it in

**Pull request closed without merging**
