### PR TITLE
Allow death weapons to knock over trees

### PR DESCRIPTION
**Pull request by Garanas**
Closes https://github.com/FAForever/fa/issues/4976

This does not implement the wave as suggested by the issue. It requires quite a bit more work, but this pull request on its own achieves the described effect.

image

### CODE REVIEW

**Comment by BlackYps** [comment]
Very nice! Two things I noticed:
1) For higher tech units the death damage is instantly applied once the unit is dead in spite of the animation first playing some small explosions before the big one that acutally spawns the wreck. This is technically not the fault of this PR, but I think it should be changed, so the damage matches the visuals of the animation.

2) It doesn't seem to work for air units. Many air units have aoe crash damage, but the trees don't get knocked over. It's especially apparent with air experimentals. Not sure why this is the case.

**Comment by Garanas** [comment]
> For higher tech units the death damage is instantly applied once the unit is dead in spite of the animation first playing some small explosions before the big one that acutally spawns the wreck. This is technically not the fault of this PR, but I think it should be changed, so the damage matches the visuals of the animation.

We can look into that in future pull requests. This would for example change how a compact volatile formation explodes. Which is fine, but it is better suited as a separate issue and we may need to discuss that with the balance team too

> It doesn't seem to work for air units. Many air units have aoe crash damage, but the trees don't get knocked over. It's especially apparent with air experimentals. Not sure why this is the case.

Air units are special snowflakes. I'll see what I can find

**Comment by BlackYps** [comment]
> We can look into that in future pull requests. This would for example change how a compact volatile formation explodes. Which is fine, but it is better suited as a separate issue and we may need to discuss that with the balance team too

Yeah, that one is definitely out of scope of this pull request

**Review by BlackYps — APPROVED** [review]
Looks good now

**Pull request merged**
