### PR TITLE
Setup to improve the pull request template

### PR DESCRIPTION
**Pull request by Garanas**

### CODE REVIEW

**Comment by Garanas** [comment]
Included by #5999

**Comment by Garanas** [comment]
@lL1l1 Should we also reference the developers guide, or is that silly at this point (given that they are making a pull request already). I think that @apollodeathstar at least initially used the tooling on Github itself to make pull requests.

**Comment by lL1l1** [comment]
I don't think referencing the guide is necessary; the contributor's environment should already be set up how they want it after they make a pull request, and it's fair to assume they read the readme on the main page of the repository before opening pull requests. No need to constantly remind people to set up their environment exactly as recommended.

**Comment by lL1l1** [comment]
Is there a way to automate the setting up the next version's changelog after releasing? This is an issue for my next PR. Also will conflicts be resolved automatically when every in-review PR is editing the changelog?
I also noticed that the "Description of Changes" title text takes up space in the issue/pr reference's tooltip.
image

**Comment by Garanas** [comment]
> Is there a way to automate the setting up the next version's changelog after releasing?

I am not sure, but it's little effort to do the setup at the moment.

> A small annoyance is that PR numbers in the changelog have to be set up after submitting the PR.

It is annoying for small pull requests that are usually merged immediately, but for the larger pull requests it makes sense to only create the entry when it is about to be merged in. It may as well skip a game version 😃 !

So far I think the new setup is working quite good. Already looking forward to the next release where we only have to check the changelog and make minor edits!

**Comment by Garanas** [comment]
We'll go with these changes; future improvements can be done in a separate pull request.

**Pull request merged**
