### PR TITLE
Fix assist for mobile shields (EQ)

### PR DESCRIPTION
**Pull request by Strogoo**
---------------------------------------------------------------
Fix from EQ
https://github.com/Ithilis/Equilibrium/commit/e729f6d72244b7cf588c3767a723b330aac1a22c#diff-df0eb38b9064089cb5ba809139ab9e4e
All thanks to Exotic
---------------------------------------------------------------

#2277

### CODE REVIEW

**Comment by shalkya** [comment]
what does that fix ?

**Comment by Strogoo** [comment]
Mobile shield stops moving if it's assisting friendly unit and there is enemy nearby. That's because of dummy weapon, which was added to fix attack-move for mobile shields.

Now both (attack-move and assit) work fine.

**Comment by shalkya** [comment]
would it be possible to do the same on flak by any chance ?

**Comment by Strogoo** [comment]
Yes. The thing is that this code starts additional thread for every mobile shield (when you give them "assist" command) and every second it checks if unit is still assisting. If not, then it turns on dummy weapon and kills the thread.

So this fix can have some impact on performance if you have too many shields/aa which are assisting other units.

Anyway, if IceDreamer doesn't mind, I can add it to mobile AA. (have to mention that Exotic did it only for mobile shields, so idk)

**Comment by JaggedAppliance** [comment]
I think just doing it for shields is fine, they have to be in more precise positions than flak and I'm wary of performance impacts.

**Comment by speed2CZ** [comment]
Can it be split into more commits, one where you add the original files, second where you clean them up and third where you actually make the fixes, so its possible to see what's actually changed?

**Comment by Strogoo** [comment]
Done. I'm not sure how I should clean these files tbh ;) Probably some tab/4-spaces stuff etc? They all looks similar in Notepad++, so yeah, I definitely need some instructions =)

**Comment by speed2CZ** [comment]
yeah, spaces, replacing # comments with --, != with ~= and such

**Comment by shalkya** [comment]
reviewed and tested

**Pull request merged**
