### PR TITLE
Fix UEF Gunship Stinger don't accept attack orders while on water

### PR DESCRIPTION
**Pull request by Uveso**
See issue #1392

This PR simply adds the Layer `Water` to `FireTargetLayerCapsTable`.
So the stinger will accept attackorders while floating on water.

### CODE REVIEW

**Comment by Exotic-Retard** [comment]
its pretty interesting that only the uef t2 gunship can land on water, is there a reason for this? perhaps its linked to the transport clamp its got?

**Comment by aeoncleanse** [comment]
Yes, it is :)

**Comment by Nojoke185** [comment]
checked this one out and it seems to work fine
a landed T2 UEF gunship (on water) - when given an attack order goes and attacks the designated target

**Comment by aeoncleanse** [comment]
ca884ee1446d1dde46c035f71177eb7d2175c7d2

**Pull request closed without merging**
