### PR TITLE
Display team ratings in the observer window of the lobby

### PR DESCRIPTION
**Pull request by Emperor-Penguin1**
This PR adds team ratings (sum totals) for each team to the observer window.  It shows the unrounded displayed rating (mean - dev * 3) and then shows the base rating (mean) +/- uncertainty (3 * dev) in parentheses.
If there are two or fewer teams, they are listed before observers.  If there are more than two teams, they are all listed after observers.

image

### CODE REVIEW

**Comment by Garanas** [comment]
Looks like a clean implementation. I'll give it to you - initially I was against because it would re-use the observers window / box. But now it seems better to have it, instead of waiting for the lobby to magically create more space for us 😄 .

I'll review it again tomorrow.

**Comment by Garanas** [comment]
In practice the numbers have a lot of decimal points:
image

@Emperor-Penguin1 Could you make a new pull request that rounds them to integers?

**Comment by Garanas** [comment]
There's a few other issues:
 - When a team is assigned manually it only updates for the host
 - When a player chooses their spot on the map it doesn't update
 
And I suspect other cases where a team switch happens (like switching two players) doesn't cause the observers window to update either.

**Comment by Emperor-Penguin1** [comment]
Okay, I'll look into fixing these and will make a new PR soon.

**Pull request merged**
