### PR TITLE
Adjust Nukes

### PR DESCRIPTION
**Pull request by Spikey84**
- Cut [nerf](https://github.com/FAForever/fa/pull/4108) to silo/sub cost in half
-  Nerf missle e cost to 5k per sec from 4.5k

### CODE REVIEW

**Comment by Tagada14** [comment]
Please revert your changes to the E cost of Silos. I wanted to only Cut the mass nerf in half, not the E cost.

**Comment by Tagada14** [comment]
Keep the ratio of 25e/m (the nerf) but adjust the cost to reflect that so 450k e -> 412.5k e

**Comment by Spikey84** [comment]
Is that what your are looking for @Tagada14?

**Comment by Tagada14** [comment]
@Spikey84 You forgot to change the E cost of Nuke subs, they should keep the old E Ratio but be lowered with the lowered mass cost

**Comment by Spikey84** [comment]
@Tagada14 is that correct?

**Comment by Tagada14** [comment]
Yeah

**Pull request merged**
