### PR TITLE
Fix RateOfFire Adjacency buffs and reload bars

### LINKED ISSUE #350: Salvation Adjacency bugged?
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9162&p=90558#p90558

### PR DESCRIPTION
**Pull request by aeoncleanse**
This is Crotalus' work (Thanks dude) from #352 pulled into release/3641. I've tested it with Salvation, Mavor, and all T3 Arty, and it works really nicely. Despite his reservations, I actually like the way the bar refills fast now, and the way the drains are working is correct.

Fixes #350

### CODE REVIEW

**Comment by Sheeo** [comment]
Bar doesn't refill all the way, shown here: https://www.youtube.com/watch?v=D0ZcAUfHMYU&feature=youtu.be

**Comment by Sheeo** [comment]
Minimum range marker is also gone.

**Comment by aeoncleanse** [comment]
This time it works. I promise it works. It worked last time too, but now it works!

**Comment by Crotalus** [comment]
9c36a5796cdb333c53b36c2d05dbf018b776278e

**Pull request closed without merging**
