### PR TITLE
feat : Update docs-build to include PR link rewrites

### LINKED ISSUE #6376: Replace `#XYZW` with a link to the pull request in question
### Description

When we create a release on GitHub all pull request references in the description that start with `#` are transformed to a link to the pull request. As an example, take the following release:

- https://github.com/FAForever/fa/releases/tag/3810

Meanwhile the source code is:

image

We'd like to do something similar for to-be introduced website that contains (generated) changelogs. As an example:

- https://faforever.github.io/fa/patches/fafbeta

Where all the pull request references should be turned into a hyperlink that takes you to the pull request in question. Not only does the average pull request contain additional information about the changes for the user, it also provides a low-weight introduction to get people to view GitHub and perhaps start contributing themselves.

### Course of Action

According to our friend ChatGPT there is a tool called `sed` in Linux to perform a 'find and replace (all)' type of operation on a file. It supports regular expressions and so we end up with something like:

`sed -E 's/#([0-9]{4,5})/[#\1](https:\/\/github.com\/FAForever\/fa\/pull\/\1)/g' inputfile.txt > outputfile.txt`

Which translates:

```
This is a reference to #12345.
Here is another one: #6789.
And yet another: #54321.
```

To:

```
This is a reference to [#12345](https://github.com/FAForever/fa/pull/12345).
Here is another one: [#6789](https://github.com/FAForever/fa/pull/6789).
And yet another: [#54321](https://github.com/FAForever/fa/pull/54321).
```

If we apply this transformation _right before_ we build the website then we have the same behavior as a GitHub release: the source is simple (just `#1234`), where as the final output is a link. This is convenient to the developer and to the user. 

Steps to take:

- (1) Add a new script file called `changelog-links.sh` to the [scripts folder](https://github.com/FAForever/fa/tree/develop/.github/workflows/scripts)
- (2) Update the [build workflow for pages](https://github.com/FAForever/fa/blob/develop/.github/workflows/docs-build.yml) so that the scripts become globally available. You can review how that is done in the [changelog workflow](https://github.com/FAForever/fa/blob/develop/.github/workflows/changelog.yaml#L99-L101)
- (3) Update the [build workflow for pages] to run the script over all the [posts](https://github.com/FAForever/fa/tree/develop/docs/_posts). These posts represent the changelogs. Make sure to run it _after_ we populate the posts for `fafbeta` and `fafdevelop`.

### Test Plan

You can write and test `changelog-links.sh` locally. It should take in a folder as a program argument and update all files in-place. 

Testing the workflow is less trivial, but you can get a long way by creating a branch and using the `workflow_dispatch` trigger and then choose the branch that you're working on.

Note: the processed markdown files should not be pushed.

### Learning Goals

Become more familiar with writing Bash scripts and integrating it in a workflow.

### Progress

_Not applicable_

### PR DESCRIPTION
**Pull request by relent0r**
Closes #6376

This PR updates the docs-build.yml workflow to update md files that include PR references.

It will loop through all files in the
docs/patches
docs/_posts

directories and rewrite any PR references using the #xxxxx expression and add the PR link.

The script takes 4 parameters. This is so it can be used with other repositories / environments in the future.
FOLDER_NAME - Where the md files are located
ORG_NAME - The github org name
REPO_NAME - The repository name
BASE_HOSTNAME - github.com

### CODE REVIEW

**Comment by relent0r** [comment]
@Garanas do we include snippets for these sorts of PRs?

**Comment by Garanas** [comment]
Not yet - when it is in a releasable state then we'll create a snippet about it.

**Comment by Garanas** [comment]
Can you add a (MIT) license to the file?

**Review by Garanas — APPROVED** [review]
Just tested it locally by running the bash script directly - appears to be all good!

**Pull request merged**
