### PR TITLE
Increase nuke and exp nuke hp 1000 times. Also increase SMD damage.

### PR DESCRIPTION
**Pull request by Kazbek**
Fix nuclear missle can be killed by satellite (and others).

### CODE REVIEW

**Comment by JaggedAppliance** [comment]
Thanks for making this pr, we will discuss it in the balance team very soon.

**Comment by JaggedAppliance** [comment]
We decided we want to implement this. Can you point this pr at deploy/fafbeta and also split the seraphim experimental nuke into two commits; one that adds the original file as it is in the base game and a second that makes the changes to the file.

**Comment by Kazbek** [comment]
@JaggedAppliance I guess its done #3155

**Comment by JaggedAppliance** [comment]
merged #3155

**Pull request closed without merging**
