### PR TITLE
Window Resize Fix

### PR DESCRIPTION
**Pull request by KionX**
To reproduce the error, place the minimap on the edge of the window and reduce,
and then increase window size.
The right side of the map sticks to the window and stretches with it.
The chat window behaves the same way.

### CODE REVIEW

**Comment by speed2CZ** [comment]
Split it please into two commits, one with a cleanup and one with the fix, so in the history you can see right aways what got changed.

**Comment by shalkya** [comment]
i don't see the bug.
Maybe you are talking about increasing the size of the windows on the right, that scale the map while the bottom of the windows don't scale, so you end up zooming. Although that's not fixed with your pr.

**Comment by KionX** [comment]
The right side of the map sticks to the window and stretches with it.
The chat window behaves the same way.
Do not merge it. I want to try to make this fix in a different way.

**Comment by shalkya** [comment]
So one thing can be an issue : 
If you kind of fucked up the minimap previous the fix, and then switch to the fix, you get that : 
image
minimap is on the left, i can resize it, but part of it is outside the windows, and i can't move it around because of that. On top of that it is obviously broken since it's the minimap (you can move around the map click inside) but it doesn't display the minimap (actually show the game behind).

**Comment by KionX** [comment]
```If you kind of fucked up the minimap previous the fix```
Correcting extreme cases was not the goal of this PR.
I managed to fix this by stretching the minimap to the edge of the window then shrinking the window.

**Comment by shalkya** [comment]
ok the bug i linked isn't caused by your PR, it's something due to my game being launched in 2 different resolution depending if i use the exe for test or not. (Pretty weird one if you ask me, that i should fix at some point, maybe just changing the exe of testing) Resulting into test game keeping the size of the other resolution and ending up with some part of the mini map out of the game.
PR seems fine to me.

**Comment by KionX** [comment]
The minimap might break if the resolution was changed multiple times. With this fix, this should stop.

**Pull request merged**
