### PR TITLE
Pbr terrain improvement

### PR DESCRIPTION
**Pull request by BlackYps**
Instead of layering two textures at different scales we now sample at the same scale but with two different rotations. Then we blend between them with a relatively sharp transition to make the visual texture repetition go away.

Screenshot 2023-05-26 211430
Screenshot 2023-05-27 140856
Screenshot 2023-05-27 141439
Screenshot 2023-05-27 141228

### CODE REVIEW

**Comment by Garanas** [comment]
There's a tiling / square-like pattern when you're zoomed out:

image

**Comment by BlackYps** [comment]
It looks like that is because the textures in the atlas are bleeding into each other

**Comment by Garanas** [comment]
image

Ah, I see now

**Comment by BlackYps** [comment]
We can fix the bleeding once and for all if we have some texture space to spare. If we repeat each texture once, so we have a 2x2 layout of each texture and then only sample the middle, we have enough padding. Of course this doubles the texture size

**Comment by BlackYps** [comment]
I'll take the atlas bleeding issues to a separate pull request

**Review by Garanas — APPROVED** [review]

**Pull request merged**
