### PR TITLE
Minor scoreboard fixes

### PR DESCRIPTION
**Pull request by KionX**
The only important thing https://github.com/FAForever/fa/pull/2865#issuecomment-562934749
3 minor bug fixes are not worth mentioning.

### CODE REVIEW

**Comment by speed2CZ** [comment]
What does it fix? Can you update the description or the commit name please

**Comment by KionX** [comment]
4 minor bug fixes are not worth mentioning.

**Comment by speed2CZ** [comment]
Sorry, I had no time to review it yet, soon™

**Comment by shalkya** [comment]
tested works well.
@Strogoo does it looks fine code wise ?

**Comment by Strogoo** [comment]
Yep, the code is fine.

**Pull request merged**
