### PR TITLE
Hotbuild support factories

### PR DESCRIPTION
**Pull request by madformuse**
I've done quite a lot of testing and everything seems in order.

### CODE REVIEW

**Comment by speed2CZ** [comment]
I think this should be done in some more complicated way, then just adding all factories on one key. This way you won't speed up anything if you have to press one key so many times to get the building you want.

**Comment by Sheeo** [comment]
You'll click at most 3 times, and the most important factories (t3) show up first. I can't think of a complicated solution (This isn't normally requested :8ball:) that would do better?

**Comment by madformuse** [comment]
I was wondering if starting with higher tech factories would be better but I decided to fit in with the existing convention.

As someone who actually gets past the t1 phase what factories do you make the most in late game?

Actually scrap that... I fiorgot, you only make sparkies :p

**Comment by madformuse** [comment]
Actually Sheeo all 3 land would show up first. I wanted all high tech first but radar / pd etc cycle through all the tech levels for a unit before moving on.

I would 've happy to change them all but I hope it wouldn't screw anyone over changing all the orders.

**Comment by Sheeo** [comment]
Well maybe cycling t3land, t3air, t3naval, t2land ... is better then?

**Comment by madformuse** [comment]
Do you think we need to make it consistent with the other groups? Or more to the point change them so they're consistent?

**Comment by madformuse** [comment]
Come to think of it showing all T3 factories first would not work without a re-think because it organises them in sub groups of Land, Sea and Air which each contain all the techs and the "builders" group lists all three sub-groups. So the order is dictated by the organisation.

**Comment by madformuse** [comment]
Sorting on tech after the list is compiled could work and would work for all groups. Do we really want this?

**Comment by Zockyzock** [comment]
cycle t3 land, t3 air, t3 navy, then t2, then t1

**Comment by Crotalus** [comment]
40b9706d4ce356aab9320680357874bccfe1465b .. af710072af26fa8f690b3336dfc13fd1f6a86a66

**Pull request closed without merging**
