### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by BlackYps**
This updates the contents of CONTRIBUTING.md and should enable everyone to make good pull requests, find reviewers and to review PRs of others.

### CODE REVIEW

**Comment by Garanas** [comment]
It may be interesting to use the [Pizza CLI](https://opensauced.pizza/blog/introducing-the-pizza-cli) (yes), to generate an accurate [CODEOWNERS.MD](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file of the last year. That integrates with GitHub if I am not mistaken, that way people get more accurate suggestions. It is also where other GitHub users would expect the code owners to be listed.

If we then document the process, we can update the file every 6 months or so.

**Comment by BlackYps** [comment]
What halts me from using the code owners functionality is this (cited from the article you linked):
> Code owners are **automatically requested** for review when someone opens a pull request that modifies code that they own

This seems terribly annoying in the long run.

**Comment by BlackYps** [comment]
Pinging the other people that are mentioned in the file, so they are aware
@speed2CZ @relent0r @MadMaxFAF @The-Balthazar

**Comment by Garanas** [comment]
> What halts me from using the code owners functionality is this (cited from the article you linked):
> 
> > Code owners are **automatically requested** for review when someone opens a pull request that modifies code that they own
> 
> This seems terribly annoying in the long run.

You're right, that does sound a little annoying.

**Review by 4z0t — APPROVED** [review]

**Review by lL1l1 — COMMENTED** [review]
You can also add me to the blueprints section, as I understand that part is about understanding what all the blueprint values can do for a unit/weapon?

**Comment by relent0r** [comment]
Silly question but what defines a code owner? is it just anyone that's committed to the file in question?

**Comment by lL1l1** [comment]
Code owners are manually added to the CODEOWNERS file, so how ownership is given is up to us. The purpose of code owners is to automatically request reviews from knowledgeable people when a PR changing certain files is opened. You could determine who is knowledgeable by commits, sure.

**Comment by The-Balthazar** [comment]
You can put me down for sim and bps.

**Comment by BlackYps** [comment]
> You can also add me to the blueprints section, as I understand that part is about understanding what all the blueprint values can do for a unit/weapon?

Yes, that is correct

**Comment by BlackYps** [comment]
I will give everybody triage access that doesn't yet have access to the repo. This is required so you can actually be requested for review.

**Comment by Garanas** [comment]
@BlackYps if I am not mistaken then there is a GitHub team role specifically for that purpose. You could add the users to that role, instead of adding them directly to the repository.

**Comment by BlackYps** [comment]
Found it. But I don't have permissions to edit these teams

**Pull request merged**
