### PR TITLE
Change ping lockout to be per player instead of global

### PR DESCRIPTION
**Pull request by MrNukealizer**
Addresses #1982 by changing the limit to be per player. It allows 3 pings with a 15 second cooldown. It also allows an additional marker after reaching the limit, to be a little more accommodating if someone takes the time to type out a message. The marker still adds to the cooldown to prevent low effort marker spam.

### CODE REVIEW

**Comment by TheKeyBlue** [comment]
Yeah 3 / 15s sounds way too long. Just imagine people quikly pinging 3 location to alert somebody of something and then having to wait 15s while being unable to alert team members about incoming snipes.
I think just keeping the 1 / 1s ping would be best at first, atleast for testing on develop.
Then if ping spam by all players is an issue we can increase the cooldown.

**Comment by MrNukealizer** [comment]
I was following @Exotic-Retard's suggestion, but I agree it might need some refinement. What situation comes to mind where you'd need to quickly ping 3 locations in quick succession?

**Comment by aeoncleanse** [comment]
Responding to enemy joint attacks. Every 5s will be fine.

**Comment by CookieNoob** [comment]
I think 3/15sec is not enough. In the rare cases that someone scouts in a teamgame, he usually pings everything important that he can see. For example started nukes/experimentals/stratbomber... or just finished experimentals (might get more than one ping). Being limited to 3 pings would mean that you run out of pings quickly there. So I agree with @TheKeyBlue 1 / 1s is good for now.

also in the case of 3 / 15s you need to communicate it in a very good way or you will see lots of posts in tech support "ping feature broken" and a way to display the cooldown ingame (that could be done similar to the nomad intelprobe UI element)

**Pull request merged**
