### PR TITLE
Conditionally define `table.empty` and `table.getsize` in Lua

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Removes the Lua definitions of `table.empty` and `table.getsize`. These are now defined in the engine for better performance.

Requires:

- https://github.com/FAForever/FA-Binary-Patches/pull/98

## Checklist
- [ ] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
@4z0t if I am not mistaken then you also did a deepcopy implementation in C/C++. Is that functionally equivalent to the Lua version?

**Comment by 4z0t** [comment]
No, there are differences. My implementation doesn't care about metatables

**Comment by 4z0t** [comment]
Plus It requires a lot of changes for this PR.

**Comment by Garanas** [comment]
> No, there are differences. My implementation doesn't care about metatables

That sounds problematic yes, with the number of brain/unit references all over.

**Pull request merged**
