### PR TITLE
Lazy import

### PR DESCRIPTION
**Pull request by 4z0t**
Introduces `lazyimport` function for creating module instance without importing it til it is needed.

### CODE REVIEW

**Comment by Hdt80bro** [comment]
I like the idea even though I don't immediately see a use case for it, but I imagine it can make a bunch of unused files never load. Encapsulating the module loading is a nice a touch. Several notes:
* It looks like using `lazyimport` will always create new modules for the same file if it hasn't been loaded yet, since you moved the module registering to the load module function
* The metatable you have set up for lazy imports ignores the global-nil error throwing behavior if the first global accessed in it doesn't exist (as metamethods are not recursive)
* I think this breaks (or at least changes) the dependency tracking done on the initial import, since it stops tracking once it's done processing the import. But this might also be what we want if the lazyimport doesn't directly load the other module? I'm not sure. I'll have to think about it.
* Your formatter added some 5-space tabs by mistake :)

If we do add lazy importing, it will be most effective if all imports are lazy--so why not make this the default behavior instead of adding a new function to the global scope?

**Comment by 4z0t** [comment]
I tried to make all imports be lazy by default, but some modules must be loaded anyway since engine requires some of them.

**Comment by Garanas** [comment]
The immediate use is for `basetemplates.lua`, which is a gigantic file that I'd prefer to remain unloaded if not required.

**Comment by 4z0t** [comment]
> The metatable you have set up for lazy imports ignores the global-nil error throwing behavior if the first global accessed in it doesn't exist (as metamethods are not recursive)
Just tested, they are recursive.

**Comment by Hdt80bro** [comment]
Well, that solves that problem then! The documentation specifically says they aren't recursive (and it could cause infinite-loop problems if it was) but maybe setting the metatable inside the metamethod has something to do with it. Or the weird LuaPlus + Moho combination. Hmm, I'll need to do some testing.

**Comment by Hdt80bro** [comment]
> I tried to make all imports be lazy by default, but some modules must be loaded anyway since engine requires some of them.

I wonder how annoying it would be to special-case all of those. It shouldn't be too hard to get the list, I can probably pull the import strings out of the exe in five minutes.

**Comment by Hdt80bro** [comment]
```
/lua/gameColors.lua
/lua/RuleInit.lua
/lua/ui/lobby/lobbyComm.lua
/lua/armordefinition.lua
/lua/formations.lua
/lua/TerrainTypes.lua
/lua/aibrain.lua
/lua/sim/Navigator.lua
/lua/aipersonality.lua
/lua/sim/Blip.lua
/lua/sim/tasks/%s.lua
/lua/sim/ScriptTask.lua
/lua/sim/unit.lua
/lua/sim/projectile.lua
/lua/sim/prop.lua
/lua/sim/Weapon.lua
/lua/platoon.lua
/lua/simInit.lua
/lua/system/saveload.lua
/lua/SimSync.lua
/lua/SimSync.lua
/lua/SimCallbacks.lua
/lua/cinematics.lua
/lua/lazyvar.lua
/lua/maui/frame.lua
/lua/ui/uimain.lua
/lua/ui/game/construction.lua
/lua/ui/game/gamemain.lua
/lua/ui/dialogs/createunit.lua
/lua/ui/dialogs/createunit.lua
/lua/debug/pathdebugger.lua
/lua/debug/pathdebugger.lua
/lua/multiplayer/onlineprovider.lua
/lua/renderselectparams.lua
/lua/ui/game/commandgraph.lua
/lua/ui/game/commandgraph.lua
/lua/ui/game/commandgraph.lua
/lua/ui/game/commandgraph.lua
/lua/ui/game/commandgraphparams.lua
/lua/ui/game/commandwaypoint.lua
/lua/game.lua
/lua/ui/uiutil.lua
/lua/ui/game/selection.lua
/lua/ui/game/multihead.lua
/lua/debug/EngineStats.lua
/lua/debug/EngineStats.lua
/lua/debug/ArmyStats.lua
/lua/debug/ArmyStats.lua
/lua/ui/game/construction.lua
/lua/keymap/keyNames.lua
/lua/keymap/keymapper.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/game/worldview.lua
/lua/ui/uimain.lua
/lua/ui/game/gamemain.lua
/lua/ui/game/commandmode.lua
/lua/ui/game/commandmode.lua
/lua/ui/game/commandmode.lua
/lua/user/UserScriptCommand.lua
/lua/UserScriptCommand.lua
/lua/ui/game/commandmode.lua
/lua/ui/game/chat.lua
/lua/ui/game/chat.lua
/lua/ui/game/rename.lua
/lua/ui/game/rename.lua
/lua/ui/game/gamemain.lua
/lua/ui/uimain.lua
/lua/ui/uimain.lua
/lua/ui/game/gamemain.lua
/lua/ui/game/econoverlayparams.lua
/lua/ui/game/strategicIcons.lua
/lua/ui/game/gamemain.lua
/lua/ui/game/gamemain.lua
/lua/ui/controls/worldview.lua
/lua/ui/game/tracking.lua
/lua/ui/game/tracking.lua
/lua/SessionInit.lua
/lua/dataInit.lua
/lua/ui/game/gamemain.lua
/lua/user/prefs.lua
/lua/user/prefs.lua
/lua/options/optionslogic.lua
/lua/options/optionslogic.lua
/lua/options/optionslogic.lua
/lua/user/prefs.lua
/lua/SinglePlayerLaunch.lua
/lua/multiplayer/gpgnet.lua
/lua/multiplayer/gpgnet.lua
/lua/userInit.lua
```

**Comment by Hdt80bro** [comment]
Oh, I'm realizing several files are imported specifically for their side effects, so they can't be lazy by default.

**Comment by 4z0t** [comment]
@Hdt80bro thanks! I'll try to make all imports lazy and see how fast it would load in comparison with current.

**Comment by Garanas** [comment]
I'd like to note that the scope of this pull request is changing rapidly - the initial purpose was to just lazy load `basetemplates.lua`. That is, on its own, is a good use case. All other use cases are fine too, but I'd like to encourage you to make a separate pull request for that.

**Comment by 4z0t** [comment]
Well, understandable. What's left to be changed? I quite badly understand how import tracking works and where it is used.

**Review by Garanas — APPROVED** [review]

**Comment by Garanas** [comment]
Great work, now go crazy. But please be careful - I see for example no benefit from lazy loading all files only for the sake of doing so. There needs to be a concrete benefit to it that we can measure, or it is not worth doing.

**Comment by Garanas** [comment]
This pull request caused regression. It apparently doesn't reload modules properly after diskwatch discards the module. This is can be shown by making some change to `/lua/ui/controls/worldview.lua` which causes `lua/ui/game/commandmode.lua` to be reloaded. But instead of reloading, the logs tell me this:

```
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
WARNING: Error running '/lua/ui/game/commandmode.lua:GetCommandMode': call expected but got nil
         stack traceback:
```

@4z0t are you available to investigate and make a fix?

**Comment by Hdt80bro** [comment]
This is due to that file now being cached in `CM`

**Comment by Hdt80bro** [comment]
Note that lazy imports don't currently create any dependencies, so fewer imports will get reloaded from any dirty files.

**Pull request merged**
