### PR TITLE
Fix normal AI key on index selection. Remove unused entries.

### PR DESCRIPTION
**Pull request by relent0r**
Pre-Patch release validation.
This PR fixes the normal AI loading as the key was set incorrectly for the brain index load. 

It also removes the medium and easy aix variants from the index list as they dont exist to avoid any future confusion.

The easy AI still needs to be fixed before this PR goes in.

### CODE REVIEW

**Comment by relent0r** [comment]
@Garanas 
Are you able to take a look at the easy AI. I tried just setting the brain file back to base-ai.lua but the easy AI was still failing with the error

warning: ...elent0r\fa\lua\aibrains\templates\base\easy-main.lua(1): access to nonexistent global variable AIBaseTemplate

I'm unsure how you are initializing this base template when the easy-ai.lua brain is not being used.

**Comment by Garanas** [comment]
@relent0r Did you remove the other `easy` entry in the table?

**Comment by relent0r** [comment]
> @relent0r Did you remove the other `easy` entry in the table?

Yes, the template load appears to be happening here in the siminit

        -- import base templates, builder group templates and builder templates
        for k,file in DiskFindFiles('/lua/aibrains/templates/', '*.lua') do
            import(file)
        end
        
      Its expecting an AIBaseTemplate class that doesn't exist. I can comment out that for loop to make it work but I never really delved into what your doing with the easy AI in regards to this functionality.

**Comment by Garanas** [comment]
Ah, I see now. I'll look into it

**Pull request merged**
