### PR TITLE
Fix Cybran Acu Sonar Bug

### PR DESCRIPTION
**Pull request by Tagada14**
This fixes the bug where cybran ACU has sonar even without the torpedo upgrade.

### CODE REVIEW

**Comment by Tagada14** [comment]
I want to also fix the intel rings for Vanilla ACU, currently it shows the ring for Sonar with the range of 60 (SonarRadius = 60).
I tried to set the SonarRadius = 0 and create new value of NewSonarRadius that is used when you upgrade the ACU with the Torpedo upgrade but it caused some bugs.

**Comment by shalkya** [comment]
been testing a bit, i don't understand what second commit is aiming for. My cyb acu never display any sonar ranga/radius overlay (before or after this PR)

**Comment by shalkya** [comment]
image
ok back to work. That's what i got using your PR (here raw cybran acu) : it still does display the sonar range even if ACU didn't get upgraded.

**Comment by Tagada14** [comment]
Yes, it has a sonar range of 26, the same as OMNI so it doesn't matter. All ACU's would spot that sub.

**Comment by shalkya** [comment]
tested

**Pull request merged**
