### PR TITLE
Introduce `Deathnuke` armor for ASFs

### PR DESCRIPTION
**Pull request by Basilisk3**
## Description of the proposed changes

All ASFs: `Deathnuke` armor introduced (ASFs take 25% less damage from ACU explosions)

## Additional context
Due to #5465, bombing ASFs with ACU explosions has become even more powerful, as they are now more expensive but remain under the threshold of 2500 hit points to survive the explosion.

## Checklist

- [ ] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
Mentioned it to the balance team 👍

**Comment by Garanas** [comment]
I'm a bit confused, given that damage of type `normal` has a value of 1.0. Doesn't a value of 0.75 mean that 75% of the damage is applied, instead of 75% resisted?

**Comment by Basilisk3** [comment]
I improved my wording to clear up any confusion. They are supposed to take 25% less damage.

**Comment by lL1l1** [comment]
This will need a rebase before merging.

**Pull request closed without merging**
