### PR TITLE
Aeon gunship rework

### PR DESCRIPTION
**Pull request by Petricpwnz**
Turn aeon gunship into frontloaded gunship/bomber hybrid. Change projectiles into colorful rainbow balls of plasma to celebrate ~faction~ diversity.
Main changes:
- Splash from 0 to 2
- Much more damage per shot, much slower reload
- Looks fabulously gay

If this gets merged I think uef gunship should get a small range buff to put an end to the gunship chapter and not leave it out since it will probably become the weakest of the bunch.

### CODE REVIEW

**Comment by Strogoo** [comment]
Oblivion _totally accidentally_ got to the gay party. Hotfix is needed asap!

image

If to be serious, there is too much of a rainbow, as for me. Need smth more neutral.

**Comment by speed2CZ** [comment]
What the fuck is this?

**Comment by Petricpwnz** [comment]
Hey, beauty is subjective, lets have a democratic vote

**Comment by Petricpwnz** [comment]
> 
> 
> Oblivion _totally accidentally_ got to the gay party. Hotfix is needed asap!
> 
Woops, good catch, thanks. And fixed.

**Pull request merged**
