### PR TITLE
Remove the dive button while diving

### PR DESCRIPTION
**Pull request by Garanas**
Closes https://github.com/FAForever/fa/issues/5039

I'm not sure if this is what we should do, but it does work. The dive feature of a unit is temporarily disabled while diving.

https://github.com/FAForever/fa/assets/15778155/8603ffa2-89f1-482c-9e62-b2a3a0798b40

### CODE REVIEW

**Comment by EvildrewFAF** [comment]
Does the shortcut “d” still change it while the icon is not visible?

**Comment by Garanas** [comment]
> Is it possible to make the sub not cancel move orders when toggling to dive/surface?

You issue an order and that resets the existing command queue. Not sure if it is possible

**Comment by RabidPope** [comment]
> > Is it possible to make the sub not cancel move orders when toggling to dive/surface?
> 
> You issue an order and that resets the existing command queue. Not sure if it is possible

Ok. 
Is there a way to add the order to a queue with shift? So you can click a place and then surface.

**Comment by Garanas** [comment]
@RabidPope 

image

It is already there

**Pull request merged**
