### PR TITLE
Make menu popout-speed faster

### PR DESCRIPTION
**Pull request by Pokute**
In-game Menu opening is pretty fast now, but closing it is excruciatingly slow, especially when accidentally opening the menu in heat of the action. This patch changes menu opening and closing speed to time-based (about 0.575 seconds) instead of size-based delay.

### CODE REVIEW

**Comment by Garanas** [comment]
What resolution is the screen you tested this on?

**Comment by Pokute** [comment]
> What resolution is the screen you tested this on?

4k, but I did try with windowed 720p and the same slowdown happened.

**Comment by Pokute** [comment]
Will add before/after videos when I manage to capture them without exposing my browser tabs to everyone.

**Comment by Pokute** [comment]
Old menu behaviour:
https://github.com/FAForever/fa/assets/5271115/515c0b64-1c80-4681-9627-659ccf63fead

**Comment by Garanas** [comment]
Looking great 👍 , I'll try to give it a review later this week.

**Comment by Garanas** [comment]
Great work @Pokute !

**Comment by Pokute** [comment]
> Great work @Pokute , with what name do you want to be referenced in the changelog?

Pokute is fine.

**Pull request merged**
