### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by speed2CZ**
WIP

Saving the unit's army like we save EntityId

Afaik this should run faster than calling the engine function GetArmy()

Maybe someone like @Uveso would know how to measure it in his 300h long AI games?

And if it runs faster, it might be worth saving the army in all Entities, so things like Projectiles can also benefit from this, as there are more GetArmy calls in their scripts.

### CODE REVIEW

**Comment by Uveso** [comment]
Using a direct value instead of an function call always save CPU runtime.
I don't know if i can do a test and see how much the difference is, but ther is a difference for sure.

Could you also please add the unit BlueprintID to the unitclass ?

**Comment by Uveso** [comment]
Sadly found a bug in `DefaultProjectiles.lua` line 423
`OCProjectiles[army] = OCProjectiles[army] - 1`
should be
`OCProjectiles[self.Army] = OCProjectiles[self.Army] - 1`

**Comment by speed2CZ** [comment]
@Uveso I picked UnitId instead of BlueprintID. So it's same as the function

**Comment by Uveso** [comment]
Shield.lua needs a change.
Add in line 48:
`self.EntityId = self:GetEntityId()`

Line 137 and 165.
Change
`amount = amount * (1.0 - ArmyGetHandicap(self.Army))`
back to
`amount = amount * (1.0 - ArmyGetHandicap(self:GetArmy()))`

Found no other errors.

**Comment by Uveso** [comment]
@speed2CZ
@shalkya 
Looks very good now.
Can't find any additional errors.

Ready for merge.

**Pull request merged**
