### PR TITLE
UI Scaling fixes and improvements

### PR DESCRIPTION
**Pull request by speed2CZ**
Some stuff that was looked over or forgotten in the first run.

### CODE REVIEW

**Comment by shalkya** [comment]
i still get that issue on the option : 
image
could you fix that too ?

**Comment by shalkya** [comment]
went from that for reclaim 
image
to that : 
image
I find the brown one, less easy to spot ?

**Comment by speed2CZ** [comment]
what scale do you use, it works fine for me

**Comment by shalkya** [comment]
i've 125% scaling

**Pull request merged**
