### PR TITLE
Revert the changes made to how game results are send

### PR DESCRIPTION
**Pull request by Garanas**
And here we are - this PR is a direct result of https://github.com/FAForever/fa/pull/3275 where changes were made to how games are reported to the server. And it intents to close https://github.com/FAForever/fa/issues/3459 .

Before that there were several PRs that changed the reporting (#3032, #3115, #3152, #3166) as a result of a [discussion on Zulip](https://faforever.zulipchat.com/#narrow/stream/203478-general/topic/DrawBug) and those got into the previous patch (https://github.com/FAForever/fa/releases/tag/3715) and that was considered stable with the exception of one particular draw bug.

I've been trying to re-produce the errors that people [have been reporting](https://forum.faforever.com/topic/2656/game-was-not-reted-reason-unknow-result) [on the forums](https://forum.faforever.com/topic/2596/rating-system-is-not-rating-certain-games-although-it-should/20) and sadly, out of maybe 30 local tests I've been able to re-produce it once and I'm not even certain anymore if I wasn't dreaming.

Therefore I'm reverting the only changes that were made to how the score was send over - hoping that we get back to the same state as before.

### CODE REVIEW

**Review by BlackYps — APPROVED** [review]
This reverts #3275 
effectively going back to the behaviour we had from gamepatch 3717 to 3720.

**Comment by KionX** [comment]
_In that case you can just remove it because that fix didn’t work at all._
This means that (#3032, #3115, #3152, #3166) never worked. Why return them?
@Askaholic

**Comment by Garanas** [comment]
If they never worked - then why do we suddenly have dozens of games with conflicting results after the patch? As far as I could see the only change directly related to this is what this PR reverts, and if I'm not mistaken then that is what BlackYps confirmed.

**Comment by BlackYps** [comment]
From my understanding this is a hotfix to revert to the state we had before where the draw bug existed, but at least the games were rated. A solution to fix the whole game result reporting for good is still missing but out of the scope of this release.
Why are you so sure that the other for PRs you linked are useless? From my impression they alleviated the problem.

**Comment by Garanas** [comment]
Your understanding is correct BlackYps - this is by no means the last PR on this subject. But for now, this appeared to have worked better than we have right now.

**Comment by Askaholic** [comment]
Sounds good. The code I wrote to try and patch over the issue is pretty shit, but I think it happens to catch enough cases that the majority of games are rated.

I had some method that I was able to reproduce it with pretty reliably. I’m sure I wrote it on an issue or PR somewhere already, but I think it went something like:

1. join 2 players into a game
2. One player ctrl-k’s and then immediately exits the game

**Pull request merged**
