### PR TITLE
Adding Categories TRANSPORTFOCUS to uea0203(Stinger)

### PR DESCRIPTION
**Pull request by Uveso**
For details see issu  #1292 

If TRANSPORTFOCUS is added to the stinger, the mousecursor will show a transport icon if hovered over a unit while the stinger is selected.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Awaiting travis merge

**Comment by Uveso** [comment]
Is this normal to wait so long for a merge ?
Maybe because the commit is from an unknown repository ?

**Comment by aeoncleanse** [comment]
Yes, deleting the branch makes it much  harder for me to merge it.

**Comment by Uveso** [comment]
Sorry for that. I corrupted my repository and had to reinstall it from scratch.
Next time i wait for your merge before i delete something.

**Pull request closed without merging**
