### PR TITLE
Game UI reworking

### PR DESCRIPTION
**Pull request by Eternal-ll**
This PR for small bug fixes on UI of the game

**Changelog:**
-
ACU avatar below the score panel |
--- |
- [x] fixed seraphim avatar texture on right side of the screen
- [x] fixed size for each avatar texture
- [x] centered health bar on acu avatar

Idle stuff below the ACU avatar|
--- |
- [x] moved avatars to the right edge of ACU avatar
...

Selected/Hover unit abilities|
--- |
- [x] fixed visible window on layout switching

Score panel|
--- |

- [ ] fixed extra space and mixing with below panel when in game only **single army**

Left UI layout|
--- |

- [ ] ....

will work on this PR as possible

Feel free to ask to fix something on UI, i will look into it
---

### CODE REVIEW

**Comment by Garanas** [comment]
What is the status of this pull request? I think in general images would be good to have an idea what to look for. At the moment it is a bit tough to review, apologies for being so delayed.

**Comment by Eternal-ll** [comment]
I wanted to slowly fix some UI parts, but temporarily stopped. Mostly UI bugs related to textures thats is not in the same dimensions, some parts have code bugs as left UI layout, where is broken everything

**Comment by Eternal-ll** [comment]
The current changes are not visually noticeable, but they are there. Mainly changes in the panel of idle units below players panel

**Comment by Garanas** [comment]
I understand - when you pick this up again it is best to add in screenshots of the result and / or what to look for. It makes it easier to review.

**Comment by Garanas** [comment]
And - if you think it may take a while - I can also review the current state and merge accordingly.

**Comment by Eternal-ll** [comment]
Okay

**Comment by Garanas** [comment]
@Eternal-ll Shall I merge what we have? 😄

**Comment by Eternal-ll** [comment]
> 

:D There is too much stuff to finish, what about convert to draft then

**Comment by Garanas** [comment]
@Eternal-ll shall I just review and merge it? 😃

**Comment by KionX** [comment]
This been tested with ui scaling?

**Comment by Garanas** [comment]
Closing this pull request - @Eternal-ll you can open it up again when you have time to finalize it.

**Comment by Garanas** [comment]
Closing this pull request - @Eternal-ll you can open it up again when you have time to finalize it.

**Comment by Eternal-ll** [comment]
Ok

**Pull request closed without merging**
