### PR TITLE
Add scrolling text with announcement into the lobby

### PR DESCRIPTION
**Pull request by speed2CZ**
First try for adding the scrolling text with announcements into the in-game lobby.

Good for informing people about future tournaments or streams of some tournaments.

It looks like this: https://www.youtube.com/watch?v=sqQjGghdw9A
- [ ] Still need to figure out the way of sending this info into the game.
Which could be a text and a link (that way clicking on the text will open the web page)
- [ ] And slight problem that there's not enough space for the text with lower screen resolutions (height 768px)

### CODE REVIEW

**Comment by Strogoo** [comment]
> Still need to figure out the way of sending this info into the game.
> Which could be a text and a link (that way clicking on the text will open the web page)

cmd args? Idk how it works with long strings, should be fine I think ;)

https://github.com/FAForever/fa/blob/deploy/faf/lua/ui/lobby/lobby.lua#L125
&
https://github.com/FAForever/client/blob/stable/0.18/src/client/_clientwindow.py#L1449

```message["fafNews"] from server```

**Comment by speed2CZ** [comment]
Ok, so the new version uses two command line arguments /newsText and /newsURL

I'm not sure about the lenght, my poor testing skill allowed me to try only some short ones.
So if someone can try to make it run with some longer text please.

**Comment by axel1200** [comment]
If you can open links you could just request the news from API. That would be easy as .... for me then

**Comment by axel1200** [comment]
If you can open links you could just request the news from API. That would be easy as .... for me then

**Comment by axel1200** [comment]
Like I make a db schema add it to java-api and client can hand you over the news url where you request news from API... And we can set them in modor

**Comment by axel1200** [comment]
I saw you got a json libary in there as well ;)

**Pull request closed without merging**
