### PR TITLE
Increase TMD range by 1 to stop ground-fire abuse of TMLs

### PR DESCRIPTION
**Pull request by aeoncleanse**

### CODE REVIEW

**Comment by Sheeo** [comment]
@Zockyzock

**Comment by Zockyzock** [comment]
Needs confirmation if its enough

**Comment by Zockyzock** [comment]
It's not enough. I have to find out what's the best way of solving the issue without buffing TMD too much. If this is holding the patch back, ignore it, and it will be in the next balance patch.

**Comment by Zockyzock** [comment]
fire rate from 0.5 to 0.56
range from 0.3 to 0.31

**Pull request merged**
