### PR TITLE
Split up defaultunits.lua

### PR DESCRIPTION
**Pull request by ChrisKitching**
Sheeo mentioned over in #647 how nice it would be if the classes were split into separate files, so I did it.

This enables the "factory fixes" rubbish to go away (merged into the classes), and makes things really surprisingly neat.

Similar work could happen to aeonunits/cybranunits/seraphimunits/terranunits.lua.

### CODE REVIEW

**Comment by ChrisKitching** [comment]
(I spawned one of every unit to verify that this didn't end the world. Any missing imports will be pretty rapidly picked up as we test, methinks. Would be nice to see this shipped for the improved modding API (we've already broken a bunch of mods for 3641: better to do it all at once methinks and make the fixing maximally pleasant, than to keep on doing it a bit at a time? ))

**Comment by Sheeo** [comment]
Looks good.

It will break all mods though; I'm not sure the other changes we did in 3641 will break quite as many.

A migratory solution could be to keep references to the classes in defaultunits.lua, and keep using that file from the units — but import the bases from there, still giving the advantageous file structure but somewhat preserving compatibility.

**Comment by aeoncleanse** [comment]
Sounds like a good solution Sheeo

**Comment by Crotalus** [comment]
Yeah, keep references in defaultunits.lua and emit a warning about them being deprecated and due to be removed in a future release.

**Comment by Sheeo** [comment]
Please rebase to target develop :)

**Pull request closed without merging**
