### PR TITLE
Modify air elevations

### PR DESCRIPTION
**Pull request by Blodir**
Motivation:
  * Lower flying elevation increases the chance of flying units interacting with land units
  * Lower flying units can be hit slightly more consistently by ground-to-air weapons
  * Elevations are changed to be more consistent across factions
  * Transport loading/unloading is more reliable at lower elevations

Changes (elevation value in brackets):
```
t1 air scouts (16)
-------------------
Mirage, Flying Eyes, Sele-istle: 20 -> 16
Hummingbird: 18 -> 16

t1 interceptors (16)
-------------------
(no changes)

t1 transports (10)
-------------------
Chariot: 15 -> 10
Vish: 8 -> 10

t1 bombers (14)
-------------------
Note: t1 bombers can now fly inside t3 heavy shields slightly. With very good hoverbombing it is possible to kill shield generators.
Shimmer, Scorcher, Zeus, Sinnve: 18 -> 14

jester (10)
-------------------
(no changes)

t2 fighter bombers (18)
----------------------
(no changes)

t2 torps (18)
---------------
(no changes)

t2 gunships (10)
------------------
(no changes)

t2 transports (10)
--------------------
Star Lifter: 8 -> 10
Dragonfly, Vishala: 9 -> 10
Aluminar: 15 -> 10

swift wind (18)
-----------------
Swift Wind: 20 -> 18

mercy (18)
------------
(no changes)

t3 scouts (22)
----------------
Seer, SR90 Blackbird, Spook, Iaselen: 25 -> 22

asf (18)
----------
Corona, Wasp, Gemini, Iazyne: 20 -> 18

strats (18)
------------
Shocker, Ambassador, Revenant, Sinntha: 20 -> 18

t3 gunships (10)
-------------------
(no changes)

continental (10)
-------------------
(no changes)

solace (18)
---------------
Solace: 25 -> 18

soul ripper (12)
-----------------
(no changes)

czar (20)
-----------------
CZAR: 25 -> 20
Lowering the CZAR height allows for it to block Ahwassa shots more reliably.
Blocking the shots is sometimes good and sometimes bad -- it creates interaction between the players.

ahwassa (25)
-----------------
(no changes)

```

### CODE REVIEW

**Comment by Garanas** [comment]
How can this branch have conflicts 🤔 ?

**Comment by Blodir** [comment]
> How can this branch have conflicts 🤔 ?

I think I branched my dev branch from fafdevelop since fafbeta is behind it. But fafbeta has some elevation changes that are not on fafdevelop.

**Comment by Blodir** [comment]
As for the conflicts: the reason we (along with turin) set the strat elevation to 18 (as opposed to 14 in the conflicting elevation change) is because the 14 goes under sera t3 shields.

**Comment by Garanas** [comment]
I get the idea, but by going back to 18 you essentially reverted the intended change where tech 1 MAA and flak can more easily hit the strat

**Comment by Tagada14** [comment]
I think it might be worth it to just slightly increase the projectile velocity of T1 MAA

**Review by MrRowey — APPROVED** [review]

**Pull request merged**
