### PR TITLE
Fix LazyVars behaviour with `false` value

### PR DESCRIPTION
**Pull request by 4z0t**
Dealing with LazyVars I recently found out that setting value of lazyvar `false` causes troubles:
First of all:
`a  = Lazyvar.Create(false)`
`LOG(a())` - returns `0` that is not `false` at all (FYI 0 is a true value in Lua, so, 
`LOG(not 0)` is false)
Secondly:
`a:Set(false)` - ok fine, now it is false
`LOG(a())` - oh no, tried to call `nil` value?
Thirdly:
`a.OnDirty = function(self) LOG('i have a new value'..self()) end` - if we set a new value this would be called
`a:Set(false)` - no, we didn't...

### CODE REVIEW

**Comment by Garanas** [comment]
First import the base file in a separate commit and then make the changes. It makes it easier to review 😄 .

**Comment by 4z0t** [comment]
i closed it somehow xdddddddd

**Comment by Garanas** [comment]
I think it closed automatically because there are no file changes 🤔

**Comment by Garanas** [comment]
Interesting - any idea what this means: `result = {&1&4}`?

**Comment by KionX** [comment]
_Interesting - any idea what this means: result = {&1&4}?_
In LuaPlus, this indicates to preallocate memory for the table.

**Comment by 4z0t** [comment]
@KionX is there a detailed doc about those numbers and how it calculates the final size?

**Comment by KionX** [comment]
First & is hash table size rounded up to 2^(trunc(log2(nh))+1).
Second & is array linear size.

**Comment by 4z0t** [comment]
Isn't this line would break all other tests right after merging?

**Comment by Garanas** [comment]
Yes - we can't merge this in its current state.

**Comment by 4z0t** [comment]
Is there some kind of filter for running tests? Just put this file into blacklist 🙂

**Comment by Garanas** [comment]
We'd need to make changes to this file:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/run_lua_tests.sh
 
I'm fine with an exception.

**Comment by 4z0t** [comment]
@Askaholic can you help us with it? 😀

**Comment by Garanas** [comment]
Added the exception, @4z0t is this pull request ready?

**Comment by 4z0t** [comment]
@Garanas sure

**Pull request merged**
