### PR TITLE
Setup branch for PBR textures

### PR DESCRIPTION
**Pull request by Garanas**
Closes https://github.com/FAForever/fa/issues/4394

This branch acts as a 'pool of changes', where all texture updates are merged into. Before we merge, we'll remove all unchanged assets. That way we keep the repository as light weight as possible.

Not all maps have a PBR-ready sky box. You can use the following maps for testing:

- Mellow Shallows
- Saltrock Colony 8 players
- (...)

Concrete todo list before merge:

- [ ] Remove unchanged assets
- [ ] Revert [986c016](https://github.com/FAForever/fa/pull/4418/commits/986c0167fe095e3a7a4c9a0296ab59f602e3965e)
- [ ] Revert [d3546e6](https://github.com/FAForever/fa/pull/4418/commits/d3546e613756eaf4178b4948adddc0b713c4fcb2)

### CODE REVIEW

**Comment by Garanas** [comment]
Example of PBR preview:
image

Example of normals preview:
image

Example of spec team preview:
image

**Comment by Garanas** [comment]
Some units also require fixing the mesh, besides just textures:

image

image

**Comment by BlackYps** [comment]
I messed up a bit when trying to remove the unchanged files. I think these come from the factory changes. This branch originally only changed UEB0301, URB4205 and ZEB9601, though I am not sure if it's worth to keep those changes.

**Comment by BlackYps** [comment]
I think this branch is not needed anymore

**Pull request closed without merging**
