### PR TITLE
Enable the PBR unit shader on all maps

### PR DESCRIPTION
**Pull request by BlackYps**
Rolls out the long-awaited PBR unit shaders on all maps.

Originally this was part of #5172 but I separated it into two parts

### CODE REVIEW

**Comment by BlackYps** [comment]
I strongly recommend using a tool that uses the patience git diff algorithm to view the changes, the default used by github produces a very ugly diff. One way would be to use intellij IDEA.

**Comment by BlackYps** [comment]
Switching the shader for navy units gets rid of the need to use a script like in #4932, the map simply needs to add the `water` environment map.
The shader is the same as the regular unit shader, but passes the `water` environment map.
As the environment name falls back to the default environment if it is not present, this is a transparent change.

**Comment by Garanas** [comment]
Closed #4932 , do you (@BlackYps ) have time to walk through the changes by sharing your screen? I do not have Intellij IDEA installed

**Comment by BlackYps** [comment]
Yeah, we can do that

**Review by Garanas — APPROVED** [review]
Reviewed it together and all is good

**Pull request merged**
