### PR TITLE
Move the code for spherical hitboxes

### PR DESCRIPTION
**Pull request by aeoncleanse**
Just cuts down on code duplication. Some cleaning too.

### CODE REVIEW

**Comment by Sheeo** [comment]
Besides the superflous version bump commit, this looks good (y)

**Comment by aeoncleanse** [comment]
yeah I accidentally included some stashed changes somehow so had to rebase :p It will all be good when I merge ;)

**Comment by aeoncleanse** [comment]
Bump erased

**Comment by Crotalus** [comment]
:+1: 

8922564352aeef85543994023c266ce422f4ca3a

**Pull request closed without merging**
