### PR TITLE
Nerf Kennel Costs

### PR DESCRIPTION
**Pull request by Penguin5**
Decreases kennel mass cost by 20%
Decreases drone rebuild mass and energy costs by 60%
Decrease drone rebuild time by 33.33%
Increases drone elevation from 2 to 3
(replacement of #4198)

### CODE REVIEW

**Comment by Hdt80bro** [comment]
Looking at other drone costs, the Kennel drone definitely needed to be cheaper. 90% is a *huge* decrease though--what's the thought process behind making it cost half as much as an air scout?

**Comment by Penguin5** [comment]
For perspective, the other recent PR that rebalances kennels (#4193) actually reduces drone rebuild mass and energy costs by 94% and gives them 100 health... Drone rebuild costs are just so ridiculous at present that my PR is actually the more conservative one.

**Comment by Tagada14** [comment]
@Penguin5 Could you decrease the buff to the Kennel drones please?
I would keep it at 1kE and 100 mass for now. Also decrease the BT to 500.
Could you also look into increase their elevation a bit? It's an idea to make them less vulnerable to random AoE.
Increasing their hp to 50 should also be a small QoL buff while not going over board.

**Comment by Penguin5** [comment]
@Tagada14 I made the changes you requested.

**Comment by Tagada14** [comment]
Looks good, have you tested how big of an effect the elevation change has?

**Comment by Penguin5** [comment]
I did basic testing of it. It can be changed further if you prefer. I changed the elevation value in the bp from 2 to 3.  Here's how it looks:  
image

image

**Pull request merged**
