### PR TITLE
Unit Restriction fix for T2 Sera Sonar

### PR DESCRIPTION
**Pull request by MrRowey**
This fixes the unit restriction for the T3 Spam button disabling the sonar due to the MobileSonar Tag it has which is normally for t3 sonar. #3463

### CODE REVIEW

**Comment by Garanas** [comment]
I'll review this tomorrow evening.

**Comment by Garanas** [comment]
@MrRowey thoughts?

**Comment by MrRowey** [comment]
@Garanas the issues was that on t3 base Spam the MoblieSonar Pulls in the T2 Seraphim sonar as the Mobile Sonar tag only relay used for T3 Sonar with the exceptions for the Seraphim which was given the ability to move by FAF

**Comment by Garanas** [comment]
Yes - that happens now. Your solution leaves the t2 sonar in when other factions lost their t2 sonar.

**Comment by MrRowey** [comment]
I can explain more when I'm home

**Pull request merged**
