### PR TITLE
Use Set and GetCreator to track external factory

### PR DESCRIPTION
**Pull request by clyfordv**
Creates a "select external factory button" with carrier:SetCreator(carrier.ExternalFactory). Rudimentary demo, no art on the button, both the changes here and the pod staging pre-processing at the beginning of CreateAltOrders would likely best be moved to their own functions with a callback system.

### CODE REVIEW

**Comment by Garanas** [comment]
That's one way to do it 😄 , well found! I'll ask Fichom if he's available to make an icon for us

**Comment by Garanas** [comment]
Is this part of #5484 ?

**Comment by clyfordv** [comment]
It is, used some of the same backend elements

**Comment by Garanas** [comment]
Does that mean we can close this pull request?

**Pull request closed without merging**
