### PR TITLE
Feature/ally overflow

### PR DESCRIPTION
**Pull request by Crotalus**
Show team overflow in economy / score

(Quality is now only visible if actually set in the game)

### CODE REVIEW

**Comment by Xinnony** [comment]
:+1:

**Comment by aeoncleanse** [comment]
This feature needs some improvement before merge. The big one is that it displays an odd string sometimes.

**Comment by Sheeo** [comment]
Is this not what Crotalus is adressing with "(Quality is now visible if actually set in the game)"?

What I'd like to see is for all of it to be optional.

**Comment by Xinnony** [comment]
Is already a option, no ?

**Comment by Sheeo** [comment]
In that case: :+1:

**Comment by Crotalus** [comment]
Yeah the ally overflow stuff is an option. Quality indicator should be own UI option I think, they don't have anything in common really except being in the same pull request

**Comment by Sheeo** [comment]
Needs rebasing, let's consider getting this optionally into 3641?

**Pull request closed without merging**
