### PR TITLE
AI - fix incorrect .Result checks and replace with .Status

### PR DESCRIPTION
**Pull request by relent0r**
**Description of the changes**

I realised that the .Result attribute for player brain 'defeat' was changed to .Status and 'Defeat' but none of the AI was updated.

This PR changes the checks to be .Status and 'Defeat'

I'd like someone to sanity check this is correct as we now have other status like recalled etc. It may not be an issue if the 'Defeat' will be the only other status where the game will continue.

### CODE REVIEW

**Comment by Hdt80bro** [comment]
"Recalled" should be the only new status, and it's specifically designed to not work with AI's--so I don't think you need to worry about that.

**Review by Hdt80bro — APPROVED** [review]

**Review by Garanas — CHANGES_REQUESTED** [review]
It feels to me it is better to use either of these:
- https://github.com/FAForever/fa/blob/feature/add-messages-to-interactions/lua/aibrain.lua#L1287-L1290
- https://github.com/FAForever/fa/blob/feature/add-messages-to-interactions/engine/Sim.lua#L49-L51

In particular the latter is true when `SetArmyOutOfGame` is called.

@Hdt80bro should we extend the brain function to include a check for `SetArmyOutOfGame`?

**Comment by Garanas** [comment]
Extended the is defeated function, please use that instead @relent0r

**Comment by relent0r** [comment]
> Extended the is defeated function, please use that instead @relent0r

Ah ok, I'll update the PR to have instances use the IsDefeated function. That should make it future proof.

**Comment by Hdt80bro** [comment]
> @Hdt80bro should we extend the brain function to include a check for SetArmyOutOfGame?

Good call, that's an entirely separate mechanism from the status that's supposed to be meaningfully correlated.

**Comment by relent0r** [comment]
@Garanas Have updated (and fixed a small bug I spotted in testing)

**Review by Garanas — APPROVED** [review]

**Pull request merged**
