### PR TITLE
Fixed #1778

### LINKED ISSUE #1778: Error with T3 Loyalist stuns
Destruction T3 Cybran bots Loyalist puts stun on air units. Tested on T3 bombers and scouts.

### PR DESCRIPTION
**Pull request by MoltenMan**
Redid jaggedappliances commit, which was erased. Fixes loyalists stunning air units #1778

### CODE REVIEW

**Comment by CookieNoob** [comment]
I think you need to do it a bit differently:
- change the title to what the fix does ("fix loyalists stunning air units")
- add the original blueprint in a first commit (named "adding URL0303_unit.bp")
- add the modification in a second commit (named "adding air exception to URL0303_unit.bp")

add to the description of the pull request "fixes #1778"

**Comment by MoltenMan** [comment]
Yeah, sorry this was my first contribution. I realized that later.

**Comment by MoltenMan** [comment]
Do you know how to get it merged? Will someone with write access come along and merge it?

**Comment by CookieNoob** [comment]
yea at some point, someone will eventually look at it...

**Comment by MoltenMan** [comment]
Sorry accidentally put that in this pull. I'm gonna move it to another one.

**Comment by aeoncleanse** [comment]
Closing because the previous fix is still present and working in the right branch. See issue.

**Pull request closed without merging**
