### PR TITLE
Fix: Enable the Sparky to be buffed by the RegenAura-upgrades

### PR DESCRIPTION
**Pull request by Basilisk3**
This was not the case previously.

### CODE REVIEW

**Comment by Garanas** [comment]
What stops us from enabling all mobile units?

**Comment by Basilisk3** [comment]
> What stops us from enabling all mobile units?

Correct me if I'm wrong, but doesn't `BUILTBYTIER3FACTORY` already mean that? Ignoring units like drones, all mobile units that aren't T4s can be built by the T3 factories. It just doesn't work for a couple of units, at least that is my understanding of it.

**Comment by Basilisk3** [comment]
@Garanas Enabling all mobile units would mean ACUs get buffed, inlcuding your own. So we would need to introduce exceptions, which probably isn't worth it. This PR is ready to be merged.

**Comment by Garanas** [comment]
You're right; it is likely setup this way to exclude ACUs.

**Pull request merged**
