### PR TITLE
fix half built ML/mega wreck falling under the ground

### LINKED ISSUE #2399: sinking mega wreck bug
image
image
[game.uid.7566744.log](https://github.com/FAForever/fa/files/1774669/game.uid.7566744.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7566744
if you ctrl k mega after 50% completion. death animation execute, mega falls but it is already on the ground. Hence it fells underground.

### PR DESCRIPTION
**Pull request by shalkya**
Fixes #2399 
correct the pr #2823

### CODE REVIEW

**Comment by KionX** [comment]
It's a bad solution. Need to add a Fraction threshold to the blueprint.

**Comment by Nojoke185** [comment]
tested below scenarios and no issues seen:

Built all T4 units/structures to less than 50% and self destructed
results:
Aeon
Land build (less than 50% built before control K)
•	GC - no wreck
•	Czar - no wreck
•	Tempest - cannot be built on land
•	Paragon - cannot select to self-destruct
•	Salvation - no wreck
Sea build (less than 50% built before control K)
•	GC - no wreck
•	Czar - no wreck
•	Tempest - no wreck
•	Paragon - cannot be built on sea
•	Salvation - cannot be built on sea

UEF
Land build (less than 50% built before control K)
•	Novax - no wreck
•	Fatboy - no wreck
•	Atlantis - cannot be built on land
•	Mavor - no wreck
Sea build (less than 50% built before control K)
•	Novax - cannot be built on sea
•	Fatboy - no wreck
•	Atlantis - no wreck
•	Mavor - cannot be built on sea

Cybran
Land build (less than 50% built before control K)
•	Scathis - no wreck
•	Monkeylord – leaves wreck (wreck not underground)
•	Megalith - leaves wreck (wreck not underground)
•	Soul Ripper - no wreck
Sea build (less than 50% built before control K)
•	Scathis - no wreck
•	Monkeylord - leaves wreck (wreck not underground)
•	Megalith - leaves wreck (wreck not underground)
•	Soul Ripper - no wreck

Seraphin
Land build (less than 50% built before control K)
•	Yolona Oss - no wreck
•	Ahwassa – no wreck 
•	Ythotha - no wreck
Sea build (less than 50% built before control K)
•	Yolona Oss - cannot be built on sea
•	Ahwassa – no wreck 
•	Ythotha - no wreck

Built all T4 units/structures to greater than 50% and self destructed
results:
Aeon
Land build (greater than 50% built before control K)
•	GC - leaves wreck (wreck not underground)
•	Czar - leaves wreck (wreck not underground)
•	Tempest - cannot be built on land
•	Paragon - cannot select to self-destruct
•	Salvation - leaves wreck (wreck not underground)
Sea build (greater than 50% built before control K)
•	GC - leaves wreck (wreck not underground)
•	Czar - leaves wreck on ocean surface (wreck not underground)
•	Tempest - leaves wreck, wreck sinks from surface to ocean floor (wreck not underground)
•	Paragon - cannot be built on sea
•	Salvation - cannot be built on sea

UEF
Land build (greater than 50% built before control K)
•	Novax - leaves wreck (wreck not underground)
•	Fatboy - leaves wreck (wreck not underground)
•	Atlantis - cannot be built on land
•	Mavor - leaves wreck (wreck not underground)
Sea build (greater than 50% built before control K)
•	Novax - cannot be built on sea
•	Fatboy - leaves wreck (wreck not underground)
•	Atlantis - no wreck
•	Mavor - cannot be built on sea

Cybran
Land build (greater than 50% built before control K)
•	Scathis - leaves wreck (wreck not underground)
•	Monkeylord – leaves wreck (wreck not underground)
•	Megalith - leaves wreck (wreck not underground)
•	Soul Ripper - leaves wreck (wreck not underground)
Sea build (greater than 50% built before control K)
•	Scathis - leaves wreck (wreck not underground)
•	Monkeylord - leaves wreck (wreck not underground)
•	Megalith - leaves wreck (wreck not underground)
•	Soul Ripper - leaves wreck on ocean surface (wreck not underground)

Seraphin
Land build (greater than 50% built before control K)
•	Yolona Oss - leaves wreck (wreck not underground)
•	Ahwassa – leaves wreck (wreck not underground)
•	Ythotha - leaves wreck (wreck not underground)
Sea build (greater than 50% built before control K)
•	Yolona Oss - cannot be built on sea
•	Ahwassa – leaves wreck on ocean surface (wreck not underground)
•	Ythotha - leaves wreck (wreck not underground)

**Comment by shalkya** [comment]
Last pr add the threshold and fix ML/mega leaving wreck before 50% completion.
Please test.

**Comment by shalkya** [comment]
tested by nojoke

**Pull request merged**
