### PR TITLE
ADD LODCutoff in Projectiles bp for AEON AA missiles and torpedos

### PR DESCRIPTION
**Pull request by 7h3-M0rPh3u5**
ADD LODCutoff=130 in Projectiles bp for AEON AA missiles and torpedos : XAA0305, UAB2304, DALK003, UAB2109,  XAA0306

**Couldn't find the unit using AANTorpedo02_proj.bp**

### CODE REVIEW

**Comment by Garanas** [comment]
Looking good - I'll merge this in right away. What name do you want to show up in the changelog?

**Comment by 7h3-M0rPh3u5** [comment]
M0rPh3u5 should be fine. ;)
Did you find the unit using the AANTorpedo02_proj.bp?

**Comment by Garanas** [comment]
Looked for it, couldn't find it. There are quite a few unused effects, projectiles and other files in the repository. This is likely one of those

**Comment by MadMaxFAF** [comment]
i also tagged what units it was used by in the bp

**Comment by Garanas** [comment]
Merged as part of #3965 .

**Pull request closed without merging**
