### PR TITLE
Add Warp In Effects for sACUs

### PR DESCRIPTION
**Pull request by speed2CZ**
Same effect as for ACUs, PhaseShield mesh that is added for few seconds
is just a personal sheild, so only one missing was for cybran sACU.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Most of this code can be put into defaultunits.lua's CommandUnit class, could we do that please (Cuts down on code duplication.

**Comment by speed2CZ** [comment]
Since every sACU/ACU has different mesh for the shield, should I put them into blueprint so it can be easily picked then? Or any better idea?

**Comment by aeoncleanse** [comment]
That's certainly one way. Another would have been file concat on the UID.

**Comment by speed2CZ** [comment]
Superior version here https://github.com/FAForever/fa/pull/1575

**Pull request closed without merging**
