### PR TITLE
Print chat message when game is paused / unpaused

### PR DESCRIPTION
**Pull request by Garanas**
image

### CODE REVIEW

**Comment by Garanas** [comment]
@Hdt80bro suggestions on if we need to, and if so how to localize this? Sending the message in russian to everyone doesn't make a lot of sense, for example. But neither does English, for other languages

**Comment by Maaach** [comment]
well I just saw this by accident but couldn't you just sent a direct/private message to each individual player in their preferred language instead of one same message to all players

**Comment by Garanas** [comment]
That is quite possible, yeah

**Comment by Hdt80bro** [comment]
Auto-localizing chat messages is definitely a problem, and taunts & notify already suffer from this. Sending automated messages through the chat system to individual players based on their localization might work, but as a kludge has several problems. One is that each client must now query each other player for their localization, and then trust that other players will respect it. This introduces an inversion of control, where we have new points in the UI where the client is no longer in charge of its own locale. A more fundamentally one is in the presentation, in that information is given as a player that they did not send (i.e. just like the resource giving, taunt, and notify messages already do... at some point we *will* need a better way to present all this). It would be better to make this distinction at more a fundamental level by transforming the chat box into a message box, where additional messages that are not player chats can be displayed in it in a way that makes it clear what each is. So, instead of it saying `<Player> to all: Paused the game` it might be more like `<Player> paused the game` in a different color to signify "system" text.

This particular implementation also raises the question of whether pausing is something that should be handled via the chat system, or if it should be polled from the sim--there are different timing considerations to each approach, particularly when the game has stalled.

**Comment by 4z0t** [comment]
>  suggestions on if we need to, and if so how to localize this? Sending the message in russian to everyone doesn't make a lot of sense, for example. But neither does English, for other languages

@Garanas the way taunts are processed.

**Comment by Hdt80bro** [comment]
Maybe we could do it more pleasantly than the callback mess that Taunts end up creating--I think the way notify works is a little better, but still rather ad hoc.

**Pull request merged**
