### PR TITLE
Now impossible destroyed ACU via Ctrl+K without cheats

### PR DESCRIPTION
**Pull request by KionX**
Also fixed displayed announcement without goalControl.

### CODE REVIEW

**Comment by shalkya** [comment]
why would you implement this ?
Or did i miss-understand you ?

**Comment by KionX** [comment]
Suicide ACU maybe use for foul play, or ACU maybe accidentally destroyed.
In a normal game, you do not need to destroy ACU.

**Comment by speed2CZ** [comment]
You need in in a normal game. Sometimes is better to self destruct to kill your opponent when they are on low health since you would die anyway and you gotta do that before they are out of range.

**Comment by KionX** [comment]
It depends on what is more important to you.

Also, please pay attention to other PR: #2907, [Common Army for Coop](https://github.com/FAForever/fa-coop/pull/88), [Fixed save Timed Expansion lobby option](https://github.com/FAForever/fa-coop/pull/87), [Delete duplicate code in PlayerDeath function](https://github.com/FAForever/faf-coop-maps/pull/344).

**Comment by shalkya** [comment]
i would consider merging this pr, if you can change it in order to remove the ctrl k for ACU only when traitor game condition is on.
otherwise it's a no-go for me.

**Comment by PhilipJFryFAF** [comment]
even with traitors on there can be situations where you want to take someone down via ctrl k i suppose
i'm strongly against this change

**Comment by KionX** [comment]
I know that the only option when it is necessary to use Ctrl + K is when the enemy escapes in transport, in other cases it is enough to be near him.

**Comment by shalkya** [comment]
been thinking of it, can't you make it so if someone ctrl k, it gives the army to the strongest opponent ?

**Comment by KionX** [comment]
> if someone ctrl k, it gives the army to the strongest opponent

This will allow specially give army to enemy.

**Comment by shalkya** [comment]
I've got another input from another moderator that doesn't support this change.
I will close this PR unless you have another idea on how to fix the issue without disabling ctrl k on ACU.

**Comment by KionX** [comment]
Are there any penalties for Ctrl K on ACU?

**Comment by shalkya** [comment]
what do you mean by penalties ?
It is completely allowed and even necessary to pull off to get a draw when an opponent is dropping a heavily upgraded acu next to your own acu or when you are getting blocked and you will quit the explosion range for a draw.

**Comment by KionX** [comment]
I think suicide should be fined.

**Pull request closed without merging**
