### PR TITLE
BaseTemplates.lua memory lazy evaluation

### PR DESCRIPTION
**Pull request by 4z0t**
A magick file that contains 40k+ rows of data. And it is being unused during regular games without AI... 
The solution was to determine what parts of the file are the same and then use lazy evaluation to allocate data when needed. Attempt of using `lazyimport` wasn't successful because some AI mods were using that file, but it wasnt imported causing bugs.
~~Please dont ask anything about formatting.~~

### CODE REVIEW

**Comment by Garanas** [comment]
> And it is being unused during regular games without AI...

The file is not loaded during non-ai games, all the imports were inlined

**Comment by Garanas** [comment]
@relent0r I don't know how to confirm these changes, do you have a suggestion?

**Comment by 4z0t** [comment]
> The file is not loaded during non-ai games, all the imports were inlined

Whats the point then trying to optimize it?

**Comment by relent0r** [comment]
So the AI reference these by using a named key for the type then a faction index that correlates to the table index.

I'll be honest I don't understand what 4z0t is doing here, looks like black magic. Perhaps Sprouto could give better input than me.

The testing that I think we'll want is from mods that go and manipulate the basetemplates file. From memory Draguns SCTA one does and likely others that add new structures.

**Comment by 4z0t** [comment]
I tested SCTA and it didnt error.

**Comment by Garanas** [comment]
Closed this in favor of #4864 . In practice about 70% of the file was not referenced. We decided to just remove the unreferenced bits. As a consequence there are no similar base templates anymore

**Pull request closed without merging**
