### PR TITLE
Make buttons less cluttered

### PR DESCRIPTION
**Pull request by aeoncleanse**
Mod Manager > Mods, Unit Manager > Units

### CODE REVIEW

**Comment by Xinnony** [comment]
Better : Units > Restrictions
Because you can restrict :
- Units
- Upgrade
- Templates
- ...

**Comment by Sheeo** [comment]
Can we have some screenshots?

Also; wasn't the unit manager previously named unit restrictions or the like?

I do like Xinnonys idea of simply calling it "Restrictions".

**Comment by aeoncleanse** [comment]
I checked, Restrictions and Unit Manager take up the same space, so still cluttered, though I think Restrictions is a more accurate description of the function... What do we want to go with?

**Comment by Xinnony** [comment]
"Restricts" ?

**Comment by aeoncleanse** [comment]
Changed to "Restrictions and merged into incoming PR"

**Pull request closed without merging**
