### PR TITLE
Fix giving units in shared armies settings

### PR DESCRIPTION
**Pull request by speed2CZ**
Should fix https://forum.faforever.com/assets/uploads/files/1632602982556-e9722363-5b8a-4f1a-9be1-6683283624f1-image.png
from https://forum.faforever.com/topic/2605/crashes/6?_=1632601054108
Untested

### CODE REVIEW

**Comment by Garanas** [comment]
How do we test this change?

**Comment by speed2CZ** [comment]
Prolly open the 5th aeon mission with common army enabled (or how its called...)

The last patch didnt break it

**Comment by Garanas** [comment]
How do I enable common army?

**Comment by speed2CZ** [comment]
Its a setting in the coop

**Comment by Garanas** [comment]
Confirmed, mission five of the Aeon campaign works with this change (Shining Star)!

**Pull request merged**
