### PR TITLE
Weapon enhancement

### PR DESCRIPTION
**Pull request by aeoncleanse**
A bit of cleanup, moves overcharge from unit scripts into defaultunits for centralisation. No functional changes.

### CODE REVIEW

**Comment by Sheeo** [comment]
4fb45e1f1eca397f7a182f04ef49bd8ec56259a5 introduces gpg-files, I'd prefer it if we stick to the purpose of #201.

**Comment by aeoncleanse** [comment]
I recognise your concern, but A: It's almost inevitable these files are going to have to be added at some point, given how broad each one is, especially if RK's is ever integrated, and B: This cuts a lot of duplication out of the ACU script files, which are a ruddy mess so that's a really good thing.

**Comment by Sheeo** [comment]
Issue is simply that we cannot do this legally.

Just import the file, strip the implementation blocks and destructively hook what you need to hook, rewriting required code as you go along. Following suit with my example from #201 this should be fairly straight forward.

**Comment by aeoncleanse** [comment]
So you want me to hook it? OK!

**Comment by Sheeo** [comment]
I would prefer it if we could simply chug it all in and provide a full base game distribution, but, we need to follow suit of projects like http://openttd.org and do it right :)

**Comment by aeoncleanse** [comment]
Or we can get Visionik to buy ALL THE THINGS and do it 'Right' that way :D

**Comment by aeoncleanse** [comment]
This is now ready

**Comment by Crotalus** [comment]
:+1: 

d793f213c4b9e34303d9b5294a9154c78b9215c8
f5ddc3d13be8d76d0e124c87e6982acbbe9df7ff
3bffc029adbad2f4ec760b8d0127f160df4ecf55
8f2a1ee83511151197ce499b8784c1ee0049feb4
4564199035c0cc280890536a591ff8bdabfcfeac
b2b0a1789d5121fa6a7c213cf2c47ead1c0a4693
d5ab7c426fe8d72bbd48d87ee60c947f24f3f9a6

**Pull request closed without merging**
