### PR TITLE
Feature/targeting memory

### PR DESCRIPTION
**Pull request by Crotalus**
#406 rebased to `develop`

### CODE REVIEW

**Comment by Sheeo** [comment]
This should be interesting for @Zockyzock and @ppipp

**Comment by Crotalus** [comment]
@ppipp Try now

**Comment by Zockyzock** [comment]
Great change. But i don't like adding new UI Elements, making the game more complicated/overloaded. I think it has to work without. 

Is it possible to check if all units from your manual priority (e.g. mex with cruisers) in range are destroyed, and when that is the case, switch back to normal priority?

**Comment by ppipp** [comment]
Now it seems to work well. In my opinion, this behaviour should have been in the stock game, so even if it's a very big nerf to ACU, I think it should be included because it's much more userfriendly and intuitive.

**Pull request closed without merging**
