### PR TITLE
Remove smoke ring on underwater SACU death

### PR DESCRIPTION
**Pull request by Hdt80bro**
Closes https://github.com/FAForever/fa/issues/3433

### CODE REVIEW

**Comment by MrRowey** [comment]
Will test it on my end

**Comment by Hdt80bro** [comment]
Perfect! Right now, the `2` in `if position[2] + 2 > GetSurfaceHeight(position[1], position[3]) then` comes from the smoke ring being created 2 units above the commander (the `2` hidden in `...X * OffsetMod , 2, Z * OffsetMod...` [here](https://github.com/FAForever/fa/blob/deploy/fafdevelop/effects/Entities/SCUDeath01/SCUDeath01_script.lua#L81)).
If you find it looks better with a different number (e.g. because the smoke ring has height) then let us know.

**Comment by MrRowey** [comment]
Based on my testing this works as descried and the current paraments are good :)

**Comment by Hdt80bro** [comment]
Perfect, we can merge this then

**Pull request merged**
