### PR TITLE
GetReclaimCosts() - Grab blueprints after we know it's a unit

### PR DESCRIPTION
**Pull request by Crotalus**
As a safeguard only get blueprints after we're sure it's a unit and actually need to use blueprint values.

See comment here about GetBlueprint() on a shield bubble entity crashes the game.
https://github.com/FAForever/fa/issues/2045#issuecomment-922841853

### CODE REVIEW

**Comment by Garanas** [comment]
Is this also called on props?

**Comment by Crotalus** [comment]
Yeah, GetBlueprint() on props are safe. So in this case it probably never will cause a problem but we save a call to GetBlueprint() at least.

**Review by Garanas — APPROVED** [review]

**Comment by Garanas** [comment]
I did something wrong, why are the other commits in here? Should I have force-pushed?

**Comment by Crotalus** [comment]
Seems like the branch got merged into itself somehow. I can try re-push the branch to correct it, one sec

**Comment by Crotalus** [comment]
Now it's based on the latest deploy/fafdevelop so "Rebase and merge" should work now

**Comment by Garanas** [comment]
Great 😄 , merging this too

**Pull request merged**
