### PR TITLE
Justify87's map preview slot switch

### PR DESCRIPTION
**Pull request by aeoncleanse**
He closed his PR #1299 , but I have this copy with a bit of cleanup done.

### CODE REVIEW

**Comment by Justify87** [comment]
Since the rating label is now part of the class of the map preview, why doesn't it show in the large map preview?

**Comment by aeoncleanse** [comment]
I'm not sure...

**Comment by aeoncleanse** [comment]
Have solved the big map preview thing

**Comment by Justify87** [comment]
How? I also was looking into it but couldn't figure it out.

**Comment by aeoncleanse** [comment]
Check here  5b9ee6d02bf718d12f740a3e1cf99fcd118dcaa3

**Comment by Justify87** [comment]
I see. I forgot that it needs to be refreshed everytime something changes.

**Comment by Justify87** [comment]
Why did you close it?

**Comment by aeoncleanse** [comment]
It's been merged :)

**Comment by Justify87** [comment]
Ah. Nice! :-)

**Pull request closed without merging**
