### PR TITLE
Normalize air factory roll off times

### PR DESCRIPTION
**Pull request by Basilisk3**
In this PR I try to normalize the roll off behaviour for all Air Factories. My aims are:

- All Air Factories must build engineers at the same rate. This is not the case right now, as described in #5627. In other words: Right now, some factories can build sooner after a prior engineer has been finished.
- No factory must have a significant advantage over the other. For example, one factory should not have a significantly more efficient roll off animation.

**Tasks:**
- [x] Evaluate the efficiency of the different roll off animations
- [x] Make the Seraphim Air Factory build engineers at the same rate as Land Factories and the Aeon Air factory
- [x] Add new roll off points where it makes sense, and improves pathfinding
- [x] Add Garanas' automatic rotation towards the optimal rollout point for the Seraphim Air Factories
- [ ] Add Garanas' automatic rotation towards the optimal rollout point for the UEF Air Factories
- [ ] Add Garanas' automatic rotation towards the optimal rollout point for the Cybran Air Factories
- [x] Unify the formatting for RollOffPoints in the .bp

Not possible without changing the animation:
- [ ] Make the UEF Air Factory build at the same rate as Land Factories and the Aeon Air factory
- [ ] Make the Cybran Air Factory build at the same rate as Land Factories and the Aeon Air factory

**Explanation of the changes:**
- Roll out points: The Aeon and Seraphim get an additional roll out point. They used to only be able to release engineers out of their sides, which, looking at their models, did not make much sense. Now engineers can move straight out of both factories, but can still choose to take one of the sides, if it makes sense for them. This makes pathfinding less complicated.
- Automatic rotation of engineers towards the optimal rollout point: I introduced this for the Seraphim Air Factory for now. 
- Build-Cooldowns: To bring the Seraphim Air Factory in line with the Aeon Air Factory, I decreased its cooldown by 4 ticks. From my testing, both factories behave exactly the same now. To bring the Cybran and UEF Air Factories in line with these two, the animations of both will have to be sped up, which is controversial and still up to debate.

### CODE REVIEW

**Comment by Garanas** [comment]
This is looking good 😃 !

**Comment by Basilisk3** [comment]
> This is looking good 😃 !

Thanks, I will try to implement your engineer-roation feature to the factories that don't have it yet, to close #5625. I hope that is okay.

**Comment by Garanas** [comment]
Of course it is - looking forward to the end result!

**Comment by Basilisk3** [comment]
Concerning the automatic engineer turning: I have managed to introduce it for the Seraphim Air Factory, but I am having problems with the UEF and Cybran Air Factories. Both will lower their platforms, then turn the engineer and let it move out correctly. But afterwards both factories won't raise their platforms anymore. 

If fixing this is more complicated, it would probably be better if this is done in another PR.

**Comment by Garanas** [comment]
I'll see what I can find for you

**Comment by Basilisk3** [comment]
I did some maintenance.

**Comment by Garanas** [comment]
@Basilisk3 The current changes are a great start, great work 👍

**Pull request merged**
