### PR TITLE
Improved Rhino stats

### PR DESCRIPTION
**Pull request by RabidPope**
The unit is decent but suffers when considered in a 1v1 game against either shielded t2 or Ilshavoh. My proposition is simple. Reduce the mass cost to 270, e cost to 1350, and the build time to 1200.

Live version
image

Proposed version
image

### CODE REVIEW

**Comment by Garanas** [comment]
For my idea, are you the author of this forum post:
- https://forum.faforever.com/topic/6314/improving-and-normalising-rhino-stats

**Comment by RabidPope** [comment]
Yes

**Comment by Garanas** [comment]
👍 , we'll wait for the balance team on this one

**Comment by Tagada14** [comment]
This will be discussed in the coming month(s) alongside cybran T3 units. It isn't clear at this point if the Rhino needs such a buff right now.

**Comment by RabidPope** [comment]
> This will be discussed in the coming month(s) alongside cybran T3 units. It isn't clear at this point if the Rhino needs such a buff right now.

Just to put some context here, buff wise this is very small in terms of mass cost. It allows you to make 16 rhinos instead of 15. The main point is normalising the e cost, e drain, and build time.

**Comment by RabidPope** [comment]
Should I close this?

**Comment by MrRowey** [comment]
Rhino is fine as it is currently so closing this for now

**Pull request closed without merging**
