### PR TITLE
Update taunt.lua

### PR DESCRIPTION
**Pull request by speed2CZ**
Added new taunts from several characters from FA campaign. Finally some Seraphim taunts, not many, but they're the best!

### CODE REVIEW

**Comment by Sheeo** [comment]
:+1:

**Comment by Crotalus** [comment]
Nice, need to update this also when it's live:
http://supcom.wikia.com/wiki/Taunt

**Comment by speed2CZ** [comment]
No, that one is for original supcom, Im gonna create page on our wiki with updatel list.

**Comment by Crotalus** [comment]
745ee5d6443cf752807e2ad3a64e8a66a555b3a3

**Pull request closed without merging**
