### PR TITLE
Fix issues with extractors

### PR DESCRIPTION
**Pull request by Garanas**
Fixes an issue reported by AlfaViTe#4489 on Discord where extractors would still produce mass even when they are paused. Removes some old TA-like code that caused an extractor to loop over all the markers of the map when it is created. This can easily be more than thousands of markers on AI-related maps.

### CODE REVIEW

**Comment by Sheikah45** [comment]
Oh wait it actually did use the amount of the marker? Why when I changed it then did that never affect the production rates

**Comment by Garanas** [comment]
In a `_save.lua` file a mass marker is typically defined as:
```lua
                ['Mass 38'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ), -- <-- camel case
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 337.5, 74.9258, 449.5 ),
                },
````

The code in question:

```lua
        for _, v in pairs(markers) do
            if v.type == 'MASS' then -- <-- all upper case
                local massPosition = v.position
                if (massPosition[1] < unitPosition[1] + 1) and (massPosition[1] > unitPosition[1] - 1) and
                    (massPosition[2] < unitPosition[2] + 1) and (massPosition[2] > unitPosition[2] - 1) and
                    (massPosition[3] < unitPosition[3] + 1) and (massPosition[3] > unitPosition[3] - 1) then
                    self:SetProductionPerSecondMass(self:GetProductionPerSecondMass() * 10)
                    break
                end
            end
        end
```

It would never find the correct marker type.

**Comment by Garanas** [comment]
And with that said - especially with Uveso's marker generator in play - when you start building any extractor (whether upgrading or directly) it would happily go over all the markers of the map 😄

**Comment by Sheikah45** [comment]
Lol the name mismatch

**Comment by speed2CZ** [comment]
Fix the string and see the bug reports coming it to find out how many maps have this :D

**Pull request merged**
