### PR TITLE
Fixed on/off of mods dependencies in ModsManager

### PR DESCRIPTION
**Pull request by KionX**
**Repeatedly** disabling dependencies did not disable dependent mods.
Fixed Esc when open from **main menu**. Not lobby.

### CODE REVIEW

**Comment by shalkya** [comment]
I need more explanation here.
I don't see any improvement compare to what we have right now. When you uncheck common mod tools, it already deactivate the dependent mods. When you checked a dependent mod and having common mod tools off, it would check it automatically.
When you are choosing your mods, you can already press esc to come back to lobby.

**Comment by KionX** [comment]
Corrected the description.

**Comment by shalkya** [comment]
"Fixed Esc when open from main menu. Not lobby." that i was able to test without issue.
"Repeatedly disabling dependencies did not disable dependent mods." that i still don't get, @Uveso maybe you can explain that to me ? maybe it's not for ui mods, i've tested only with common mod tools.

**Comment by KionX** [comment]
Here are a few scenarios.
1. EcoManager on, Common Mod Tools off.
2. EcoManager off, EcoManager on, Common Mod Tools off.
3. Common Mod Tools off.

**Comment by Uveso** [comment]
@shalkya 
`When you uncheck common mod tools, it already deactivate the dependent mods.`
Exactly this was NOT always the case.


Lets say you have `common mods tools` and `UI Party` on.
If you disable `common mods tools`, then also `UI Party` is off. (like expected)

Same again, `common mods tools` and `UI Party` are on.
First disable and enable `UI Party`.
Now, if you disable `common mods tools`, `UI Party` is still on.

**Comment by shalkya** [comment]
alright i see now.
Tested works well.

**Pull request merged**
