### PR TITLE
Stinger and C14 Star Lifter: Fix, so they no longer miss low height units

### PR DESCRIPTION
**Pull request by Basilisk3**
**Changes:**
Added a slight amount of homing to the Stinger and C14 Star Lifter
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units (Stinger only)
Health = 880 --> 920 (Stinger only)

Tries to fix the Stinger (and the C14 Star Lifter) missing units it really shouldn't miss. It also gains a slight buff to its hit points in line with its faction's theme.

### CODE REVIEW

**Comment by Basilisk3** [comment]
Ready for review.

**Comment by Tagada14** [comment]
You need to be careful with the muzzle velocity, if you make it too high then the unit will miss land units that have small height.
@Garanas Correct me if I am wrong and this has been fixed btw.
If it wasn't then what happens is the projectile impacts the ground at the end of the tick and the game doesn't register the hit to the unit.

**Comment by Garanas** [comment]
It is not - the bug is still in the game. When a projectile hits multiple targets in the same tick then it ends up processing the furthest (or last) target it hit, which could be the terrain.

**Comment by Basilisk3** [comment]
I reduced the increase to 50 to be on the safe side. Is there a rough estimate at which values this bug starts to occur? After some tests, it appears to work fine at 50.

**Comment by Tagada14** [comment]
It would be best to test on some small units to be on the safe side. I suggest trying it out with Aeon T1 artilleries since they are very short.

**Comment by Basilisk3** [comment]
I tested it, and that bug occurs even at the muzzle velocity we have right now, which is 40 (though rarely). At lower values, it seems to never happen. At 60 the unit misses the Fervor most of the time. 

I will investigate adding soft tracking to it again.

**Comment by Garanas** [comment]
An alternative solution is to increase the vertical height of the collision box of 'flat' units

**Comment by Tagada14** [comment]
Please revert the hp changes for the Stinger, we would like to buff it in other ways.

**Comment by Basilisk3** [comment]
@Tagada14 I reverted it.

**Review by Tagada14 — APPROVED** [review]

**Pull request merged**
