### PR TITLE
Increase modularity and testability in PenguinAutoBalance

### PR DESCRIPTION
**Pull request by Penguin5**
Increases modularity/testability for the new autobalancer via the DetermineTeams function, which can generate testing data by being called  with (true, true)

### CODE REVIEW

**Comment by Garanas** [comment]
This is great - is it decoupled enough that you could place it in another file, and import that accordingly? That would reduce the amount of code in the lobby.

**Comment by Penguin5** [comment]
Theoretically, but when I tested that, it would not work in its current location (for the in-lobby autobalance button) because of an error for too many upvalues (limit of 32).

**Comment by Garanas** [comment]
Ah, yes - that is a known issue 😞 .

**Comment by Penguin5** [comment]
So, can this be merged?

**Pull request closed without merging**
