### PR TITLE
Feature/soft stop

### PR DESCRIPTION
**Pull request by Crotalus**
New keymap 'soft_stop' which can be mapped by the user to whatever key wanted. 

With soft_stop, all factory orders except the current will get deleted. If you want to delete all orders press soft_stop again or use normal stop command to clear the queue instantly

Also added special stop-handling for silo units to prevent accidental cancellation when building missiles in SML, strat subs etc. Not sure if this also should be counted as soft_stop or always default. Shift-Stop will cancel all in this case.

### CODE REVIEW

**Comment by Crotalus** [comment]
Seems like #262 contains some discussions about this. Also:
http://forums.faforever.com/forums/viewtopic.php?f=42&t=9122

**Comment by Crotalus** [comment]
Maybe should scrap the option and instead make it as an bindable, that way people can choose whatever behavior they want themselves

**Comment by Crotalus** [comment]
Added soft stop support to silo units to prevent accidental stop of missile building

**Comment by CodingSquirrel** [comment]
Based on the code and the fact that the phim battleship has the category SILO it probably does, but does the soft stop also work for it and other nuke ships as well? Nothing worse than having a battleship building a nuke and pressing stop to make it stop moving.

**Comment by Crotalus** [comment]
Yeah should work for all units which has the SILO category defined

**Comment by Crotalus** [comment]
`release/3652`

**Pull request closed without merging**
