### PR TITLE
Normalize Notha aircrash damage

### PR DESCRIPTION
**Pull request by quark036**
It was 25, all other t2 fb are 200

Credit to KrogothFTW and Korbah for pointing it out.

### CODE REVIEW

**Comment by Sheeo** [comment]
I'd like to point out that t1 and t2 transports have highly irregular crash damage as well.

@Zockyzock @ppipp want to make a decision on this? :)

**Comment by quark036** [comment]
Want me to put those into this pr too?

**Comment by quark036** [comment]
Also, t1 transports all have 100 crash damage

**Comment by quark036** [comment]
For t2, cybran and aeon have no crash weapon, and uef and sera both do 25 dmg, which seems odd that its lower than t1 transports

**Comment by quark036** [comment]
What seems sensible is make all the t2 transports do 200 crash damage, like the t2 fbs

**Comment by quark036** [comment]
Oops I messed up with github, making a new pr

**Pull request closed without merging**
