### PR TITLE
Fix #1628 slow and unreliable reclaim view

### LINKED ISSUE #1628: Reclaim view unreliable and slow
I often see reclaim numbers for wrecks that aren't there, or then I don't see reclaim numbers for wrecks that are there. Likewise the numbers "jump" around depending on zoom level and what part of map I look at. Before the optimizations you could rely on the numbers, now you have to zoom and fiddle around a while before they show correct values. I got used to using the feature alot but now it got degraded quite badly.

### PR DESCRIPTION
**Pull request by micheljung**
Signed-off-by: Michel Jung <michel.jung89@gmail.com>

### CODE REVIEW

**Comment by Crotalus** [comment]
Nice work, splitting / reloading world camera view causes it to crash though, it needs to recreate the labels / clear label table (or use weak references) to fix that.

**Comment by micheljung** [comment]
Thx for the additions @aeoncleanse :) Did you fix what crotalus' pointed out?
And, if we include the issue-IDs in our commits it's easier to figure out why this commit was done :)

**Comment by aeoncleanse** [comment]
Didny even see it and not sure what he means

**Comment by speed2CZ** [comment]
Hotkeys Home and End and for splitting the view into two and joining it back to one. That causes an error

**Pull request merged**
