### PR TITLE
Prevent corrupted maps from showing

### LINKED ISSUE #351: Map preview bug
I not have a crash, just warning

info: Pausing background task "Map loader /maps/scmp_019_3v3.v0003/scmp_019_3v3.scmap"
info: Background task "Map loader /maps/scmp_019_3v3.v0003/scmp_019_3v3.scmap" paused.
info: Starting background task "Map loader /maps/x1mp_014/x1mp_014.scmap"
info: Aborting background task "Map loader /maps/scmp_019/scmp_019.scmap"
info: Background task "Map loader /maps/x1mp_014/x1mp_014.scmap" running.
warning: Error in file /lua/RuleInit.lua : Unknown exception
debug: MEM: -31 bytes RULE
info: Background task "Map loader /maps/scmp_019/scmp_019.scmap" aborted.
info: Active game mods for blueprint loading: \000{ }
info: Loading blueprints...
warning: Error running OnKeySelect script in CScriptObject at 11e65580: Unable to find file /maps/SCMP_015.v0001/SCMP_015_save.lua
         stack traceback:
         	[C]: in function `doscript'
         	... forged alliance\gamedata\lua.scd\lua\ui\maputil.lua(125): in function `GetStartPositions'
         	...nxt\lua\ui\dialogs\mapselect.lua(205): in function <...nxt\lua\ui\dialogs\mapselect.lua:191>
         	...nxt\lua\ui\dialogs\mapselect.lua(495): in function `PreloadMap'
         	...nxt\lua\ui\dialogs\mapselect.lua(511): in function <...nxt\lua\ui\dialogs\mapselect.lua:509>

### PR DESCRIPTION
**Pull request by aeoncleanse**
fixes #351

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Changed to return armyPositions properly (I think), but it still dies with the following error:

WARNING: ...lliance\gamedata\lua.scd\lua\ui\lobby\gameselect.lua(33): access to nonexistent global variable "EnumerateSkirmishScenarios"
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
WARNING:         ...lliance\gamedata\lua.scd\lua\ui\lobby\gameselect.lua(33): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         c:\github\fa\lua\ui\menus\main.lua(830): in function <c:\github\fa\lua\ui\menus\main.lua:829>
WARNING:         c:\github\fa\lua\ui\menus\main.lua(753): in function <c:\github\fa\lua\ui\menus\main.lua:745>
WARNING:         c:\github\fa\lua\ui\menus\main.lua(314): in function <c:\github\fa\lua\ui\menus\main.lua:299>
WARNING: Error running OnFrame script in CScriptObject at 100414c0: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/lobby/gameselect.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
         	c:\github\fa\lua\ui\menus\main.lua(830): in function <c:\github\fa\lua\ui\menus\main.lua:829>
         	c:\github\fa\lua\ui\menus\main.lua(753): in function <c:\github\fa\lua\ui\menus\main.lua:745>
         	c:\github\fa\lua\ui\menus\main.lua(314): in function <c:\github\fa\lua\ui\menus\main.lua:299>

**Comment by Sheeo** [comment]
To hook the file, you need to put your hooking code in the `schook/lua/ui/` folder.

**Comment by aeoncleanse** [comment]
This fix doesn't work. The file exists so the fix won't trigger, we need another way of checking if the save file is corrupted, then blocking it.

**Comment by Sheeo** [comment]
Gotcha. Closing this.

**Pull request closed without merging**
