### PR TITLE
Adding a 0 Damage Weapon to Guide Weaponfire of LABs

### PR DESCRIPTION
**Pull request by Uveso**
More Info: #1336

I added a Weapon with 0 damage to the Aeon Transporter to guide the weaponfire from loaded units.

Dont know if there is a better way, but at least it works :)

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Why bother with this? Nobody complains about the T1 GG. I say we do it to all four T1 Transports as well, or to none.

**Comment by Uveso** [comment]
They maybe don't complain, because LAB's can fire when loaded on all T1 transports.
The AEON T2 transport was the only transport where those units don't fire.

**Comment by aeoncleanse** [comment]
The units should fire just fine. The complaint is that, unlike the other T2 transports, you can't use the transport's weapon as a target guide to force them to fire _at a specific target_.

**Comment by Uveso** [comment]
Yes you are right, with T1 transporter and T2 Aeon Transport you have to micro the transporter over the target but the units can fire. (Also on the T2 Aeon.)

The dummyweapon only change the behavior of the transporter to stay/cycle over the target.

**Comment by aeoncleanse** [comment]
@Zockyzock This one's your territory. The dummy allows LABs to track a specific target by attacking that target with the transports. IMO either everything (Including T1 Trans) gets this, or we leave it the way it is. Your call.

**Comment by Uveso** [comment]
@aeoncleanse 
Just in case we need to add this to T1 Transports, i dont have an idea how to make it.
Just adding a dummy weapon don't work here.
It works on the T2 Aeon, because it has already a working weapon (only air), but the dummy weapon gives the ability to "aim" at groud targets.
If you have no weapon or only a dummy weapon, it will not get any target at all.

This will lead to ugly solutions like a aktive weapon with a smal Turret angle, so the turret can't aim at anything and can't fire then.
In this case, the weapon will fire sometimes. If you are flying uphill and the transporter guns has the right angle to the target, it will fire 1-2 shots.

**Comment by aeoncleanse** [comment]
It's not too tough. We'll wait on Zock's answer before worrying about it.

**Comment by Zockyzock** [comment]
There is no need for t1 or Aeon t2 transports to target fire.

**Comment by aeoncleanse** [comment]
Closed: Zock verdict

**Pull request closed without merging**
