### PR TITLE
Fix Aeon tmd deflects nuke (EQ)

### PR DESCRIPTION
**Pull request by Strogoo**
Issue #2575

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@shalkya @Strogoo this PR looks good code-wise.

**Comment by Uveso** [comment]
Do i get this right, because we have a problem with the Aeon TMD collision detection, we are changing the flightpath from nukes ???

Did you test this with the UEF commander (tactical nuke) on short range ?
(It can't change flightangle on short distances)
nukeshort

(I know we don't care about mods, but this also won't work with moded missiles like
the Black Ops TECH3 tactical missile defence.)

In my opinion we should change the Aeon antimissile flare instead of (all) nuke flightpath's

**Comment by Strogoo** [comment]
1. We aren't changing the flightpath, only turn rate at final phase.
nuke


2. This change doesn't affect tactical nuke, it has its own MovementThread.
movement

3. I don't know how t3 tmd works in BlackOps (will test it), but I doubt that this fix can break it.

**Comment by Uveso** [comment]
Sorry i wrote to much, so just my first question;

"Why" we are fixing nukes when the Aeon tmd launcher is the problem ?"

Can't we change the Aeon tmd flares ?

**Comment by Strogoo** [comment]
Well yes, you are right. Honestly, I just did it in easiest way (for me ;) Because defaultantiprojectile.lua is still not hooked, so I have to clean it up or make a new class based on it and then change tmd projectile blueprint etc etc. And here you just add some lines in one file and it works =)

Exotic just told me that he fixed it in EQ, so I will probably copy it.

**Comment by shalkya** [comment]
need to code review the EQ change also then ;)

**Comment by Strogoo** [comment]
https://github.com/FAForever/equilibrium/commit/36d7c31ce3788efaf63577328567ba3bfac05a1a#diff-4c50057a3c51be05ebd08578faafd4b2

https://github.com/FAForever/equilibrium/commit/ea8f7ec665bfc5caa46aa2ba44c4f78699f65618#diff-013dedf3e78323e4466cbe9353ba1a59

**Comment by Uveso** [comment]
Tested the new changes ingame, and it's working flawless.

@Strogoo thank's a lot for making this new PR!!!

**Pull request merged**
