### PR TITLE
Bugfix "Share Unit Cap at Death"

### PR DESCRIPTION
**Pull request by Uveso**
issue #1481

Fixed this by removing civilian armies from alive list.

### CODE REVIEW

**Comment by Uveso** [comment]
Played with this last Weekend.
2 Player and several AI's. ~16 hours playtime.
Works perfect :)

**Comment by micheljung** [comment]
*AIs

**Comment by Uveso** [comment]
I validated this with a debugline and checked if the index of the `Brain` is indeed the index position inside the global `ArmyBrains` array.

I used brain.index because using a variable is faster then executing a function. And because we are already lopping over the ArmyBrains array its easy to get the index from there.

**Comment by aeoncleanse** [comment]
5e91a56402deb9f00f823b729b50314dffe80763

**Pull request closed without merging**
