### PR TITLE
Lobby Feature: Add new button to close/open all slots

### PR DESCRIPTION
**Pull request by TheKeyBlue**
close
A new button that allows you to close all currently open and empty slots.
This can be very usefull incase you want to play a big map with only a small number of players.
It's also easier for closing off the last slot since it requires only 1 click instead of the usual 2.

# Changes coming

~~How does it work exactly:~~
### ~~left-click~~

- ~~no closed slots : all open empty slots become closed~~
- ~~all empty slots closed : all closed slots become open~~
- ~~some empty, some open : all open empty slots become closed~~

~~"closed - spawn mex" slots don't get influenced at all~~

### ~~right-click~~
~~similar to left-click, but for "closed - spawn mex" instead of closed
closed slots don't get influenced at all
for non-adaptive maps it does the same as left-click~~

### ~~ctrl + click~~
~~all empty slots become open
so both closed and "closed - spawn mex" slots change to open
easy way to reset everything incase you have a complicated mixture of open/closed/"closed - spawn mex"~~

### textures made by svenni_badbwoi

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Great PR, thanks 👍

**Comment by TheKeyBlue** [comment]
what? xD 
What part of "Changes coming" tells you that i want you to merge it already :p

There was some talk with svenni_badbwoi, for doing some different approach.
Since he thought it was too complex at the moment. (with the right-clicking and ctrl+key stuff)

**Comment by badbwoi** [comment]
Hey guys,

first of all its nice to see that the button is so desired ;)

But I believe (I'm not sure if keyblue agrees) that the button function needs to be reworked - to my mind best before launching it and people starting to like or hate the applied features/usage of button.
I'm thinking about a simple toggle button, which cycles through all three desired functions (same function on right, middle and left-click). e.g. first click "close", second click "close - spawn mex" on adaptive maps (redundant on normal maps) and third click "open".
To my mind it should look and behave like all the the other normal buttons (except "autoteams"). I prefer the old-fashioned way to avoid misuse and confusing people.

So what do you think?
And when will it be online/is there a chance to rework it - if needed-  before that?

Best regards

**Comment by aeoncleanse** [comment]
All the changes listed were crossed out. Conventionally that means all completed

**Comment by aeoncleanse** [comment]
Hmm. The suggestions are good, too. Never mind, git means we can fix this :p

**Comment by badbwoi** [comment]
Hey, yesterday I noticed that "random faction" got a different colorsetting for the buttons. I will make a version for the new button till tomorrow.

**Comment by badbwoi** [comment]
done

**Pull request merged**
