### PR TITLE
Fix multiple fire cycle bugs

### LINKED ISSUE #5576: Skipping firing cycle by manually re-ordering attacks
**Describe the bug**
It seems like RackSalvoReloadTime can be skipped if the unit has a faster fire rate by issuing a stop command or a new attack command.

**To Reproduce**
Spawn two lightning tanks or Cougars or Bouncers and a target (Czar). Micro one of them by issuing a stop command when they finish firing, and it should start firing basically immediately in comparison to the other one.

**Expected behavior**
Lightning tank has a RackSalvoReloadTime of 5 seconds, so it should only be able to fire every 5 seconds.
Cougar has a 12 muzzle salvo, fires one at a time every 0.1 seconds, a 1 second chargeup, and a 4.5 second reload so it should only be able to fire every 6.7 seconds.

**Additional context**
- Lightning tank can be fixed trivially by using the RateOfFire instead of RackSalvoReloadTime
- Bouncer requires its fire rate for its firing cycle
- Cougar waits double its RateOfFire if you use it instead of RackSalvoReloadTime, and I think it needs the rack firing sequence instead of fire rate for its animations.
- There may be other units I haven't noticed that could abuse this.

### PR DESCRIPTION
**Pull request by lL1l1**
Resolves #5576.
I'm unsure about the RackSalvoFiringState OnLostTarget change. It would be overwriting https://github.com/FAForever/fa/pull/4863 and I haven't been able to break GC laser to fire forever or ythotha storm to not deal damage.
Also I used `MATH_IRound()` because it seems to round the same way as the game does. For example, Pillar has 0.8 fire rate, which turns into 12.5 ticks wait time, which rounds to 12 with `MATH_IRound()` and 13 with `math.floor(x*10+0.5)`. Testing shows a 12 tick wait time. The reasoning is that 0.8 in floating point is 0.800000011920928955078125, which gives a reciprocal of slightly below 1.25.

### CODE REVIEW

**Comment by lL1l1** [comment]
Previous commit was to fix the ravager.

**Comment by lL1l1** [comment]
Fix #5716 in the way as described in the issue by changing `canFire()` to `not bp.ManualFire`. I haven't found anything that needs CanFire to be true to work, and it always returns false when things do work.

**Comment by lL1l1** [comment]
Please excuse the new commits.
Intended changes:
- T3 ACU with Backpack TML/Billy should not fire a second missile if given a move order after firing and the missile rebuilds before the reload is done
- Lightning Tank, Bouncer, and Cougar should not be able to rapid-fire by giving target-changing orders such as the stop command. (Fix bypassing fire cycle through OnLostTarget)
- Spearhead fires every 10 seconds exactly.
- Fix spearhead script that would make it pack its weapon randomly after being manually re-targeted repeatedly.
- Fix mobile artillery packing up twice.

Side Effects:
- Packing upon losing targets was effected by the changes meant for fixing bypassing the fire cycle, so that was adjusted a bit.

In general, any weapons outside of the intended changes should behave the same as before. Some weapons that aren't just controlled by fire rate:
- Cyb TML: 4 racks controlled by fire rate and then a rack reload
- Other faction TMLs: controlled by `WeaponRepackTimeout`
- Yolona Oss: controlled by `WeaponRepackTimeout`, but it's depressing when you trigger it by cancelling the fire order (I'll work on its firing cycle later).
- Mongoose/Ravager: "Instant unpack, Charge, Salvo, Rack reload, repack" firing cycle
- Scathis: "Unpack, Salvo, repack if lost target" firing cycle
- T3 Mobile arty: Same as scathis, but it's a single shot so you cannot give a lost target command in the middle of firing.

<details>
<summary> Spawn test units command </summary>

```
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xeb2306', 0,   -8.58,    7.98, -0.00486)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('uas0202', 0,   -9.08,  -27.52, -0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xab1401', 0,   -1.51,   -7.58,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xel0306', 0,   -2.50,    5.99,  0.22945)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('del0204', 0,    5.83,    6.43, -0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('drlk001', 0,    5.42,   -4.02, -0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('url0304', 0,   -5.65,    5.70,  0.23978)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xsb2401', 0,   -9.14,   -7.75,  0.00000)
   CreateUnitAtMouse('drl0204', 0,    9.75,    0.15,  0.02394)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('urb2108', 0,    9.29,    6.61,  0.00000)
   CreateUnitAtMouse('uel0001', 0,    1.77,    5.78,  0.51364)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('url0401', 0,  -12.11,    3.17,  0.06827)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xsb2108', 0,   12.65,    6.83,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('xrb0304', 0,   -0.18,    0.05,  0.00000)
   CreateUnitAtMouse('delk002', 0,    8.42,   -4.02, -0.00000)
   CreateUnitAtMouse('dslk004', 0,   11.42,   -4.02, -0.00000)
   CreateUnitAtMouse('xsl0301_missile', 0,    3.42,    0.98, -0.00000)

```
</details>

**Comment by Garanas** [comment]
This fixes the bugs that you mention, great work 👍 . I've been toying with it and I can't find a scenario where something happens that I did not expect.

**Pull request merged**
