### PR TITLE
Improve consistency of occupancy of props (that block pathing)

### PR DESCRIPTION
**Pull request by Garanas**
There are a lot of tiny rocks that block pathing. As a result, the pathing of units gets all messed up because we do not have flow pathing, but more realistic-like pathing. We can fix this properly now that we have all the base game script and blueprint files. All small rocks (value < 50) no longer impact pathing. All rocks that look flat also no longer impact pathing. Only the actual bigger rocks (sea rocks, field stones) still impact pathing.

As a practical result of this change, take the map Syrtis Major where units path near the cliff where a lot of rocks are:

_old behavior_

https://user-images.githubusercontent.com/15778155/195585281-50d7e41b-7849-4d78-bd36-e543a64bfb4e.mp4

_new behavior_

https://user-images.githubusercontent.com/15778155/195585310-43439c9b-fc70-4734-b6e8-a5ba17f940bf.mp4

This is best seen in-game. You can view the occupancy maps (or pathing maps) with this hotkey:
image

A few examples of how that looked before / after:

_old pathing map for Syrtis Major_
image

_new pathing map for Syrtis Major_
image

_old pathing map for Archsimkats Valley_
image

_new pathing map for Archsimkats Valley_
image

_old pathing for Open Palms_
image

_new pathing for Open Palms_
image

_old pathing for Daroza's Sanctuary_
image

_new pathing for Daroza's Sanctuary_
image

Reason for the last one is that all these 'groups of rocks' block a lot of pathing:

image

### CODE REVIEW

**Comment by Garanas** [comment]
@Hdt80bro this one is tricky to review, but could you glance over the changes quickly, see if I did anything out of the ordinary?

**Comment by Garanas** [comment]
Clear-cut example:

https://user-images.githubusercontent.com/15778155/195635131-8aa9eb86-73e8-45fa-9f29-aaf1505ff97a.mp4

https://user-images.githubusercontent.com/15778155/195635147-ac080f8d-f459-4e60-a71c-1fa5b16bd7b3.mp4

**Comment by Garanas** [comment]
This is discussed and accepted by both the creative team and the balance team. So here we go 😄

**Review by Hdt80bro — APPROVED** [review]
Looks all good. No hidden annotations or debug stuff left in :)

**Comment by Tagada14** [comment]
Even though while playing I rarely see my units getting stuck I remember going through some replays and it was painfully visible how often your units get stuck on random rocks so this is a very welcome change. Can't wait to play Desert Arena after this is merged.

**Pull request merged**
