### PR TITLE
Structure terrain slope tilting

### PR DESCRIPTION
**Pull request by The-Balthazar**
Added the option for terrain slope tilting for structures that aren't getting rotated towards the enemy, and haven't flattened the terrain already.

### CODE REVIEW

**Comment by Hdt80bro** [comment]
It looks like you plopped down some utility functions you needed inside `OnStartBeingBuilt()`--this makes them non-extensible, unreusable, and expensive. I recommend either adding them to the utilities library instead or incorporating their functionality into the function (removing the unused features). There's a couple of other concerns in them as well, but we *still* haven't gotten our guidelines updated, so that's not really fair to point out right now :)

**Comment by Hdt80bro** [comment]
I'm curious, why go through two `Rotator`s instead of directly changing the unit orientation? Does that not properly update other stuff like collisions or meshes?

**Comment by The-Balthazar** [comment]
I should put them in some form of utils file, I just wanted to get something up before I had to do life stuff. They're from my [terrain utils file from my mod](https://github.com/The-Balthazar/BrewLAN/blob/master/mods/BrewLAN/lua/TerrainUtils.lua). 

I didn't use set orientation because that involved using quaternians.

**Comment by Hdt80bro** [comment]
Ah, gotcha. Someone has actually already solved that math for us, so if you'd prefer, you can transform your rotation using `EulerToQuaternion(roll, pitch, yaw)` first.

**Comment by The-Balthazar** [comment]
I've got it working with `SetOrientation`, and while it does mean the collision lines up with the mesh and I don't have to deal with the origin being a non-standard orientation in the mesh, it does cause some graphical weirdness: The selection highlight gets weirdly offset as the incline increases, and my mod has a shielded extractor that has the bubble offset a different kind of weirdly, which indicates that there might also be other things that go a bit weird.

**Comment by Hdt80bro** [comment]
Huh, that might mean that there's more bugs to fix then. Have you found anything else besides the selection box and attached entities causing problems solved by rotators?

**Comment by The-Balthazar** [comment]
I did find that it's possible to skew the collision box with it, but that was with manually input quaternions `(1,1,1,1)`. I don't know how realistic that is an orientation, and I've been a bit busy the last few days.

**Comment by Garanas** [comment]
I can't seem to be able to push back onto this branch 🤔 

image

I also do not entirely understand why it says `hdt80bro/fa.git`

**Comment by Hdt80bro** [comment]
*Huh*

**Pull request closed without merging**
