### PR TITLE
ChatArea styling

### PR DESCRIPTION
**Pull request by 4z0t**
Some styling improvements for ChatArea of lobby

### CODE REVIEW

**Comment by Garanas** [comment]
What else do you expect to add to the pull request?

**Comment by 4z0t** [comment]
Ye some things left to be done

**Comment by Garanas** [comment]
Could you describe the other changes?

**Comment by Garanas** [comment]
Could you describe the other changes?

**Comment by 4z0t** [comment]
Since there us styling table, i applied all values from it accordingly

**Pull request merged**
