### PR TITLE
Fix Shield Disruptor VS Personal Shields

### PR DESCRIPTION
**Pull request by aeoncleanse**

### CODE REVIEW

**Comment by Sheeo** [comment]
@ResinSmoker do you have any input on this before we go for it?

**Comment by ResinSmoker** [comment]
I'd suggest making sure that the instigator is valid as often this can be
lost or become corrupted.

Resin

**Comment by Sheeo** [comment]
Fixes #501

**Comment by Crotalus** [comment]
2706b373a6497c156d7088980752d34a45c3ada2
3a358a7bad2b20c978a78cf63f9ea0aad4229ec8

**Pull request closed without merging**
