### PR TITLE
BugFix missing Bigger Strategic build icons

### PR DESCRIPTION
**Pull request by Uveso**
There are some icons missing for the build-in `Bigger Strategic Build icons` Mod:

 - Unit drlk001 (Mobile Missile Anti-Air) StrategicIconName (icon_bot3_antiair) not declared in "straticons.lua"  Missing StrategicIconName (icon_bot3_antiair) as Strategic Mod-Icon on disk
 - Unit xrl0305 (Armored Assault Bot) StrategicIconName (icon_bot3_armored) not declared in "straticons.lua"
   Missing StrategicIconName (icon_bot3_armored) as Strategic Mod-Icon on disk
 - Unit xel0305 (Armored Assault Bot) StrategicIconName (icon_bot3_armored) not declared in "straticons.lua"
   Missing StrategicIconName (icon_bot3_armored) as Strategic Mod-Icon on disk
 - Unit dalk003 (Mobile Missile Anti-Air) StrategicIconName (icon_bot3_antiair) not declared in "straticons.lua"
   Missing StrategicIconName (icon_bot3_antiair) as Strategic Mod-Icon on disk
 - Unit dal0310 (Shield Disruptor) StrategicIconName (icon_land3_antishield) not declared in "straticons.lua"
   Missing StrategicIconName (icon_land3_antishield) as Strategic Mod-Icon on disk
 - Unit xal0305 (Sniper Bot) StrategicIconName (icon_bot3_sniper) not declared in "straticons.lua"
   Missing StrategicIconName (icon_bot3_sniper) as Strategic Mod-Icon on disk
 - Unit xsl0305 (Sniper Bot) StrategicIconName (icon_bot3_sniper) not declared in "straticons.lua"
   Missing StrategicIconName (icon_bot3_sniper) as Strategic Mod-Icon on disk
 
Added new Strategic Icon
- "icon_bot3_antiair.dds"
- "icon_bot3_armored.dds"
- "icon_land3_antishield.dds"
- "icon_bot3_sniper.dds"

to directory "/textures/ui/icons_strategic/"

Insert new icons to  `strategic.lua `

### CODE REVIEW

**Comment by aeoncleanse** [comment]
The bigger icons option doesn't appear to do anything for me. Am I missing something?

**Comment by speed2CZ** [comment]
Did you restarted the game?

**Comment by Uveso** [comment]
Normal:
sinorm

Simple:
sisimple
Full:
sifull

**Comment by aeoncleanse** [comment]
97206f837bcdc5f3cee27d306db7615c12cf93e8

**Pull request closed without merging**
