### PR TITLE
Stop factory building beams when paused

### LINKED ISSUE #2387: remove the build beam when factory is paused
when factory is paused, it still displays the build beam as if you were still building. it should be turn off, so opponent can see your factory is paused.
image
image
image
image

[game.log](https://github.com/FAForever/fa/files/1754413/game.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7538250

### PR DESCRIPTION
**Pull request by speed2CZ**
Fixes #2387

Please test properly, pausing unpausing all kinds of factories when building smth or when theey are being upgraded. Cancelint the unit in production or upgrade.
Even mobile factories, so nothing get broken by this.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Can tell you right now that any carriers, Fatboy etc won't benefit from this as they don't inherit from these classes at all.

**Comment by speed2CZ** [comment]
They dont need to benefit from it as they dont have any build effect since they use building the units inside them.

Not sure what you want with the second one? I basically took this from engineers

**Comment by aeoncleanse** [comment]
Just below the new flag is an old self.BuildingUnit = true. There doesn't seem to be much need for this any more, since it can probably be replaced everywhere it's used by the new one.

**Comment by speed2CZ** [comment]
I see, I'll check that

**Comment by speed2CZ** [comment]
This goes actually much deeper than I wanted :D I did the tests only on UEF factories and they work correctly, but other factions are using different approach and this PR breaks them. So I either figure that shit out or I close it.

**Comment by aeoncleanse** [comment]
Or if the other factions already work properly, move this UEF-specific fix into the UEF class file where they belong

**Comment by shalkya** [comment]
other faction don't work properly, as you can see in the associated issue.
keep us updated on the progress you been doing here.

**Pull request closed without merging**
