### PR TITLE
Add the Lua 5.1 functions string.match and string.gmatch

### PR DESCRIPTION
**Pull request by The-Balthazar**

### CODE REVIEW

**Comment by Askaholic** [comment]
Add tests!

**Comment by Garanas** [comment]
I agree - these are perfect candidates for a few unit tests.

**Comment by KionX** [comment]
The 5.1 documentation says: "Function string.gfind was renamed string.gmatch"

**Comment by The-Balthazar** [comment]
I missed that. I guess I'll just have gmatch redirect to that then.

**Pull request merged**
