### PR TITLE
Fixing chat issues

### PR DESCRIPTION
**Pull request by CodingSquirrel**
Fixing an issue with the chat timeout.

Fixing a couple regressions introduced in commit: 5b639b80675f2c9af2eba8ecadfbb1c1104a119c

### CODE REVIEW

**Comment by Sheeo** [comment]
Hey squirrel, would you mind joining us on slack? I'll just need your email (Either pm me on forums or in faf lobby).

Looks good otherwise, but I'll leave review of this to Chris.

**Comment by CodingSquirrel** [comment]
Integrated @ChrisKitching 's change to fix the hide for chat toggle, and used the same in place of the color change in the other area that had a regression issue. And again, using hide when the background is created to fix the bars showing up when the setting is changed while the chat is open.

**Comment by CodingSquirrel** [comment]
Cleaned up the commits a bit. Should be a bit cleaner now.

**Comment by ChrisKitching** [comment]
Merged at 95f313f5590e5b56c0ead9c784bef13f69085031

**Pull request closed without merging**
