### PR TITLE
Add shiny new 'medium' buttons

### PR DESCRIPTION
**Pull request by aeoncleanse**

### CODE REVIEW

**Comment by Sheeo** [comment]
Are these integrated with anything? I'd like some screenshots :)

**Comment by ChrisKitching** [comment]
I think this is waiting on someone (probably me) to come along and do the layout tweaks necessary.
Just merging this will cause layout bugs.


That said, doing that might lead to someone else fixing them before I get to it. :P

**Comment by aeoncleanse** [comment]
Forget doing those tweaks, I've got most of it done. I'm also making the presets window/system work properly, or at least, as properly as I can. It will need more pruning afterwards. Should have this PR finalised for review by tonight, along with screenshots of the new, rather pretty layout.

**Comment by aeoncleanse** [comment]
@Sheeo You wanted screenshots? This is from post #431 

http://s356.photobucket.com/user/aeoncleanse/media/Untitled-2_zpsmi0upopx.png.html

**Pull request closed without merging**
