### PR TITLE
Passing statistics of individual units to UI

### PR DESCRIPTION
**Pull request by Garanas**
Introduces the feature of keeping track of reclaim statistics on an individual basis. The statistics are almost accurate, sometimes they are off by one or two mass. In practice that won't be noticeable. As two examples:

image

https://user-images.githubusercontent.com/15778155/183886608-ca98cf26-fc95-4e9e-b5bd-7869496400ca.mp4

This pull request uses the `unit:GetStat` and `unit:SetStat` functions that have not been used before. It allows for syncing of statistics of individual units to the UI, without passing through the user sync. As far as I can see, this is essentially free of charge. Or at the very least a lot cheaper and a lot more cheat resistance than passing it through the sync.

### CODE REVIEW

**Comment by Garanas** [comment]
It only took two months to find an accurate solution!

**Comment by Garanas** [comment]
@The-Balthazar What is a good way to check if a unit has the reclaim ability?

@Hdt80bro or @Ejsstiil , could either of you review this pull request?

**Comment by Garanas** [comment]
And if anyone knows why my commits are no longer linked to my account, please do share that too. Perhaps it has to do with my local git configuration?

**Comment by Hdt80bro** [comment]
> And if anyone knows why my commits are no longer linked to my account, please do share that too. Perhaps it has to do with my local git configuration?

Are you talking about how all of your branches you create are under FAForever instead of your forked repo? If you're creating the branches in VSCode, then make sure your remote's origin is setup correctly.

**Comment by Hdt80bro** [comment]
> What is a good way to check if a unit has the reclaim ability?
I'd reckon checking for the `RULEUCC_Reclaim` command cap in the blueprint should be fine

**Comment by Garanas** [comment]
> > And if anyone knows why my commits are no longer linked to my account, please do share that too. Perhaps it has to do with my local git configuration?
> 
> Are you talking about how all of your branches you create are under FAForever instead of your forked repo? If you're creating the branches in VSCode, then make sure your remote's origin is setup correctly.

image

I'm referring to my pretty face missing on these commits

**Comment by Hdt80bro** [comment]
> > 
> 
> I never got that to work, it appears to be culled from the blueprint last time I checked

Not culled, flattened. You can look at some of the examples in `unitviewDetail.lua`, it's something like `DecimalToBinary(bp.General.CommandCaps)[x]` where `x` is the command cap enum value (should be 21 in this case)

**Comment by Hdt80bro** [comment]
I've added temporary mass reclaimed and energy reclaimed icons for the unit view--if anyone thinks they can do better, please do!
reclaim_mass
reclaim_energy

**Comment by Garanas** [comment]
I've asked the graphic designer to see if he can come up with alternatives

**Pull request merged**
