### PR TITLE
Add EnableDiskWatch-support for UI so you can hot reload lua files

### PR DESCRIPTION
**Pull request by Crotalus**
Have a "global" reference table with the UI controls so they can be found if an UI lua file is reloaded.

### CODE REVIEW

**Comment by Sheeo** [comment]
Does this actually do the trick and allow you to hot reload all UI code?

**Comment by Crotalus** [comment]
`touch lua/ui/game/*.lua` works without getting spam in the log about destroyed elements.

It doesn't force a redraw though so already instanced UI elements can have function pointers to "old version" of code requiring reselect / redraw to actually see the change.

If we restructure the UI code some more we probably could get that to be done automatically as well.

**Comment by Exotic-Retard** [comment]
wait; if you can mess with enablediskwatch, how far can you mess with it?

currently it does not work on hooked files properly. when you reload a hooked file for something like a unit, it tries to reload all the textures *from that directory* which are usually not there.

making it use a fallback directory (base game dir) or something would be the best thing ever and essentially fix it for hooked mods.

also: currently you can reload dds textures from ui mods with it, and it works. dunno if that is useful info though

**Comment by aeoncleanse** [comment]
c059c8d3198411628fa1752b64c96a482e835f8e

**Pull request closed without merging**
