### PR TITLE
No Air Restriction Fix

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
fixes issue #2083

Now, the No Air Restriction will disable these:
- Air units except drones (needed for late-game and they can be countered with mobile AA)
- Novax Center and structures with AA or Air staging
- Naval Carriers except Atlantis (needed for naval war in late-game)

### CODE REVIEW

**Comment by PhilipJFryFAF** [comment]
imo we can leave carriers in
they have nice vision range (mostly over water) which can be very useful when fighting stealth without proper scouting tools (air scouts/spy planes)

gonna test the pr for now and check out how it works out as it is

**Comment by PhilipJFryFAF** [comment]
ok tested just now

imho we can make it so that merely air, air facs and air staging is disabled
leave static aa in (so people can build them against uef drones...) and carriers for vision/tml

**Comment by aeoncleanse** [comment]
Can we have rebase and inclusion of static AA and carriers please.

**Comment by HUSSAR-mtrela** [comment]
I'm closing this PR because it is obsolete and I create a new PR with fixes.

**Pull request closed without merging**
