### PR TITLE
Clean up various blueprints

### PR DESCRIPTION
**Pull request by Basilisk3**
## Description of the proposed changes
This PR attempts to remove the following fields from all blueprints:

`BankingSlope = 0,`
`MaxSteerForce = 0,`
`MinSpeedPercent = 0,`
`TurnRate = 0,`

## Testing done on the proposed changes
I have not found any issues with the functionality of the units. 

## Checklist
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
How certain are we that these values are meaningless?

**Comment by Basilisk3** [comment]
All units I tested still functioned normally. According to the debug dialog that lets you change units in-game, these stats all default to 0 if their respective fields are not present.

**Comment by Garanas** [comment]
@Basilisk3 can you update the changelog to the snippet format? Then we can merge this in

**Comment by Basilisk3** [comment]
I added it in with the other two changes, is that correct?

**Comment by Garanas** [comment]
My mistake, I must have been confused!

**Pull request merged**
