### PR TITLE
fix BaseMonitorPlatoonDistress function from creating infinite table …

### PR DESCRIPTION
**Pull request by relent0r**
This is a fix to the default AI function BaseMonitorPlatoonDistress.
It corrects an edge case crash that can happen when platoons are using the 'PlatoonCallForHelpAI' addon plan.

By default if 2 or more platoons are under distress the function will only check if one is under distress and then add the next even if it is already within the table. Should 2 or more platoon remain under distress for a prolonged period this causes the table size to exponentially increase in size until the game eventually starts lagging and crashes due to the table size. In logging I saw the table size go into the tens of thousands within a 3 minute period once the issue started happening.

### CODE REVIEW

**Comment by relent0r** [comment]
Uveso pointed out that there is another function related to this base monitors distress table that is also broken by default so this can't be validated. I'll fix that up and commit to this fix.

**Comment by relent0r** [comment]
have added the extra fixes and tested to validate no obvious errors.

**Review by Uveso — APPROVED** [review]
Tested and working flawless

**Comment by shalkya** [comment]
tested, no crash / no warning. Trusting Uveso on this.

**Pull request merged**
