### PR TITLE
Add link to the patchnotes to the changelog popup

### PR DESCRIPTION
**Pull request by speed2CZ**
Reaction to: https://forum.faforever.com/topic/537/read-only-sections-on-the-forum/23

Looks like this:
ForgedAlliance_2020-11-17_20-50-06

### CODE REVIEW

**Comment by shalkya** [comment]
would have been better to say "balance patchnotes". So people don't start looking for game patchnote.

**Comment by speed2CZ** [comment]
Button size is limited, maybe in a tooltip?

**Comment by speed2CZ** [comment]
Well but the webpage says its for balance, so... that should be enough?

**Comment by shalkya** [comment]
hmm well i guess. Will see we get any feedback from users on that afterward.

**Comment by speed2CZ** [comment]
My guess is that almost no one will click on it :D

**Pull request merged**
