### PR TITLE
Keybinding and Hotbuild Fixes

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
- [x] improves keybinding UI with info about conflicting key mappings
- [x] improves generation of hotbuild modifier mappings
- [x] fixes issue #1913 - Hotbuild keybinds not working
- [x] fixes issue #1914 - HotbuildKeyMap Has Conclifts With Already Bound Keys 
- [x] fixes issue #1915 - Hotbuild Labels do not update in construction menu
- [x] fixes issue #1925 - Keybinding allows an action to have 2 key bindings
- [x] fixes issue #1926 - Keybinding is showing text outside of dialog
- [x] implements #1924 feature:
 - auto-assign shift_action when user assigns a new key to action, e.g. Attack and Attack (SHIFT)
 - auto-clear shift_action when user clears old key assigned to action, e.g. Attack and Attack (SHIFT)

image

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse I resolved my merge conflicts in this PR so there is no need for rebase. This PR is complete :)

**Comment by aeoncleanse** [comment]
Rebased and merged as 2fa995a5b54f2cd6d1039b256064be6453dca6fa

**Comment by aeoncleanse** [comment]
2fa995a5b54f2cd6d1039b256064be6453dca6fa

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse thank you!

**Pull request closed without merging**
