### PR TITLE
update seraphim shader to be more realistic

### PR DESCRIPTION
**Pull request by BlackYps**
The seraphim shader looks weird at the moment. Especially on maps with very bright lighting. I gave the shader a look closer to the original SCFA shader while preserving the ability to have the teamcolor influence the shader. Here is the corresponding forum thread: https://forums.faforever.com/viewtopic.php?f=2&t=17676
The shader is tested on many maps. It reacts nicely to the different environments.

The build shader now also utilizes the teamcolor.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Picky, but could you go though and bring it fully up to style?
- `// Comments` should have a space after the `//`, be capitalised, and only have a `.` when doing complex sentences
- Please remove code, instead of commenting it out. Git provides history for us
- See if you can use blank lines (whitespace) to split chunks into sensibly divided sections with appropriate commentry. For most of us, shaders are a total mystery, so having some explanation for each logical block would be sweeeeeet

**Comment by BlackYps** [comment]
Will do the style changes.

The commented out code is new code (actually rewritten old code, but the old one was immensely hard to understand) so it is not in the git history. But it has a bug and needs someone with in depth shading knowledge to fix. I wanted to preserve it in the future so people get reminded, that this is possible. If there is another option to save the code, I am also fine with that.

 I tried to not comment literally what the code does and tried to split it in chunks already, but maybe I assumed too much knowledge. It is hard to describe what the code does for someone with zero knowledge how rendering works, though, because the result is all visual. Can you give me a hint where you need more explanation?

**Comment by aeoncleanse** [comment]
Usually it's good practise not to be too literal when programming. However, because this is a kind of open, community effort driven by novices without much experience, I encourage people who understand what's going on to put in full commentry whenever possible. Makes it easier for someone in future to maybe update or learn from it see?

For code that needs a more expert look that you've commented, maybe put a `TODO: ...` comment block above it, explaining why it's there and what needs looking at?

**Comment by BlackYps** [comment]
I decided to write a Wiki page instead of spamming the code with endless comments. I think in the wiki the information is also more likely to be found. https://wiki.faforever.com/index.php?title=Shaders

**Comment by speed2CZ** [comment]
@BlackYps can this be improved in the shader?
From certain angle the team color takes over the LOD1 model
ForgedAlliance_2019-07-22_18-42-35
with slightly different angle the unit looks fine
ForgedAlliance_2019-07-22_18-43-12
(those are gunship and ASF, but I think it happens on more units)

Some more pictures, with yellow it's really burning my eyes:
ForgedAlliance_2019-07-22_18-46-02
ForgedAlliance_2019-07-22_18-46-17

Could you investigate?

**Pull request merged**
