### PR TITLE
Fix ML exhaust effects playing during construction

### LINKED ISSUE #2396: ML does its "engine smoke" while under construction
image
i don't think this is on purpose it should be able to use its engine only when finished.

### PR DESCRIPTION
**Pull request by speed2CZ**
Fixes #2396

### CODE REVIEW

**Comment by aeoncleanse** [comment]
This fix doesn't seem right... Surely we should need to track down, and remove, the original call which creates the effect in the first place?

**Comment by speed2CZ** [comment]
It happens on layer change. You can see it in the script. Different effext for land and water layer.

Problem is that its called right away when you start building it. Since it goea from no layer to land for example.

**Comment by aeoncleanse** [comment]
So is the correct solution not to put a guard in place around the call to create effects, inside layerchange, to check completion, thereby fixing this bug in _all_ units at once?

**Comment by speed2CZ** [comment]
What all units? It's a ML specific effect inside the ML script, where else would you want the check to be?

**Comment by aeoncleanse** [comment]
Oh yes, I see now

**Pull request merged**
