### PR TITLE
Refactoring deathweapons

### PR DESCRIPTION
**Pull request by Crotalus**
Colossus

* An additional death animation
* Death weapon now using the generic codepath in sim/Unit.lua

On a side note, the way death weapons work at the moment is silly, if
you're staying 4.1 from the unit 0 damage, 4 - 7500 damage.

I will send in a gradient damage patch to make damage variable depending
on distance from centrum

### CODE REVIEW

**Comment by Sheeo** [comment]
How's this looking?

**Comment by Crotalus** [comment]
Seems to be working, needs discussion if the change is wanted though

**Comment by Sheeo** [comment]
Want to spin this off on the forums then? :)

**Comment by Crotalus** [comment]
Thread here:
http://forums.faforever.com/forums/viewtopic.php?f=2&t=9317

**Comment by Crotalus** [comment]
Ok, people seems to be favorable of the change so I guess we aim for 3642 with this PR

**Comment by Sheeo** [comment]
:+1:

**Comment by Sheeo** [comment]
Needs rebasing, I'm closing this.

**Pull request closed without merging**
