### PR TITLE
Removing "Radar" Ability from Tech 1 Bombers as part of Balance Patch.

### PR DESCRIPTION
**Pull request by JJ173**
Saw a post on Slack that the UEF Tech 1 Bomber is showing that it has a Radar Ability when it doesn't. This was done for Balance Patch.

### CODE REVIEW

**Comment by Crotalus** [comment]
They do:
https://github.com/JJ173/fa/blob/567d3be838709aa23e211e99f4dbedb6c483aefa/units/UEA0103/UEA0103_unit.bp#L209

**Comment by aeoncleanse** [comment]
@Crotalus  - He's doing this for the balance patch, which removes the radar. It's all cool :)

**Comment by Crotalus** [comment]
Haha, ok then all fine :)

**Comment by JJ173** [comment]
Sorry @Crotalus I'll make them more clear.

**Comment by JJ173** [comment]
Much better :D

**Comment by aeoncleanse** [comment]
a60c06c98312705360f25ebdd7e1d7b772e5e96e

Merged into the balance branch

**Pull request closed without merging**
