### PR TITLE
Fix various annotations

### PR DESCRIPTION
**Pull request by 4z0t**

### CODE REVIEW

**Comment by Garanas** [comment]
What is the idea of the `@` symbol?

**Comment by 4z0t** [comment]
> What is the idea of the `@` symbol?

Wdym?

**Comment by Garanas** [comment]
Like so:

`---@return number @ float from 0 to 1`

**Comment by 4z0t** [comment]
It adds comment next to param

**Comment by Garanas** [comment]
The rest of the repository uses `#` for that, can you do so too?

**Comment by 4z0t** [comment]
@Garanas edited.

**Comment by Garanas** [comment]
A lot of these annotations have been done so by other pull requests

**Pull request closed without merging**
