### PR TITLE
Added toggle option to disable chat colors, fixed factional font colo…

### PR DESCRIPTION
**Pull request by Rackover**
…r, fixed observer color

### CODE REVIEW

**Comment by shalkya** [comment]
image
can you pls remove the bold, and make the toggle on by default.

**Comment by shalkya** [comment]
image
there is an issue with bold still ?

**Comment by Rackover** [comment]
I thought you wanted boldness to disable only when the factional font color was enabled...

**Comment by shalkya** [comment]
never said anything like that xD
i just said you make a toggle : 
if on => we get your full addition (color + bold)
if off => we let people get the lobby as before.

**Comment by shalkya** [comment]
image
doesn't seems to work

**Comment by shalkya** [comment]
tested and behave as expected.

**Pull request merged**
