### PR TITLE
Shard Adjustment

### PR DESCRIPTION
**Pull request by MrRowey**
Completes #4981

### CODE REVIEW

**Comment by Basilisk3** [comment]
I don't know a single unit that does x.y amounts of damage. It is better if the values are rounded to the nearest integer, because the UI does not indicate if a unit has 0.x hp, for example. 

Also, the unit is comically fast (a **third** faster than frigates, which are already extremely fast) and tiny, which results in them driving in front of your other naval units and dying. There is no reason for the unit to be kept in this state, size increases and speed nerfs have already happened to other naval support units, for similar reasons. 

I can understand, if you did not like the numbers I proposed in my pull request but touching the unit's speed and size are mandatory in my book.

**Comment by Hdt80bro** [comment]
Perhaps these should be brought to the balance team's attention
https://github.com/FAForever/fa/blob/deploy/fafdevelop/units/UEL0203/UEL0203_unit.bp#L304
https://github.com/FAForever/fa/blob/deploy/fafdevelop/units/UEA0103/UEA0103_unit.bp#L263

**Comment by Garanas** [comment]
@MrRowey / @Spikey84 fractional numbers does not work for damage. The engine will round them, not sure in which direction but it doesn't matter. You'll have to make a choice between 7 or 8. @Hdt80bro found a few other cases, best to make a choice there too and round them in the blueprint

**Comment by Garanas** [comment]
Apparently we were wrong @Hdt80bro , the test setup was bad.

```lua
ForkThread(
    function()
        WaitSeconds(1.0)
        LOG("Doing damage")
        local val = 0.2
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
        Damage(nil, self:GetPosition(), self, val, 'Normal')
        WaitTicks(1)
    end
)
````

This does about 4 damage over time, meaning the numbers are fractional but what we get to see (in the UI) is not

**Review by Tagada14 — APPROVED** [review]

**Pull request merged**
