### PR TITLE
Automate creation of the changelog

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Continuation of #6137 

Updates the Github workflow file to create a changelog without the need to run the bash script on your system. The workflow removes the need to have a Bash interpreter available on your system. At the moment it outputs the following file:

[changelog.md](https://github.com/FAForever/fa/files/15140017/changelog.md)

Which is a great start!

## Testing done on the proposed changes

Run the bash script locally and on Github via the workflow.

### CODE REVIEW

**Comment by Garanas** [comment]
@Sheikah45 and/or @Brutus5000 would either of you be available to review the workflow file? In particular I do not fully understand why the script fails when it's not run in the faf-lua container. See also the failed runs.

**Comment by Sheikah45** [comment]
The workflow does run in the lua container though. It is specified in the container line of the yaml as part of this PR. From the log messages it just looks like the container does not have bash installed in it.

**Comment by Sheikah45** [comment]
Also why are you specifying bash? Why not just execute the file and allow the shebang to tell the system how to execute it

**Comment by Sheikah45** [comment]
Also you are calling combine.sh as if it is in the root directory but it looks like the file lives in changelog/snippets so just ./combine.sh will result in file not found

**Comment by Garanas** [comment]
@Sheikah45 processed your feedback 👍 

> Also you are calling combine.sh as if it is in the root directory but it looks like the file lives in changelog/snippets so just ./combine.sh will result in file not found

Note the working directory that is set!

**Comment by Sheikah45** [comment]
Ah yeah I had missed that

**Pull request merged**
