### PR TITLE
Add Divisions to scoreboard

### PR DESCRIPTION
**Pull request by 4z0t**
Related to this #4258, however can't test it since everybody must have this code on their side in order to see division of every player ~~(by default all gm's lmao) and position must be corrected for sure.~~ (Works in autolobby only) Decided to not change base scoreboard layout leaving it for modders.

### CODE REVIEW

**Comment by 4z0t** [comment]
@Garanas I can leave only the fact of divisions, because this PR waits for too long

**Comment by 4z0t** [comment]
@Garanas what are we doing with this one?

**Comment by 4z0t** [comment]
It also requires other division textures.

**Comment by Hdt80bro** [comment]
Is this supposed to add divisions to the scoreboard or lobby? I see code that sets up both, but not actually doing either.

**Comment by 4z0t** [comment]
@Hdt80bro it adds only the fact that player has division. Those are provided through gameoptions.

**Comment by BlackYps** [comment]
It's supposed to be for the scoreboard. Maybe we can show them in the lobby as well at a later point, but for now the focus is the scoreboard

**Comment by 4z0t** [comment]
I don't see a better place for divisions in base scoreboard.

**Comment by BlackYps** [comment]
It's supposed to replace rating

**Comment by 4z0t** [comment]
In base scoreboard rating is concatenated with nickname. What i mean is current code base isn't suitable for any changes like this. I will add in my scoreboard for sure 🙂

**Review by Garanas — APPROVED** [review]

**Pull request merged**
