### PR TITLE
Aeon Palace: Add missing info to blueprint

### LINKED ISSUE #1706: Aeon Palace shield stops working after giving to ally
kinda ruined our game

replay: 5480508

### PR DESCRIPTION
**Pull request by TheKeyBlue**
So i added the missing blueprint data, like speed2 suggested, mostly copy/paste from Aeon T3 shield
And that solved the issue: fixes #1706

Probably a good time to balance it a little?
Atleast regarding shield assist and reclaim values.

### CODE REVIEW

**Comment by duk3luk3** [comment]
Could you please make a commit that adds the original (gpg) blueprint, and then a second commit with your changes?

That's what we've always done when adding new files, it helps with debugging and tracking what actually changed.

**Comment by CookieNoob** [comment]
lol 5 mass cost... maybe our balance councilor should suggest some new values for the economy part of the blueprint @Zockyzock

**Comment by TheKeyBlue** [comment]
Allright, i added a commit for the original blueprint

**Comment by Zockyzock** [comment]
give it 2000 mass, 30000 energy and 3000 build time for the sake of capturing. Values are loosely made up and up for discussion if there is any reason to spend more thought into it.

**Pull request merged**
