### PR TITLE
Try to preserve the original name field of a marker

### LINKED ISSUE #5510: AddBuilderManagers will not take NavMesh generated markers
**Describe the bug**

This is in regards to this report 
https://forum.faforever.com/topic/6538/ai-sea-gameplay-problem/5
This is the AddBuilderManagers function as it stands right now.
`    
AddBuilderManagers = function(self, position, radius, baseName, useCenter)

        local baseLayer = 'Land'
        position[2] = GetTerrainHeight( position[1], position[3] )
        if GetSurfaceHeight( position[1], position[3] ) > position[2] then
            position[2] = GetSurfaceHeight( position[1], position[3] )
            baseLayer = 'Water'
        end

        self.BuilderManagers[baseName] = {
            FactoryManager = FactoryManager.CreateFactoryBuilderManager(self, baseName, position, radius, useCenter),
            PlatoonFormManager = PlatoonFormManager.CreatePlatoonFormManager(self, baseName, position, radius, useCenter),
            EngineerManager = EngineerManager.CreateEngineerManager(self, baseName, position, radius),
            BuilderHandles = {},
            Position = position,
            BaseType = Scenario.MasterChain._MASTERCHAIN_.Markers[baseName].type or 'MAIN',
            Layer = baseLayer,
        }
        self.NumBases = self.NumBases + 1
    end,
`

This particular line here
`BaseType = Scenario.MasterChain._MASTERCHAIN_.Markers[baseName].type or 'MAIN',`

So the function is passed the name of the marker, which is the .Name property.
It then looks this up in the masterchain. Which won't contain the NavMesh markers.

So the BaseType will always be 'MAIN' since the marker doesn't exist in the marker chain.

**To Reproduce**
Run any AI game that uses generated markers and the bases will not be named correctly.

**Expected behavior**
The BaseType will use the type property of the marker used to create the base.

**Additional context**
I looked at a few options, but the best one is to have a helper function in the marker utilities module that will lookup the marker for a marker name and return it. Then update the AddBuilderManagers function that is against the default AI brains to perform this check while leaving the base functionality as is.

The other option is to modify the functions and pass the entire marker through rather than just the name and position. This is possible and makes sense but would negatively impact 3rd party AI that leverage these functions. It would require getting functions like `AIFindNavalAreaNeedsEngineer` to return the marker itself rather than just the position and name.

### PR DESCRIPTION
**Pull request by Garanas**
Closes https://github.com/FAForever/fa/issues/5476
Closes #5510

### CODE REVIEW

**Comment by Garanas** [comment]
@relent0r would this suffice?

**Comment by relent0r** [comment]
> @relent0r would this suffice?

The only issue I see and its not an issue in normal usage due to the cache.
Line 131 is checking for marker.type of 'Spawn' but the marker.type == 'Blank Marker'.

info:  - Name: ARMY_5
info:  - Position: table: 14D7C230
info:  -    1: 119.5
info:  -    2: 20.093799591064
info:  -    3: 519.5
info:  -    type: VECTOR3
info:  - RallyPoints: table: 26DC91E0
info:  - Size: 25
info:  - color: ff800080
info:  - orientation: table: 14D7CF78
info:  -    1: 0
info:  -    2: 0
info:  -    3: 0
info:  -    type: VECTOR3
info:  - prop: /env/common/props/markers/M_Blank_prop.bp
info:  - size: 25
info:  - type: Blank Marker

One thing I'm noticing though is we need to do work in the code due to the lower vs upper case we are using. 
e.g

function AIGetMarkerLocations(aiBrain, markerType)
    local markerList = {}
    if markerType == 'Start Location' then
        local tempMarkers = AIGetMarkerLocations(aiBrain, 'Spawn')
        for k, v in tempMarkers do
            if string.sub(v.Name, 1, 5) == 'ARMY_' then
                table.insert(markerList, {Position = v.Position, Name = v.Name})
            end
        end
    else
        local markers = import("/lua/sim/markerutilities.lua").GetMarkersByType(markerType)
        if markers then
            for k, v in markers do
                table.insert(markerList, {Position = v.position, Name = k})
            end
        end
    end

    return markerList
end

Ideally I don't need to actually create the table anymore and can just pass the markers straight through. But I just need to figure out how to make sure its consistent.

**Comment by relent0r** [comment]
Perhaps this is a case where having both lower and upper case will make life easier :)

**Comment by Garanas** [comment]
@relent0r how's this solution? In general, we should no longer rely on the marker chain

**Pull request merged**
