### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by Crotalus**
Fixed some errors in game.log

### CODE REVIEW

**Comment by ChrisKitching** [comment]
In general, you seem to be adding defensive null checks to naively prevent lua runtime errors.

Often, it's better to solve this sort of problem by preventing nils from ever reaching the problematic place, otherwise you just end up with defensive nil checks *everywhere*.
This might not be possible in al cases, but, generally, defensive nil checks hide other bugs. The fact that a nil is being passed to a function that can't meaningfully process them is possibly a symptom of a larger problem.

... But not always :P

**Comment by Sheeo** [comment]
Indeed I'm skeptical about the Cybran massfab unit--I don't remember seeing these rotator errors in previously.

**Comment by DarkmatterVale** [comment]
@Sheeo,

If you change that back to 10, does that fix the problem?

**Comment by Sheeo** [comment]
I don't know -- I have yet to be able to reproduce crashes arising from it consistently.

There was another destruction thread value changed with c72643cfeb1e997a8d819f4eeb6f650067320079 -- for seaunits.

It's worth investigating :)

**Comment by Sheeo** [comment]
@Crotalus if this PR is directed at 3641, it should target the release/3641 branch.

**Pull request closed without merging**
