### PR TITLE
Bring back the map label

### PR DESCRIPTION
**Pull request by ChrisKitching**
.. And make the text animation less infuriatingly slow.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
I was wondering about this, thought it might not be loading just because it was local.

**Comment by ChrisKitching** [comment]
Nah, it wasn't loading because you broke it ;)

**Comment by aeoncleanse** [comment]
Checked, working :+1:

**Comment by Sheeo** [comment]
I'm sorry I didn't catch this the first time around. Good work Chris :)

**Pull request closed without merging**
