### PR TITLE
Cybran land factories hq and sup

### PR DESCRIPTION
**Pull request by MadMaxFAF**
re work of the cybran factories

### CODE REVIEW

**Comment by Garanas** [comment]
@MadMaxFAF is this ready?

**Comment by MadMaxFAF** [comment]
no still got the air and navy factories to do and balth said he would do the textures

**Comment by Garanas** [comment]
You can make separate PRs for those.

**Comment by MadMaxFAF** [comment]
ok then barring the textures it's done the ones in here are temp ones till balth dose it properly

**Comment by MadMaxFAF** [comment]
this should be ready now

**Comment by MadMaxFAF** [comment]
i can look into it

**Comment by Garanas** [comment]
They all use the same normals texture, yet when upgrading from t1 to one of the t2s the normals suddenly jump:
image

**Review by Garanas — APPROVED** [review]

**Pull request merged**
