### PR TITLE
Make Seraphim T3 Nuke damage itself

### PR DESCRIPTION
**Pull request by bamboofats**
https://github.com/FAForever/fa/issues/878

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Well, that was a hilarious thing for GPG to miss.

**Comment by Varaxis** [comment]
I thought it was Seraphim faction diversity, since their T4 nuke also did the same before you guys nixed that.

**Comment by ChrisKitching** [comment]
It's pretty unhelpful faction diversity, because it doesn't protect anything except the launcher. Your base is flattened, but at least the nuke launcher is okay!

**Comment by Varaxis** [comment]
Bases are pretty big, and exp assaults that can't be stopped in any other manner makes it worth it. ACU still may have ras and eng suite, so a nuke and half a base still useful than the enemy wiping out the base and moving on to another. Easier to aim the nuke if they're right there trying to kill you.

**Pull request merged**
