### PR TITLE
New mesh and normal texture for the valiant

### PR DESCRIPTION
**Pull request by Ajamajan**
had to reexport mesh too since the mesh normals were broken

related issue: https://github.com/FAForever/fa/issues/5891

OLD
image

NEW
image

### CODE REVIEW

**Comment by BlackYps** [comment]
It looks like the barrels of the main weapon are now flat. Is that correct?

**Comment by Garanas** [comment]
Some more images:

image

image

image

**Comment by BlackYps** [comment]
yeah, this barrel should be round in my opinion

**Comment by Garanas** [comment]
I think the problem is that the barrel has 4 sides, where as the barrel of the frigate has 5 sides. I don't think it matters much because you need to be zoomed in quite a bit, but if it is not much effort then it also can't harm 😃

**Comment by BlackYps** [comment]
It only having four sides is not a problem. Even with three sides you could interpolate the normal. You can even see in the old comparison screenshot that it was interpolated and thus appeared round before.
Luckily it is very easy to fix

**Comment by Ajamajan** [comment]
I could change it if it REALLY REALLY bothered you guys. the fact that the smaller barrels on the AA turret have more subdivisions lets me think that 4 on the bigger cannon suggests it may be intended as a hard edge barrel. since i already re-exported the mesh anyway the fix shouldnt take too long. IF it is requested.

**Comment by Garanas** [comment]
I do not personally see it as a (big) issue, the unit is already quite a bit better now than it used to be.

**Comment by BlackYps** [comment]
I personally would appreciate it, if you changed it to a round barrel :3

**Comment by Ajamajan** [comment]
i am getting mixed signals here..

**Comment by BlackYps** [comment]
Idk, Jip says it is already good, I say it would be even better if the barrel was smooth shaded. That's not a contradiction to me.
Ultimately it is your decision if you want to edit the barrel again or not

**Comment by Garanas** [comment]
I'm fine with what we have, but a smooth barrel would of course be better. I'll be merging this in because on its own this pull request is a large improvement. Feel free to make a separate pull request with the changes for a better barrel however 😃

**Comment by jospoortvliet** [comment]
Looking super nice!!!

**Pull request merged**
