### PR TITLE
Enhanced lobby rating tooltip

### PR DESCRIPTION
**Pull request by Justify87**
Tooltip shows rating and deviation of each player in the lobby. Solves #1391

2016-09-22 02_04_30-forged alliance

### CODE REVIEW

**Comment by Uveso** [comment]
With LOC tags, german translation and dummy strings for all other languages!!!
I could give you a hug for this :dancer: 

Sadly it will conflict with my latest language changes.
Translation tag `lobui_0762` ist not free
```
lobui_0762="Kontrolle erlangen"
lobui_0763="Wenn du stirbst, werden deine Einheiten an den Feind übergeben der dich besiegt hat. Einheiten die du gebaut und Allierten übergeben hast wechseln nicht den Besitzer."
lobui_0764="Zivile Fahnenflucht"
lobui_0765="Nachdem du besiegt wurdest Konvertieren deine Einheiten zu Zivilisten, vorrausgesetzt das die Karte zivilisten beinhaltet, ansonsten sterben sie."
lobui_0766="Überläufer"
lobui_0767="Wenn du stirbst laufen deine Einheiten zum Feind mit der höchsten Punktzahl über.  Einheiten die du gebaut und Allierten übergeben hast wechseln nicht den Besitzer."

```

`lobui_0768` is the next free tag.

**Comment by Justify87** [comment]
I see. Would it be sufficient if I change that with another commit? Or do I need to redo the commit I already have? My git skills are bad.

**Comment by Uveso** [comment]
its fine, icedreamer will take care of it. let it unchanged.

**Comment by Justify87** [comment]
Ok

**Comment by aeoncleanse** [comment]
03d30498c556773f5e7da1dcc0974778b41fbc82

**Pull request closed without merging**
