### PR TITLE
add lobui_0692 to loc files

### PR DESCRIPTION
**Pull request by CookieNoob**

### CODE REVIEW

**Comment by aeoncleanse** [comment]
There's a lot more LOC files to go...

**Comment by CookieNoob** [comment]
yea I am adding them atm

**Comment by TheKeyBlue** [comment]
why 7commits and not just 1? 
Just do all the lines in 1 commit. Its the same change anyway.
(i mean if you give them the same name, there is 0 value to having them seperate)

**Comment by aeoncleanse** [comment]
Don't worry, I'll squash them in the merge.

**Comment by CookieNoob** [comment]
<--- noob with github

**Pull request merged**
