### PR TITLE
Increase the muzzle velocity of the Hoplite's rockets

### PR DESCRIPTION
**Pull request by Basilisk3**
## Description of the proposed changes
**Hoplite: T2 Rocket Bot**
MuzzleVelocity: 20 --> 25

As discussed with the balance team.

## Checklist
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by MrRowey** [comment]
@Basilisk3 add the changelog then when i can merge stuff ill add this in

**Comment by Garanas** [comment]
@Basilisk3 You missed the memo 😄 !

Please create a new changelog snippet in `/changelog/snippets` named `balance.6141.md` (type.pull-request-number.md). The snippet would contain what you wrote into `3810.md`. We can then regenerate the changelog by combining the snippets via a [workflow](https://github.com/FAForever/fa/blob/deploy/fafdevelop/.github/workflows/changelog.yaml)

**Comment by MrRowey** [comment]
@Garanas I add the do not merge for a reason so I can add them to the beta patchnotes first

**Comment by Garanas** [comment]
Oh, I missed that - my mistake!

**Pull request merged**
