### PR TITLE
Window class TitleGroup scale

### PR DESCRIPTION
**Pull request by MrRowey**
Pr for #3540

### CODE REVIEW

**Comment by Garanas** [comment]
Shouldn't the rest of the window scale accordingly too?

**Comment by MrRowey** [comment]
Probably I'll fix accordingly later did decide to do this at like 1am my time do didn't realy read much into it 😆

**Comment by MrRowey** [comment]
image
 @Garanas I assume you're talking about the other 3 about the line I changed ?

**Comment by Garanas** [comment]
What LayoutHelpers does is make that part scale accordingly with the UI scaling implemented a while ago. What we have now is that the height of the window scales accordingly, but its size (top / left / right) does not.

**Comment by MrRowey** [comment]
i can adjust this

**Comment by speed2CZ** [comment]
Well have you tested it? How does it look before/after the change? The size top/left/right is not set by the number in this case. It's a reference to other element, so it changes to whatever the referenced element changes to. So it should be always correct.

**Comment by Garanas** [comment]
Closing this pull request - the issue is there to pick up for someone else.

**Pull request closed without merging**
