### PR TITLE
Reduce the lifetime for water trail emitters

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

This reduces the life time of water trails to a similar value to what we have for footprints and tread marks. When you zoom out and back in all emitters are recomputed. The water trails are surprisingly complex (multiple emitters per unit that last 10 to 15 seconds on average) and are therefore a prime target for a frame time spike.

_Adjusted life time_

https://github.com/FAForever/fa/assets/15778155/3e303f38-4407-4596-9ae9-67d19e7adab5

_Old life time_

https://github.com/FAForever/fa/assets/15778155/805732a5-cd19-4762-821f-d9f77e27681a

## Testing done on the proposed changes

Spawn in naval units and observe the trail.

## Additional context

I'd also like to review the other water trail effects.

Rebased version of https://github.com/FAForever/fa/pull/6088

## Checklist

- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
The emitters are determined by the [terrain type definitions](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/TerrainTypes.lua), specifically:

```lua
            Water = {
                AeonGroundFX01 = { EmitterBasePath .. 'aeon_groundfx_emit.bp', },
                AeonGroundFXT1Engineer = { EmitterBasePath .. 'aeon_t1eng_groundfx01_emit.bp', },
                AeonGroundFXT2Engineer = {
                    EmitterBasePath .. 'aeon_t2eng_groundfx01_emit.bp',
                    EmitterBasePath .. 'aeon_t2eng_groundfx02_emit.bp',
                },
                BackWake = {
                    EmitterBasePath .. 'water_move_trail_back_02_emit.bp',
                    EmitterBasePath .. 'water_move_trail_back_03_emit.bp',
                    EmitterBasePath .. 'water_move_trail_back_04_emit.bp',
                },
                Hover01 = { EmitterBasePath .. 'tt_water_hover01_01_emit.bp', },
                LeftFrontWake = { EmitterBasePath .. 'water_move_wake_front_l_01_emit.bp', },
                RightFrontWake = { EmitterBasePath .. 'water_move_wake_front_r_01_emit.bp', },
                SeraphimGroundFX01 = {
                    EmitterBasePath .. 'seraphim_groundfx_emit.bp',
                    EmitterBasePath .. 'seraphim_groundfx_02_emit.bp',
                },
                SeraphimGroundFX02 = {
                    EmitterBasePath .. 'seraphim_groundfx_03_emit.bp',
                    EmitterBasePath .. 'seraphim_groundfx_04_emit.bp',
                },
            },
            ```

**Comment by BlackYps** [comment]
I like that the water trails look more reasonable in general now.
We could further improve the visuals by changing that second emitter that creates this shorter trail. It looks kinda weird at the moment. I am not quite sure what it is supposed to represent. Maybe it is supposed to mimick the dissipating foam...
I would suggest either making the lifetime longer and varying the lifetime a lot to better achieve this effect, or to remove it entirely.
grafik

**Comment by Garanas** [comment]
It is supposed to be this:

image

I can make it slightly shorter and close to the unit.

**Comment by Garanas** [comment]
I'm merging this in as it works on its own. Additional changes can be done via new pull requests

**Comment by zhanghm18GIT** [comment]
图片
@Garanas Sorry to bother you, but I recently came across this pull request while studying unit movement effects, and I've also encountered a similar issue: in your second video, between 2 and 5 seconds, the trails of moving naval units suddenly disappear, and they only reappear by zooming in and out.Two units also exhibit this problem at 18 seconds in your first video.
图片
 Is there any way to avoid this problem?

I don't seem to have this issue when adding movement effects to army units; the effects don't suddenly disappear when army units move. However, this problem frequently occurs with naval unit movement effects.

**Comment by Garanas** [comment]
@zhanghm18GIT I don't know why this happens. We can only interact with emitters. The behavior of particles (created by emitters) is entirely in the engine.

**Comment by Garanas** [comment]
@zhanghm18GIT With thanks to @speed2CZ , a fix for missing ship wake effects is found in https://github.com/FAForever/fa/pull/6981!

**Comment by zhanghm18GIT** [comment]
@Garanas Thank you for letting me know. I'm very glad to see this issue resolved.

**Pull request merged**
