### PR TITLE
Cleanup of lua/ files

### PR DESCRIPTION
**Pull request by Crotalus**

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Looks great. Another thing of this sort that might be useful to add is conversion of all comments to use -- instead of #, as is standard lua syntax. Makes things look nicer in some editors (as that, plus your other changes, means things are actually standard Lua syntax at last).

**Comment by Crotalus** [comment]
The only thing left now to standard lua syntax is getting rid of "continue"

**Comment by Sheeo** [comment]
This looks good. I'm concerned about having to rebase all the other PR's after the fact, though :)

**Comment by Crotalus** [comment]
Yes, I can rebase this instead and merge it at some time when there's less PRs

**Comment by Sheeo** [comment]
Gotcha, let's do that.

**Pull request closed without merging**
