### PR TITLE
Initial integration of lobby manager code

### PR DESCRIPTION
**Pull request by Duck42**
This contains all of the code and textures used in the lobby manager SCD mod.  I've updated it to match the new lobby UI.

I was unable to test the functionality completely because I can no longer hook the lobby.lua file in FAF (see https://github.com/FAForever/fa/commit/2860bc89f174f853c3cb9f96627c505dae3e11fc#diff-76a1487a0512e42a56e35de561571ced).  Everything related to player management (creating new entries, modifying existing ones, and removing entries) should work correctly.  The actual enforcement portion (automated messages, kicking players, etc) has not been tested.

### CODE REVIEW

**Comment by Sheeo** [comment]
Hey Duck, sorry nobody has gotten back to you on this. Regarding how to test changes with FAF, see the `readme.md` file in this repository for an explanation of how to run the game with modified core code.

I think we're rescheduling this for the next release of the lobby, and I would like some serverside integration -- potentially do all the work in the client using the foe list, so it's persistent with the rest of FAF. What are your thoughts on this?

**Comment by Duck42** [comment]
Hey Sheeo, If the current functionality can be replicated in the FAF client, then moving it to the server would have some benefits (i.e. the player list wouldn't need to be stored in the game.prefs).  Still, bringing the capability to the server side means integrating the FA code and the FAF client/server code.  That a bit more involved than a (relatively) simple FA UI mod.  Unfortunately, I don't have enough time available to contribute much to that.

If you'd like to pursue that approach, I'd recommend backing out the lobby.lua shadowing until you're ready.  That way, I can put together a working Lobby Manager SCD for people to use in the meantime.

**Comment by Sheeo** [comment]
@Duck42 sounds like a plan.

**Comment by Sheeo** [comment]
@Duck42 there were some integration issues between the current 3641 mod and lobbymanager -- are you able to look into these?

I'm closing this pull request for now. Thank you for your work :)

**Pull request closed without merging**
