### PR TITLE
Terrain advancements

### PR DESCRIPTION
**Pull request by BlackYps**
I had to partially revert the fix that got rid of the water coloration on steep cliffs. When only checking for the terrain height we can get artifacts in shallow water when zooming out far because of the terrain tesselation. Then random segments of the water disappear. So as a compromise we only get rid of the start of the coloration. This is enough for reasonably steep cliffs while it minimizes the tesselation artifacts to a level that is not distracting.
Screenshot 2023-10-12 234552

The advanced shaders now use the previously unused channel in our mapwide texture for the water depth. This enables us to put the mapwide albedo "decal" into a normal slot that was already free, but we couldn't access it because of the limit of how many different textures we can sample. Now that we got rid of the need to sample the water depth texture that the engine provides, we can sample that normal slot.

The areas underwater now get their specularity reduced instead of their roughness increased, which is more physically accurate.

According to the naming scheme in #5529 I added shaders that utilize the full mask range and I added a shader that uses the pbr workflow with roughness maps without implementing the advanced splatting, which makes it much easier to use this shader with the current map editor.

The map generator will soon provide tools to easily generate the needed mapwide and pbr texture in https://github.com/FAForever/Neroxis-Map-Generator/pull/365

### CODE REVIEW

**Comment by Garanas** [comment]
Do you want these in for the 28th?

**Comment by BlackYps** [comment]
There is no rush. You can also postpone it to later if that is easier for you

**Comment by BlackYps** [comment]
Oh, the water fix should make it in, but I could extract that into a separate PR

**Comment by Garanas** [comment]
It's all fine to me; do you have a (generated) map or two that I can use to review your changes?

**Comment by BlackYps** [comment]
Do you think you will find time to review this before the release?

**Comment by Garanas** [comment]
Noticed the effect you mentioned in the screenshot; it appears to be not symmetrical:

image

image

I noticed this before too. Any idea why this is?

With regards to the sharp transitions:

image

Isn't it maybe better to revert to what we had before? At least then it visually appears smooth

**Comment by BlackYps** [comment]
It's probably because the heightmap is not completely symmetrical. It's a gpg map after all that originally also had asymmetric resource markers.

If we revert the water changes we get this again, which is a side effect of the new exponential water absorption. Unfortunately there seems to be no perfect solution. I think the best solution is to do it like in this PR and to expect map makers to not make insanely steep cliffs.
image

**Comment by Garanas** [comment]
Ah yes; I forgot about those. And is a solution where we take into account the camera position viable?

**Comment by BlackYps** [comment]
What are you thinking of?

**Comment by Garanas** [comment]
Tesselation only shows up as you're zoomed out. The rough edge / transition this pull request introduces only shows up when you're zoomed in. If I'm not mistaken then we have the position of the camera. Maybe we could use the Y-value as a linear interpolation to get best of both worlds

**Comment by BlackYps** [comment]
Ah yeah, that sounds like it could work

**Comment by BlackYps** [comment]
But how do I interpolate a boolean decision?

**Comment by BlackYps** [comment]
That was quite tricky to pull off, but I did it!

**Comment by Garanas** [comment]
I think that the grass should be less shiny but that can be controlled by the input if I'm not mistaken. Note that maps that do not use the new shaders remain unaffected.

image

image

image

image

**Comment by Garanas** [comment]
And with thanks to the last bit of work the water ramp artifacts on steep cliffs are less noticeable:

image

image

image

**Comment by Garanas** [comment]
@BlackYps also a huge fan of using the new water textures 😃 , the only thing the map is missing at this point are waves

**Comment by BlackYps** [comment]
The map is excessively shiny because I forgot to adjust the mask of the highest texture layer. That one adjusts the roughness, so it is indeed controllable by the map.

**Pull request merged**
