### PR TITLE
Global Lua optimization. Part 1

### PR DESCRIPTION
**Pull request by KionX**
Continued #3511
A total of ~1000 files are expected.

Number of optimizations 4585(globals, math, table, string, exclude ui).

### CODE REVIEW

**Comment by Garanas** [comment]
I think we should start simple: only rescope common table and math operations. This is considered a good improvement according to [the Lua book in the chapter 'Basic facts'](https://www.lua.org/gems/sample.pdf). It is also easy to review and it won't cause any hidden issues.

I agree with your last statement in #3511 that doing this type of work on all the files just makes them a lot more difficult to read. Instead, I think our focus should be on better memory management and refactoring hot-code to improve efficiency. An example of the former is https://github.com/FAForever/fa/pull/3743 that has a 10% improvement in performance when you have 900 ASF because of recycling of tables. An example of the latter is https://github.com/FAForever/fa/pull/3702, where we drastically reduce the amount of Lua byte code generated and prevent a lot of table operations by using mathematics.

**Comment by KionX** [comment]
At the moment, the total number of microoptimizations is 25699.
Maybe it's worth disabling some optimizations?

I don't plan any further work on the existing FAF code and am considering whole remake this.

**Comment by Garanas** [comment]
Yes - I'd say we limit it to:
 - globals (e.g., `CreateEmitterAtBone`)
 - math functions (as an example, `math.abs`)
 - table functions (as an example, `table.insert`)
 
And leave other engine and lua functions out of it, as they make the code a lot less readable.

**Comment by Garanas** [comment]
And what does a remake of FAF entail? 😄

**Comment by KionX** [comment]
I suggest a couple more optimizations:
Extract imports to global, for k,v in t do -> for k,v in next, t, nil do

The main idea of the FAF remake is that everything will be written in LuaJIT x64.
If necessary, other functions are added via Lua dll modules.
Graphics - DX9 (this is the simplest)
I care about the engine. I hope others will do the rest.

**Comment by Garanas** [comment]
`Extract imports to global, for k,v in t do -> for k,v in next, t, nil do` 
I was not aware of this one, I did a few benchmarks. I do not notice a significant difference, how much do you think this change is faster?

`Also after optimization, you can rename everything for better readability.`
That is not viable / maintainable in the long term, especially if you want to integrate the optimizer.

I'd be fine with this list:
 - globals (e.g., CreateEmitterAtBone)
 - math functions (as an example, math.abs)
 - table functions (as an example, table.insert)
 - k,v in t do -> for k,v in next, t, if it is faster
 
Anything else is not required for the average code and can lead to errors down the route. As an example, if you'd optimize the brain and use `GetUnitsAroundPoint` or `GetListOfUnits` directly then you'd skip the Lua versions of those functions. The same applies to Lua functions in general, as mods / maps can override those (without hooking the file, quite destructive) and we'd still have a reference to the old function.

`I care about the engine. Hope others will do the rest.`
I don't know what type of changes this would require but I'd be open to discuss it and help you with it.

**Comment by KionX** [comment]
Number of optimizations 4585(globals, math, table, string, exclude ui).
This PR is completed.

**Comment by Garanas** [comment]
This is looking good. Surprised to see that the number of optimizations is still so high. Good idea to include the string functions too.

I'll look through it and experiment with it. Great work.

**Comment by KionX** [comment]
Think about using this https://github.com/FAForever/FAFLuaJit for the lua test.
Example: https://github.com/FAForever/LOCChecker

**Comment by KionX** [comment]
What's with this PR?

**Comment by Garanas** [comment]
I've been testing it on the benchmark map and did not notice a significant change. I'm not sure if it is worth it.

**Comment by KionX** [comment]
If it does not spoil the convenience, then it will not be worse.

**Pull request closed without merging**
