### PR TITLE
Optimize AI managers

### PR DESCRIPTION
**Pull request by Azraeel**
This branch is for bugfixes, general improvements, and new features. If your change is designed to alter balance, please make 
sure your changes are rebased onto [development/balance] (https://github.com/FAForever/fa/tree/development/balance), and target that branch with your PR.

This Commit will Optimize the following Files Platoon Form Manager, Engineer Manager, Builder Manager, and Build Conditions Monitor to make them faster and less heavy on the sim. In the future I plan to add more documentation as some of these functions and entire files have poorly documented or are not documented at all.

### CODE REVIEW

**Comment by Garanas** [comment]
Great work - keep it up.

One note is to make the commit messages more elaborate. As an example, think as if you're trying to answer this with the first sentence of the commit message: 

_If applied, this commit will your subject line here_

For example:
- If applied, this commit will refactor subsystem X for readability
- If applied, this commit will update getting started documentation

The reason is for readability - it makes it a lot easier to see in the history what happens. As an example, see the history of fafdevelop.

**Comment by Azraeel** [comment]
> 
> 
> Great work - keep it up.
> 
> One note is to make the commit messages more elaborate. As an example, think as if you're trying to answer this with the first sentence of the commit message:
> 
> _If applied, this commit will your subject line here_
> 
> For example:
> 
>     * If applied, this commit will refactor subsystem X for readability
> 
>     * If applied, this commit will update getting started documentation
> 
> 
> The reason is for readability - it makes it a lot easier to see in the history what happens. As an example, see the history of fafdevelop.
> 
> With thanks to Askaholic for his suggestion.

Will do thanks for the tips :)

**Comment by Dragun123** [comment]
This code will also be breaking SCTA if it breaks Uveso and RNG

**Comment by Azraeel** [comment]
> This code will also be breaking SCTA if it breaks Uveso and RNG

I do not expect these changes to work with other AI Currently as they are core changes to how things work like discluding the AIBrain in all managers and such. This is more risky merge because of such, I'd want multi reviews before this is merged @Garanas 
@Uveso @speed2CZ

**Comment by speed2CZ** [comment]
Im not a fan of breaking stuff. How much you gain with that? Looks like you could do a lot of those optimizations even without breaking things

**Comment by KionX** [comment]
There are more and more large-scale PR optimizations that affect compatibility. This delays the release. And it will look as if the patch has broken everything. Can we postpone the compatibility-breaking PRs? Although it is unclear when the release will be.

**Comment by Azraeel** [comment]
I do not expect this to be merged for this release AT ALL @KionX

**Comment by Azraeel** [comment]
> 
> 
> Im not a fan of breaking stuff. How much you gain with that? Looks like you could do a lot of those optimizations even without breaking things

When removing AIBrain references and input into every piece of data, I do end up breaking most AI related mods, but I have to do this because I need to log the data I CAN NOT with all these AIbrain references everywhere the data becomes insanely unreadable and I can not continue to work on optimizing, rewriting, and making the ai code more reliable

I have asked Jip to help me make sure I am not breaking everyones AI including my own :)

**Comment by Dragun123** [comment]
There is a couple theoried solutions you can do. 
1) define aibrain as a local on top of file or create a globalized vsriable there. Sense most ai’s do aibrain.x if you define on top of page. 
local aibrain = GetArmyBrain(). Or self:GetBrain(). You’d atleasy partly solve the problem

2) You have to write different code. While the code you wre usings comes from an enviroment with improved efficiency its not the faf enviroment and you have to accept the differences.

3) You cannot repr the data. You van still log the data. Just have to be more careful. And know what to log for specifically.

4) I’d try and put these improvements into Swarm first. And see what happens. And do logging alot of your basic improvements here can be do via the standard ai hooking. While you won’t be able to remove aibrain references. You’ll be able to test other things

**Comment by Azraeel** [comment]
> 
> 
> There is a couple theoried solutions you can do.
> 
>     1. define aibrain as a local on top of file or create a globalized vsriable there. Sense most ai’s do aibrain.x if you define on top of page.
>        local aibrain = GetArmyBrain(). Or self:GetBrain(). You’d atleasy partly solve the problem
> 
>     2. You have to write different code. While the code you wre usings comes from an enviroment with improved efficiency its not the faf enviroment and you have to accept the differences.
> 
>     3. You cannot repr the data. You van still log the data. Just have to be more careful. And know what to log for specifically.
> 
>     4. I’d try and put these improvements into Swarm first. And see what happens. And do logging alot of your basic improvements here can be do via the standard ai hooking. While you won’t be able to remove aibrain references. You’ll be able to test other things

1. If you look in BuilderManager
you'll see Self.Brain = Brain is defined which essentially defines any brain for all the managers and their data to the entire AIBrain
I commented this out and begun fixing a lot of stuff that caused major errors but most likely still invisible errors happening. 

2. I do not get what you mean, nothing here is bad and the faf environment thing is completely irrelevant mate

3. Fair, I have been able to do this in same areas but some areas a more nasty then some, a lot of these fixes come from data ive been able to pull and such especially the brain error trace-backs and such through intensive logging for hours :)

4. I do this anyhow and ye ur right cant test the aibrain references stuff.

**Comment by Dragun123** [comment]
1) Az, I know I saw the code. Beside a desire to repr. I absolutely no reason this is needed to be done. (Yes I know why it is done, its removing an extranous amount of logged data that is no longer needed). Which if we were in an enviroment that is designed for only one ai that work. 

I have worked extensively with the managers, not as much as Sprouto, but I already did several of the improvements you done so already. In my AI. I am tje one who pointed this out to you (albeit in context of fbm. But every manager does self.Brain = brains)).

2) The fact that fact has different design concerns tje enviroment this code you are deriving from. Means what you are doing is questionable logic. This means removing aibrain from everything might be just a no go. 

——————
Honeslty most important thing imho is builder types than any other optimizations.

**Comment by Garanas** [comment]
This PR is not part of the next release as it requires Uveso's approval.

**Review by Uveso — CHANGES_REQUESTED** [review]
Function overloads with `builderType` needs to be removed
(not used in the end)
Function overloads with `aibrain` needs to be removed
(we will get it with self.brain again)

Please make different commits for code cleaning and code changes next time.

From the code view it looks ok, but need testing after the rework.

(reviewed with Azrael in Discord)

**Comment by Garanas** [comment]
After discussing it with Azreal, I am closing this pull request due to it being aged. It can be re-opened in the future.

**Pull request closed without merging**
