### PR TITLE
Refactor trashbag management for units

### PR DESCRIPTION
**Pull request by Garanas**
There are a few 'legacy' trashbags used through the code. These legacy bags involve roughly the same operations of a regular trashbag, except they allocate a new table each time the code 'empties' the bag. As a result, memory is thrown out just to be re-allocated again.

### CODE REVIEW

**Comment by Garanas** [comment]
This branch consistently produces a hard crash using the following replay:

- [LastGame.zip](https://github.com/FAForever/fa/files/10434629/LastGame.zip)

I've tried doing this: https://github.com/FAForever/fa/issues/3493 , but I can't understand even the first few sentences. I don't know how to show the debugger interface, for example. Or what debugger it refers to.

It consistently produces this at minute 4:

```
Command line:
ForgedAlliance.exe /init "init_dev.lua" /EnableDiskWatch /showlog /log "dev.log" /debug /RunWithTheWind /nomovie /LogGC /logGC /loggc /sse2 /headtest

Exit code: 1
Engine ver.: 3720
Game tick: 2515

ACCESS_VIOLATION: Read from 0x00000000
Stacktrace: 0x0067AA5F 0x00A462E2 0x0044F81A 0x006BC54D 0x0040A8C5 0x0040A8C5 0x00556251 0x0052B240
.?AVUnit@Moho@@
MiniDump:
From 0x0067AA1F to 0x0067AA9F
CC558B6C2408578BBD7801000085FF741453E80AC0FFFF84C0740A5F896B04B0015DC204005F32C05DC20400CCCCCCCCCC83EC3C53568BF18B8E780100008BD8
8B018B40108D54242452FFD08B8E780100008B118B4208FFD085C00F8464010000F30F10542424F30F1040300F28CAF30F5CC8F30F58C2F30F10542428F30F11
```

@Hdt80bro do you understand how to analyse it? And if not, @KionX could you look into this? I'd be very grateful if the one that analysis it turns it into a video on how he / she analysis it. Maybe that helps me understand how I can tackle this in the future

**Comment by KionX** [comment]
The fafdevelop game reports: Unable to launch replay. What exe is being used? Is there a list of loaded dll files?

**Comment by Garanas** [comment]
I'll see if I can reproduce it.

**Comment by KionX** [comment]
something like this https://x64dbg.com/ ?
Yes.

**Pull request merged**
