### PR TITLE
Cybran beams

### PR DESCRIPTION
**Pull request by Crotalus**
With the changes of hitboxes and intel for beams we can restore the old beam effect of the PD and t2 tank, for nostalgic reason maybe?

### CODE REVIEW

**Comment by aeoncleanse** [comment]
We could...  I kinda prefer the pew-pew-pew...  :/

**Comment by speed2CZ** [comment]
Yes, those were superior to what we have now

**Comment by Zockyzock** [comment]
Would like to have them back, but i think there was another reason for them, @ppipp knows more about it

**Comment by Crotalus** [comment]
`release/3652`

**Pull request closed without merging**
