### PR TITLE
More refactoring

### PR DESCRIPTION
**Pull request by speed2CZ**
Changed
- :IsDead() to .Dead
- :GetArmy() to .Army
- :GetUnitId() to .UnitId
- optimized :GetBlueprint() calls
- optimized local imports
- Save BuildEffectBones for construction units for later use
- refactored Hives code

### CODE REVIEW

**Comment by speed2CZ** [comment]
I summon @Uveso for his review skills

**Comment by speed2CZ** [comment]
With the last commit, one thing I havent tested is if all mobile factories and engineering stations work as intended

**Comment by Uveso** [comment]
PM me or post here when you have tested it.
I will review it right after it :)

**Comment by speed2CZ** [comment]
@Uveso in my quick test everything worked as intended

**Pull request merged**
