### PR TITLE
Mass Storage able to be built around underwater mex

### PR DESCRIPTION
**Pull request by MrRowey**
- Auto Capping underwater Works
- Building works
- adjacently works

### CODE REVIEW

**Comment by Garanas** [comment]
Remove this if statement:

https://github.com/FAForever/fa/blob/memory/reduce-memory-of-intel-state/lua/SimCallbacks.lua#L212-L213

And it should work. Can you add it to this pr?

**Comment by Garanas** [comment]
And I suspect you want this to be part of the balance patch? If so, you should branch off `deploy/fafbeta` and then point to `deploy/fafbeta`

**Comment by MrRowey** [comment]
I'm not fussed about if it added as apart of balance update or game update. just wanted to make the pr so it get added at some point

**Review by Garanas — APPROVED** [review]
It has my approval - requires a voice from the balance team to merge

**Comment by Tagada14** [comment]
Yep, fine by me

**Pull request merged**
