### PR TITLE
Allow monkeylord to walk backwards

### PR DESCRIPTION
**Pull request by RabidPope**
Completely removes the possibility that the unit gets stuck after testing. Allows more accurate control of unit.

### CODE REVIEW

**Comment by RabidPope** [comment]
@Garanas Sorry I pilfered your code. ;p

**Comment by HUSSAR-mtrela** [comment]
why make 2nd Cybran unit to have wall backwards and not Aeon as well?

**Comment by Garanas** [comment]
@RabidPope please make a separate pull request for #5299

**Comment by RabidPope** [comment]
@Tagada14 Note that if you don't want it to be able to micro backwards(easily), the backwards distance can be set to 0. So it will still let it not get stuck, but making it very hard to make it walk backwards.

**Comment by Tagada14** [comment]
Please make the backwards distance 0 because we don't want to change how you micro the Monkey Lord.

**Comment by Garanas** [comment]
So how do I test and confirm that this works?

**Comment by RabidPope** [comment]
> So how do I test and confirm that this works?

What part do you plan on testing?

**Comment by Garanas** [comment]
How do I get a Monkey Lord stuck consistently, to see if this fixes it 😄

**Comment by RabidPope** [comment]
Find a place on a map with cliffs on live version where you can get it stuck reliably. Then try and do it with the changes. To find a place to test this, check for a indent in the cliff it cant turn around in.

**Comment by Garanas** [comment]
Thanks, I'll come back to you 👍

**Comment by RabidPope** [comment]
@Garanas So any thoughts?

**Comment by Garanas** [comment]
I did not manage to get it stuck 👍

**Pull request merged**
