### PR TITLE
minor hotbuild fixes

### PR DESCRIPTION
**Pull request by PhilipJFryFAF**
puts the energy storage in on the same list of buildings as power generators in the hotbuild unit group
saves you one additional hotkey to bind

### CODE REVIEW

**Comment by MrNukealizer** [comment]
I can see how that could be nice, but it also seems like it might confuse people into making energy storage instead of T1 pgens...

**Comment by TheKeyBlue** [comment]
I don't think that's a real concern, but I can't be sure.

I like it, Now I don't need to learn another key.

**Comment by PhilipJFryFAF** [comment]
i think it fits and since you have to cycle through to get to the storage it shouldn't cause too many issues if any

**Comment by PhilipJFryFAF** [comment]
the select next idle air scout function did select every single air scout instead of just the next

**Comment by PhilipJFryFAF** [comment]
changed scout to intelligence so that idle spy planes will be selected and not just scout planes

**Pull request merged**
