### PR TITLE
Mercy Adjustment

### LINKED ISSUE #4985: Balance idea: Mercy Rework
## Intended changes

```
- Lower damage
- High AOE
- Buff HP
```

## Thoughts on the changes

Based on [Deribus's suggestion](https://forum.faforever.com/topic/1834/ideas-for-mercy-changes/12?_=1685304186726) from a while ago, this changes the mercies role from a snipe unit to a low damage AOE unit. 

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

### PR DESCRIPTION
**Pull request by Spikey84**
Draft to close #4985. More documentation coming soon.

### CODE REVIEW

**Comment by MrRowey** [comment]
@Spikey84 I'll test this when I'm home from work 😄

**Comment by Garanas** [comment]
Please add videos for visual changes. It makes it easier to understand

https://github.com/FAForever/fa/assets/15778155/77aaad2e-8cef-4c2e-8c7e-b3f28673409f

**Comment by Azraeel** [comment]
wow thats actually cool asf, Jip is right add videos. It'll be great for Promo too!!!

**Comment by MrRowey** [comment]
This it could look better if it was similar to the salvation when it detonates is like 4 small projectiles to create the area

**Review by MrRowey — APPROVED** [review]

**Comment by Garanas** [comment]
I assume the fx are finalized in a different pull request, after testing the changes?

**Comment by Spikey84** [comment]
Yes, this is just a way to test stats, all subject to change and will be polished once we are sure we like it.

**Pull request merged**
