### PR TITLE
Improve campaign base manager expansions

### PR DESCRIPTION
**Pull request by speed2CZ**
One more value IncomingEngineers was needed in ExpansionBaseData of base
manager. It tracks engineers that are sent into expansion base.
If expansion base needs engineers is determined by number of engineers
working in expansion base manager + engineers that are on the way to
expansion.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Nice one @speed2CZ . Could you please re-write this a little to hook the lua rather than shadowing it, since you are only touching a small part of the file that you imported? Thanks.

**Comment by speed2CZ** [comment]
No, I dont know how, and it's just the beginning. There are more things to fix and improve with campaign AI.

**Comment by aeoncleanse** [comment]
OK I'll do it. I await future AI PRs :p

**Comment by speed2CZ** [comment]
so @aeoncleanse what's it gonna be?

**Comment by aeoncleanse** [comment]
2a99c9cf7b0afc6baffe1ab1a218c104e503e980

**Pull request closed without merging**
