### PR TITLE
Target bones - Seraphim Tech 3 / 4 Land 

### PR DESCRIPTION
**Pull request by Garanas**
image
_Old and new collision box_

image
_Target location_

Matches the collision box with the setup of the Siege Tank, where the treads are excluded. The height of the aim location is higher, as previously it was near the ground. It didn't have any target bones set, and the collision box was quite small.

### CODE REVIEW

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target location_

Removes a few target bones that were at the outer edges of the collision box, only the `Torso` remains as shown in the image. Slightly increases the collision box to make the support command unit easier to hit.

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target location_

The collision box is slightly lower and the unit uses the `Turret` bone as a target bone. The location of where units fire at is the same, but the siege tank can slightly easier prevent soaking up projectiles for other units.

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target location_

Slightly lowers the collision box to match the chassis, adds the `Torso` as a target bone

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target location_

Increases the height of the collision box to only encapsulate the top bit of the sniper. This should make the sniper more nimble, making it difficult for it to soak up damage from a siege tank behind it as an example.

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target location_

Increased the height slightly to make it easier for beam weapons to hit.

**Comment by Garanas** [comment]
image
_Old and new collision box_

image
_Target locations_

Adapts the Ythotha to have a similar structure as the Monkey Lord and Megalith do - where the bottom part of the experimental has no collision box.

**Comment by Garanas** [comment]
This pull request is ready for a review, merging it toggles the task Tech 3 / 4 Land units for the Seraphim faction of https://github.com/FAForever/fa/issues/4067

**Comment by speed2CZ** [comment]
If Yotha collision box is not to the ground, will fire beetles be able to hit it?

**Comment by Garanas** [comment]
They appear to hit just fine 👍

**Pull request merged**
