### PR TITLE
Add lobby option for player chat color

### PR DESCRIPTION
**Pull request by Crotalus**
Make the gay pride colors optional 🏳️‍🌈

### CODE REVIEW

**Comment by shalkya** [comment]
image
Should we also add an option (or use the same option) to revert the bold username ?
Could we make color "on" by default, and then people will turn it off if they don't like

**Comment by aeoncleanse** [comment]
Great PR @Crotalus. I agree with shalkya, please include the bold-ness in the toggle, and default it to "On". Then we'll merge it in :)

**Comment by Rackover** [comment]
The color + boldness should be default on because most users benefit from it. 
Also may you fix the faction color being overriden by the chat rewrite aswell please ? When the player colored names are disabled the faction color should technically take over. (Or else, be sure to make the chat white, not grey). Otherwise yeah it's really cool thanks for handling this

**Comment by shalkya** [comment]
another PR has been set up to improve this one.

**Pull request closed without merging**
