### PR TITLE
Rationalize and buff the stats of all Cybran Shield Generators

### PR DESCRIPTION
**Pull request by Basilisk3**
### Explanation of the changes
I was going through the blueprints of these units and noticed how all over the place their stats are. Especially their mass/energy consumption figures are very unintuitive. This PR aims to remedy this, and make their behaviour easier to learn. If you are looking for an example, the ED2 will no longer use 7.6 mass/s when upgrading to the ED3. Additionally, all buildpower figures are now dividable by 5, the buildpower of a Tech 1 engineer. No more 29.3 buildpower, like with the ED3.

While doing this, I also threw in a buff for the three mid/late game shields. It is widely accepted, that the ED3, ED4 and ED5 are extremely bad, while the ED1 and ED2 are good/fine. These changes make them more competitive/usable, while still keeping them considerably worse than the shields of the other factions, as to not break faction diversity.

### Stat Changes

 **ED1**
BuildRate: 19.2 --> 20

 **ED2**
BuildCostMass: 460 --> 440
BuildRate: 21 --> 20
BuildTime: 775 --> 800

**ED3**
BuildCostMass: 1260 --> 1140
BuildRate: 29.3 --> 30
BuildTime: 2200 --> 2000

**ED4**
BuildCostEnergy: 41000 --> 39000
BuildCostMass: 2460 --> 2240
BuildRate: 50.7 --> 50
BuildTime: 3515 --> 3300

**ED5**
BuildCostEnergy: 67666 --> 63000
BuildCostMass: 4260 --> 3920
BuildTime: 7100 --> 6000

### CODE REVIEW

**Comment by MrRowey** [comment]
The Balance Team is currently discussing this and currently doesn't see a need for the changes.

**Comment by Basilisk3** [comment]
I reduced the buffs considerably, could this get another review?

**Comment by MrRowey** [comment]
> I reduced the buffs considerably, could this get another review?

this is currently being discussed

**Comment by MrRowey** [comment]
Awaiting Team Approval

- [ ] Team Approval

**Comment by MrRowey** [comment]
Closing this PR as the team is not sure what direction to take the changes for all the shield in at this moment in time.

**Pull request closed without merging**
