### PR TITLE
Hotfix for firebeetles

### PR DESCRIPTION
**Pull request by aeoncleanse**
Further simplified the way beetles work and walked through it from the start.

### CODE REVIEW

**Comment by ChrisKitching** [comment]
In what sense is this a "hotfix"? What problem is it fixing? Do you even know what this word means? :P

**Comment by aeoncleanse** [comment]
Hehe. It's a hotfix because when pip and I were talking, he mentioned beetles and hotfixing in the same sentence. The problem it's fixing is stupid complexity allowing it to blow at the wrong times in some situations, which is why we had to revert.

Whatever :8ball:

**Comment by duk3luk3** [comment]
Why is this closed? Was it merged?

**Comment by aeoncleanse** [comment]
Crotalus reworked it

**Comment by irswat** [comment]
fire beetles were working correctly before the last update if I recall correctly. With the faf beta that is up now the firebeetles do not explode at all. The detonate button pauses them and attack they just surround the unit and sit there.

**Pull request closed without merging**
