### PR TITLE
Wait on full score / stats to sync before EndGame

### LINKED ISSUE #1612: JsonStats not properly reported
In pretty much all 4-5 games I recently played, the game never reported JsonStats. Those were all 4x4 games that took quite a while - so a lot of stats have to be sent.

My preliminary assumption is that either the string gets too big and the game somehow silently drops it, or that it's connected with "After-game graphs not displayed".

A healthy game looks like this:

```
INFO: creating high fidelity terrain
INFO: creating high fidelity water
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000victory 10
INFO: Sending stats: {"stats":[{"blueprints":{"ual0001":{"built":1,"lowest_health":11000},"uab5101":{"built":8},"uab1103":{"built":1}},"type":"Human","general":{"score":77,"currentcap":{"count":1000},"lastReclaimedMass":0,"mass":703.69287109375,"built":{"mass":52,"count":10,"energy":440},"kills":{"mass":0,"count":0,"energy":0},"lost":{"mass":0,"count":0,"energy":0},"currentunits":{"count":3.8000001907349},"energy":4696,"lastReclaimedEnergy":0},"faction":2,"resources":{"massin":{"total":703.69287109375,"rate":0.30000001192093},"energyout":{"total":993.60107421875,"rate":6.1999998092651},"energyin":{"total":4696,"rate":2},"energyover":308,"massover":9.8975830078125,"massout":{"total":105.79981231689,"rate":0.60000002384186}},"name":"Downlord","units":{"air":{"lost":0,"kills":0,"built":0},"tech3":{"lost":0,"kills":0,"built":0},"cdr":{"lost":0,"kills":0,"built":1},"tech2":{"lost":0,"kills":0,"built":0},"tech1":{"lost":0,"kills":0,"built":9},"transportation":{"lost":0,"kills":0,"built":0},"land":{"lost":0,"kills":0,"built":1},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":0,"kills":0,"built":9},"engineer":{"lost":0,"kills":0,"built":1},"naval":{"lost":0,"kills":0,"built":0},"experimental":{"lost":0,"kills":0,"built":0}}},{"blueprints":{"uel0001":{"lost":1,"built":1,"lowest_health":9500}},"type":"Human","general":{"score":85,"currentcap":{"count":1000},"lastReclaimedMass":0,"mass":671.09484863281,"built":{"mass":0,"count":1,"energy":0},"kills":{"mass":0,"count":0,"energy":0},"lost":{"mass":18000,"count":1,"energy":5000000},"currentunits":{"count":1},"energy":4422,"lastReclaimedEnergy":0},"faction":1,"resources":{"massin":{"total":671.09484863281,"rate":0},"energyout":{"total":1043,"rate":0},"energyin":{"total":4422,"rate":0},"energyover":3379,"massover":551.89666748047,"massout":{"total":119.20016479492,"rate":0}},"name":"Brutus5000","units":{"air":{"lost":0,"kills":0,"built":0},"tech3":{"lost":0,"kills":0,"built":0},"cdr":{"lost":1,"kills":0,"built":1},"tech2":{"lost":0,"kills":0,"built":0},"tech1":{"lost":0,"kills":0,"built":0},"transportation":{"lost":0,"kills":0,"built":0},"land":{"lost":1,"kills":0,"built":1},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":0,"kills":0,"built":0},"engineer":{"lost":1,"kills":0,"built":1},"naval":{"lost":0,"kills":0,"built":0},"experimental":{"lost":0,"kills":0,"built":0}}}]}
INFO: called Set_graph...
```

A broken game looks like so:
```
INFO: creating high fidelity terrain
INFO: creating high fidelity water
INFO: Hooked /lua/ui/game/scoreaccum.lua with /mods/supremeeconomy/hook/lua/ui/game/scoreaccum.lua
INFO: Hooked /lua/defaultantiprojectile.lua with /schook/lua/defaultantiprojectile.lua
INFO: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 1
INFO: GAMERESULT : \000defeat -10
WARNING: ACU kill detected. Rating for ranked games is now enforced.
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 1
INFO: GAMERESULT : \000score 2
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
WARNING: ACU kill detected. Rating for ranked games is now enforced.
INFO: GAMERESULT : \000score 3
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000defeat -10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: GAMERESULT : \000victory 10
INFO: called Set_graph...
```
Good thing is, it's reproducible when watching the replay.

### LINKED ISSUE #1616: "No data available" in score graph
Sometimes after games, the score graph shows "No data available".

This is because a full score sync takes place on game end. However if the timing is bad, the sim stops before the scores were synced -> empty scoreboard.

Related to #304

### PR DESCRIPTION
**Pull request by Crotalus**
Fixes #1616

### CODE REVIEW

**Comment by micheljung** [comment]
Crotalus, I updated your comment. This PR fixes #304 (thanks!) and a part of #1612. but since the stats should also be sent after someone died and not only on game end, I'll create a separate PR.

**Comment by Crotalus** [comment]
I think #304 is more about the case when you die in a game before it's over and not allowed to see score yet (to prevent giving "intel-numbersl" about enemy eco etc). 

So button should be renamed to "Exit" instead of "Score" if score isn't available.

**Comment by micheljung** [comment]
Hm right, should we create a separate issue?

**Comment by micheljung** [comment]
I created #1616 
And updated your comment again :P I wanna see if it automatically closes the issue when we merge it (this works from commit messages, please use that, that way the issue is also referenced in the commit)

**Comment by aeoncleanse** [comment]
Merging into release/3660

**Pull request closed without merging**
