### PR TITLE
platoon.lua annotation and warning fixes [lua/AI/aiutilities.lua]

### PR DESCRIPTION
**Pull request by clyfordv**
Annotation and warning fixes for platoon.lua

files:
aiutilities.lua

focus:
- annotation additions and fixes
- convert `$type|boolean` return values to `$type|nil`
- optional params

### CODE REVIEW

**Comment by relent0r** [comment]
What do the question marks mean in the annotations there @clyfordv?

**Comment by clyfordv** [comment]
Optional parameters. Most of those marked as optional here are done so implicitly (read as: I found another piece of code somewhere that calls it with a bunch of `nil` values).

**Comment by relent0r** [comment]
> Optional parameters. Most of those marked as optional here are done so implicitly (read as: I found another piece of code somewhere that calls it with a bunch of `nil` values).

Ah cheers. I'll take a look at this PR once I get home from work.

**Comment by clyfordv** [comment]
Appreciate it. Happy to take any more questions or feedback, stylistic or mechanical.

**Review by relent0r — APPROVED** [review]
No issues with this PR.
Similar to the other, we just need a snippet added.

It would be
/changelog/snippets/ai.6085.md
With just an entry of something like say
`- (#6085)  annotations of aiutilities.lua and logic fixes`

**Pull request merged**
