### PR TITLE
Annotate `AddBlinkyBox`

### PR DESCRIPTION
**Pull request by lL1l1**
## Description of the proposed changes

Annotate `AddBlinkyBox`, now we know what it does!

## Testing done on the proposed changes

https://github.com/user-attachments/assets/db36d2e2-657d-4425-979e-a17562054c26

## Checklist
- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Review by Hdt80bro — APPROVED** [review]

**Review by Garanas — APPROVED** [review]

**Comment by 4z0t** [comment]
I wonder how it can be used 🤔

**Comment by Garanas** [comment]
Maybe we can use it to highlight (relevant) units that receive damage. There is a callback for that in `gamemain.lua` if I am not mistaken.

**Comment by 4z0t** [comment]
Yeah, there is one.

**Comment by lL1l1** [comment]
I think it could've been used to highlight units in the tutorial, it's a typical "click me!" type of thing across games.

**Pull request merged**
