### PR TITLE
Integrate wonky structures

### PR DESCRIPTION
**Pull request by Garanas**
See also: https://github.com/FAForever/fa/pull/4507

When a structure is build it no longer generates a flat plane but a gradient between terrain heights at the outer tips of the build skirt. The structure is then slightly rotated to match the orientation of the terrain. This applies to all structure. On top of that Extractors and Hydrocarbon plants can now always be built.

With thanks to Balthazar for the Wonky Structures mod and the gradient terrain 'flattening'.

Various examples that would previously deform the terrain to the point where it seriously impacts gameplay:

image

image

image

### CODE REVIEW

**Comment by Garanas** [comment]
image

**Comment by Garanas** [comment]
image

image

**Comment by Garanas** [comment]
New behavior: 

image

image

image

Old behavior:

image

image

image

**Comment by Garanas** [comment]
image

**Comment by Marc-Spector** [comment]
Cool! Great work, Jip and Balthazar!

**Pull request merged**
