### PR TITLE
Remove stray png

### PR DESCRIPTION
**Pull request by ChrisKitching**
Well spotted, @Xinnony!

... And this is why we don't do `git add .` :P

### CODE REVIEW

**Comment by Xinnony** [comment]
np
But why you convert the PNG to DDS if you edit with PNG format ???

**Comment by ChrisKitching** [comment]
DDS loads much faster. The lobby comes up about 1s faster after the conversion.

These files though, these belong to GPG. I just converted one to view it and forgot to put it in /tmp. Time for a shell script!

**Comment by Xinnony** [comment]
Can you prove it ?
If that's true, well played !

**Comment by ChrisKitching** [comment]
Yes. IceDreamer and I conducted benchmarks.

I did actually tell you this on the forums, and at the time, but you seemed too busy shouting at me to actually listen to what I said :/

**Comment by Xinnony** [comment]
I'm not sure

http://forums.faforever.com/forums//viewtopic.php?f=45&t=9140&sid=a8f0f82efedec0cfbfa263bf90f38949&start=10#p90203

**Comment by ChrisKitching** [comment]
@Xinnony Ze_Pilot has not measured it. I told him how to measure it, he continues to claim it cannot possibly be faster.

Until he can be bothered to qualify his statements with facts, it seems futile to continue to try and talk to him.

Do you really think I did it for no reason? That Sheeo would approve changing 223 images for no apparent gain? That'd be ridiculous.

**Comment by Xinnony** [comment]
Because he love you probably, i don't know.

In short, no evidence.

**Comment by visionik** [comment]
Why can't we all just get along? ;-)

**Comment by visionik** [comment]
happy happy patch day.

**Pull request closed without merging**
