### PR TITLE
Revert "UEF ACU: Revert the option to have the teleporter and nuke upgrades simultaneously"

### PR DESCRIPTION
**Pull request by lL1l1**
Reverts FAForever/fa#5783
Now that the Billy is fixed and rebalanced for teleport, this can be reverted.

### CODE REVIEW

**Comment by MrRowey** [comment]
@Garanas This was something the balance team decided on that they wanted at the time

**Review by MrRowey — APPROVED** [review]

**Comment by Garanas** [comment]
@MrRowey and I think it is a really bad idea 😃

**Comment by MrRowey** [comment]
Let's Leave it on develop for now and with the issues being fixed see how it goes it it still completely a bad thing then we can revert it.

**Comment by Garanas** [comment]
@MrRowey it will now be part of the hotfix 😃 , to fix an issue with the Billy ironically.

**Pull request merged**
