### PR TITLE
Disable area reclaim command

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Disables the area reclaim command. Area ground attack command is polished in https://github.com/FAForever/fa/pull/6317

### CODE REVIEW

**Comment by lL1l1** [comment]
Area attack has a consensus that it's a beneficial feature for both strategic depth and aesthetics, and it should be added.

**Comment by Tagada14** [comment]
I would leave the area attack as well. I haven't seen any pushback against that change.
Could also revert the reclaim rate changes in this PR or should I make a separate PR for that?

**Comment by Garanas** [comment]
@lL1l1 / @Tagada14 processed the feedback

**Comment by Tagada14** [comment]
@Garanas  AFAIK it was decided to not release the Pulsar this patch either, are we moving that to a separate PR?

**Comment by lL1l1** [comment]
@tagada14 Here's the reasoning to not release Pulsar: [Discord](https://discord.com/channels/197033481883222026/1248621733112578109/1255075225998196816)
Otherwise it's ready to go. The textures are the highest priority (Progress: https://github.com/FAForever/fa/pull/6319). Shield effects would be nice to have. Further balance feedback seems unlikely because of how rare FAF develop games are, combined with the useful situations for it being uncommon.

**Pull request merged**
