### PR TITLE
Change Sera Snipe-Mode Icon

### PR DESCRIPTION
**Pull request by Spikey84**
Snipe mode off: off

Snipe mode on: off

### CODE REVIEW

**Comment by MrRowey** [comment]
Nicely Done !

**Comment by Spikey84** [comment]
@MrRowey thanks for the help :)

**Comment by MrRowey** [comment]
Dose the tooltip when you hover still work / have the correct information ?

**Comment by Spikey84** [comment]
@MrRowey yes, all that was changed was the look of the button

**Pull request merged**
