### PR TITLE
Allow users to once again view the unit restrictions.

### PR DESCRIPTION
**Pull request by ChrisKitching**
Simple fix to get the old behaviour back.

### CODE REVIEW

**Comment by ChrisKitching** [comment]
Shame this missed the hotfix: it's a bit of a gamebreak :/

**Comment by Xinnony** [comment]
Already added in : https://github.com/FAForever/fa/pull/339

**Comment by ChrisKitching** [comment]
That's right, but 339 is a bit of a tangled mess at this point, so I had a go at extracting the more immediately-mergeable parts of it.
In this case, since the work in 339 doesn't produce the same behaviour as was present before the regression, this warranted a fresh commit, not just a cherry-pick.
We can discuss your proposed new behaviour over in 339, or elsewhere. This PR provides a direct "un-regress" option with no additional baggage or complication.

Apologies if my comments on your PR don't make it clear how I got to this point.

**Comment by Xinnony** [comment]
My PR is widely clearer than yours.

Exemple here :
https://github.com/ChrisKitching/fa/commit/49f0d460c197cdd6e4e1eff150771300ea8b5b51#diff-1898ae6dfa782099d74a2bc0b76f078aL4772
line 4772 > 4783

It was much clearer before your change.

**Comment by Sheeo** [comment]
@Xinnony pull requests like these are preferred, since I can fire up FA and test this change individually, then merge it straight away and feel confident we do not have regressions -- I too, was working on pulling out parts of #339 for individual review before my exams hit.

I think with the comment in place, this is a good addition. I do think we should attempt to avoid the somewhat obtuse expression to determine visibility. Perhaps we could have two different buttons?

**Comment by Sheeo** [comment]
@ChrisKitching please follow the conventions specified [here](https://github.com/FAForever/fa#contributing)

**Pull request closed without merging**
