### PR TITLE
Add dummy drone to skipped categories and add lobby option to unrank game

### LINKED ISSUE #3405: Game did not give units to mates on full-share acu death
I died in a full-share game and my units were not given to my mates instead they stayed with me  and I could not controll them. Errors in log.
Deatch must have been arround that time:
```
debug: Current gametime: 00:26:30
debug: Loading module '\000/units/xsa0304/xsa0304_script.lua\000'
warning: ACU kill detected. Rating for ranked games is now enforced.
info: Sending game result: 8 score 1
info: GAMERESULT : \000score 1
info: CWldSession::DoBeat() unknown entity id (0x2ff000cf) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0051f) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00d05) supplied in a pose update.
debug: Current gametime: 00:27:00
debug: Loading module '\000/units/zxa0001/zxa0001_script.lua\000'
warning: Unit.OnStopBeingBuilt() Army 3 cannot create restricted unit: Dummy Drone
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\simutils.lua(415): Game object has been destroyed
         stack traceback:
         	[C]: in function `SetBuildRate'
         	...gramdata\faforever\gamedata\lua.nx2\lua\simutils.lua(415): in function <...gramdata\faforever\gamedata\lua.nx2\lua\simutils.lua:335>
         	...ogramdata\faforever\gamedata\lua.nx2\lua\aibrain.lua(543): in function <...ogramdata\faforever\gamedata\lua.nx2\lua\aibrain.lua:535>
         	...ogramdata\faforever\gamedata\lua.nx2\lua\aibrain.lua(560): in function `TransferUnitsToHighestBrain'
         	...ogramdata\faforever\gamedata\lua.nx2\lua\aibrain.lua(642): in function <...ogramdata\faforever\gamedata\lua.nx2\lua\aibrain.lua:497>
debug: Loading module '\000/units/uab4201/uab4201_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff00156) supplied in a pose update.
```
... then game crashed
[game_15273612.log](https://github.com/FAForever/fa/files/7124410/game_15273612.log)
No local replay was recorded for unknown reasons

### LINKED ISSUE #3435: Remove dummy drone from restrictions list
image

The dummy drone used to gift unfinished structures (when someone dies) is part of the restrictions list. It should be removed as people interpret it as an easy approach to unrank games. This causes the gift script when someone dies to crash.

The dummy drone should be excluded from the overview.

Maybe we can add in a game option that states ranked / unranked, that defaults to ranked instead? It feels a bit too much to require people to add a restriction to unrank a game.

### PR DESCRIPTION
**Pull request by Garanas**
Closes #3435 and closes #3405

What should we do instead to make it easier / intuitive to unrank a game? I could make an additional lobby option specifically for it, as described in the issue?

### CODE REVIEW

**Comment by Tagada14** [comment]
Yeah, would be nice to have something else to unrank games for sure.

**Comment by Garanas** [comment]
@Sheikah45 how does the client determine a game is not ranked? Would adding an option that isn't on its default value trigger it?

**Comment by Sheikah45** [comment]
The client doesn't determine ranked games. The server does. It has a set of options it checks. @Askaholic can probably be more specific.

**Comment by Sheikah45** [comment]
Could also just create an actual dummy unit

**Comment by Askaholic** [comment]
Or maybe just make it a game option

**Comment by Garanas** [comment]
Yeah - that feels more intuitive. I'll add the option to this PR tomorrow.

**Comment by Askaholic** [comment]
Ok we’ll have to make an issue on the lobby server for it too otherwise I’m gonna forget.

**Comment by Askaholic** [comment]
Server PR is merged

**Pull request merged**
