### PR TITLE
Set ground fire as default for mobile units

### PR DESCRIPTION
**Pull request by Crotalus**
We could make this a gameplay option also per player basis. What's needed then is a SimCallback which provide the default firestate at start of game / whenever player changes that option.

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Errr. Why do we want this?

**Comment by JaggedAppliance** [comment]
Ground-fire is more useful, units act the same way as with return fire but you can more quickly and easily give ground-fire commands without having to change fire-state. Also the hotkey for changing fire-state is laggy.

**Comment by speed2CZ** [comment]
Also the myth about ASFs performing better if set to groud fire

**Comment by JaggedAppliance** [comment]
I guess you would be setting all factories to ground-fire rather than the actual units right?

**Comment by Exotic-Retard** [comment]
theres a nice ui mod im using that already does this, just do what it does.
i think its called uiparty.
factories are nice and all but if you get units gifted to you, ect it doesnt work. it needs to be on select like in the ui mod, so you can be sure its consistent.

**Comment by Crotalus** [comment]
As mentioned, with factories you would miss given units and also experimentals.

Yeah, it's possible to do with UI mods works but is not really optimal. I don't know how UI-party works but if it always set ground fire on selected units it will spam the sim / replay with SetCommandPair commands every time a user select unit(s). If it only does it if not already set it's not as bad I guess.

**Comment by snufflesAU** [comment]
Would be nice to have the option to enable or disable this, in the Interface preferences. Possible?

**Pull request merged**
