### PR TITLE
Comment out Lobby Presets Button 

### PR DESCRIPTION
**Pull request by MrRowey**
@Garanas this one seems hard to test on FAF Dev Setup as Presets don't show up there seems to be faf specific.

### CODE REVIEW

**Comment by KionX** [comment]
You can comment everything out --[[ ]]

**Comment by Garanas** [comment]
To me it feels better to just hide the button for now:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/lobby.lua#L3478
 
 By commenting that elseif. If suddenly people were using it we can easily get it back and / or if nobody was using it we remove the legacy code for patch 3727.

**Comment by MrRowey** [comment]
> 
> 
> You can comment everything out --[[ ]]

I wondered if there was an easy way to do that just using the Comment out code shortcut in VS Code

**Comment by MrRowey** [comment]
Okay something in the part i commented out Prevent game from launching when lunch button is clicked need to investigate further

**Pull request merged**
