### PR TITLE
Nomadicons

### PR DESCRIPTION
**Pull request by Dragun123**
This branch is for bugfixes, general improvements, and new features. If your change is designed to alter balance, please make 
sure your changes are rebased onto [development/balance] (https://github.com/FAForever/fa/tree/development/balance), and target that branch with your PR.

### CODE REVIEW

**Comment by shalkya** [comment]
At first, I thought this would be not required anymore with the fix of the init upload. But thinking back on it, since we won't have to redownload everything (especially what is unchanged) in the next patch (this is a fix that will come alongside with the init upload). So user will need to download that once, and those icon can become very handy for modders.

**Comment by KionX** [comment]
``
we won't have to redownload everything (especially what is unchanged) in the next patch
``
I assume this applies to featured mods as well. In this case, this PR is not needed.

**Comment by Dragun123** [comment]
If a featured mod has unique strategic icons they are not avaliable in FAF Vanilla game mode.

**Comment by KionX** [comment]
init file don't solve this problem?

**Comment by shalkya** [comment]
@KionX will init fix, allow modders to include dds into their mods now. They weren't able to do that before.
But i guess we can add dds that are commonly used by modders, since as I said, players would need to download them only once. I guess the question is to know how much modders need that.

**Comment by Uveso** [comment]
@Dragun123 

please write a propper comment to your PR next time. Thanks !

Since this problem can be solved with the ini.lua file i am closing this.

**Pull request closed without merging**
