### PR TITLE
 FAF UI Framework

### PR DESCRIPTION
**Pull request by 4z0t**
- Set class
- Static Scrollable class
- Dynamic Scrollable class

### CODE REVIEW

**Comment by Garanas** [comment]
@4z0t shall I merge this in?

**Comment by 4z0t** [comment]
@Garanas I'm working here [UMT](https://github.com/4z0t/FAF-UI-Mods/tree/dev/UMT/mods/UMT/modules/Containers), if you are ok with current ones, I'll PR later then an another one.

**Comment by Garanas** [comment]
Would you be okay if I change the name to something less cryptic? `FAFUIF` isn't exactly inviting, how about `ui-framework`

**Comment by 4z0t** [comment]
I would say `UI-Framework` :D

**Comment by 4z0t** [comment]
@Garanas Done! Now you can merge :)

**Review by Garanas — APPROVED** [review]

**Pull request merged**
