### PR TITLE
Faction specific SACU explosions

### PR DESCRIPTION
**Pull request by Garanas**
Introduces faction unique SACU explosions that are similar to the ACU explosions, but smaller. All of the work is done by Marlo.

Todo:
 - [ ] Rename some of the files to have a better naming convention
 - [ ] Scale down some of the SACU explosions

### CODE REVIEW

**Comment by MrRowey** [comment]
@Garanas where do i changes the explosions sizes ?

**Comment by Garanas** [comment]
I missed the notification!

The logic of the explosions are defined in the projectile script:
- effects/Entities/SCUDeathAeon/SCUDeathAeon_script.lua
- effects/Entities/SCUDeathCybran/SCUCybranDeath_script.lua
- effects/Entities/SCUDeathSeraphim/SCUSeraphimDeath_script.lua
- effects/Entities/SCUDeathUEF/SCUUefDeath_script.lua

You can scale the effects independently using their [interface](https://github.com/FAForever/fa/blob/deploy/fafdevelop/engine/Sim/IEffect.lua), which is quite extensively annotated. All light emitters have a radius parameter. Other values you can tweak in the blueprints, if necessary

**Comment by Garanas** [comment]
Great feature in my opinion - feel free to request to open this pull request again if you (the reader) feels like picking it up.

**Comment by BlackYps** [comment]
Is anyone ever going to find this again when it is closed?

**Comment by MrRowey** [comment]
Could Just make it an Issue and link to this pr

**Pull request closed without merging**
