### PR TITLE
Remove rocking behavior calls

### PR DESCRIPTION
**Pull request by Garanas**
All calls to starting / stopping the rocking behavior are removed. If you're wondering what it is - it wasn't used in practice. It requires blueprint values set that aren't set by any blueprint, both of the base game files (including those that are not part of the repository) and common mods. 

Removing the call on its own is good - but preventing _a lot_ of threads from being made is better. To give an idea, each time StartRocking is called a thread is made. Each time StopRocking is called, if a thread was made, a new thread is made to stop the previous one. In a game of 4 AIx fighting these functions were called 2030 times to start rocking and introduce a thread and 2580 times to kill the start thread and start a new thread to stop rocking. This was over a timespan of 13 minutes, which means (2030 + 2580) / 780 = 5.9 threads a second. If you take into account that almost no thread spawns the first 5 minutes because there are no units on the water then we get (2030 + 2580) / 480 = 9.6 threads a second. That is almost one thread a tick, for just four AIs in a game that is 13 minutes long.

And all of that - for nothing!

There is one mod that calls the rocking behaviors: Jaggeds_Infrastructure_Pack. I suspect it is because the original files (where the author looked at) made similar calls. There are no mods that define the right values in their blueprint files, hence there would be no actual rocking even though a call was made.

I've looked at the following mods, highlighted some that I think are important:
#2x Resources,Storage,BuildRate,BuildRange
**#Marlos mods compilation**
additionalCameraStuff
Advanced target priorities
AdvancedShieldsV4Fixed
AI-Swarm
AI-Uveso
AllFactionsFixed
AllFactions_FAF_BO_Nomads
All_Faction_Quantum_Gate
Big boom
**BlackOpsFAF-ACUs
BlackOpsFAF-EXUnits
BlackOpsFAF-Unleashed
BrewLAN
BrewLAN_Units**
CinematicsMod
Commanders_x4 BlackOps
Compat_GilbotCore+BlackOpsACU
Cybran UnBalanced
dear-windowing
DilliDalli
Hard FFA (ACUS spawn in T2 transport in center)
Improved Close-up Camera
Jaggeds_Infrastructure_Pack
kazbek-replay-ui
Low Commander Upgrades Costs Tweaked
Low Commander Upgrades Costs Tweaked 2
Music_PhilCrofts
No Friendly Fire
NuclearRepulsorShields
Oof
Personal Phantomz Blackops Balance Patch
PxModAlphaV6
rks_explosions
RNGAI
SACUAI
simspeed++
Sorian Edit
StorageRich_x10Fixed
SupremeScoreBoard
T1 UNIT HEALTH X2
Unholy Alliance - BlackOps ACUs
x2 Build Range

### CODE REVIEW

**Comment by KionX** [comment]
Maybe should add the default settings instead of deleting rocking?

**Comment by Garanas** [comment]
What would the default settings be?

**Comment by KionX** [comment]
For example, like this:
bp.Display.MaxRockSpeed = 4

**Comment by speed2CZ** [comment]
There actually is a default value (1.5), it's just on a wrong line
https://github.com/FAForever/fa/blob/6da131f33004f5f447eb398234770d63e4ac4023/lua/sim/Unit.lua#L4248-L4249

**Comment by Garanas** [comment]
I don't understand - why do we want to introduce something that has never run (not even in the steam version)?

**Comment by speed2CZ** [comment]
Well it's an option, small detail. We dont know why it was removed (if it ever was a thing). I know it grinds your gears since it goes against everything you're doing here now :D
Anyway if someone decides to enable it, without adding the values into the bps.
At least this line would have to change https://github.com/FAForever/fa/blob/6da131f33004f5f447eb398234770d63e4ac4023/lua/sim/Unit.lua#L4258
to
```LUA
self.RockManip:SetTargetSpeed(- (bp.MaxRockSpeed or 1.5)) 
```
But saving the value direcly in the unit would be better.

**Comment by Garanas** [comment]
I've changed the code slightly so that if it does gets called, at least the threads are not made _before_ the checks whether it makes sense to make them. Made a small benchmark and creating threads is expensive. With that said - I'm not adding in the calls that do the rocking. It is not used by the game and it is not used by any of the common mods. I do not see why we need it, or need to re-establish them as a whole.

image

**Comment by Garanas** [comment]
I'm going to merge this next Monday morning unless someone has an objection to that.

**Comment by Garanas** [comment]
Received no further objection - merging.

We could look at this again in the future if we have spare ms / tick to spent at something.

**Pull request merged**
