### PR TITLE
Fix depth charges not applying the `ProjectilesToDeflect` blueprint field

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Fix an issue where the blueprint field `ProjectilesToDeflect` of a depth charge was ignored. It would always default to the value `3`.

## Testing done on the proposed changes

In the following test case I increased the redirect count of the depth charge of the UEF Destroyer to 10.

https://github.com/user-attachments/assets/68fa6e63-9c84-4a6e-a36b-d62aae46c0dd

## Checklist

- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Review by lL1l1 — COMMENTED** [review]
"Depth charge" is confusing with the depth charge weapon. I think we should use "Anti-Torpedo Flare" because that makes sense when you know about Aeon tactical missile flares, and the name is already used by the Mermaid, Brick, Megalith, and Barracuda. UEF's display name is "Smart Charge AntiTorpedo" and Salem is an outlier with "Anti Torpedo Solution".

**Comment by lL1l1** [comment]
You have to respawn the units for the changes to take effect since this mechanic uses the weapon's blueprint, and blueprints are cached on instantiation (`self.Blueprint`), so you have to respawn the unit and its weapon for it to update.
You may also find useful the hotkey "toggle collision debug information" (equal to `dbg c` console command) to see how the projectiles hits the flare's hitbox, and increasing the projectile lifetime in the antitorp weapon's blueprint so that it can catch more torpedoes.
{6E383769-F0F7-4ED6-925C-A448CD7117EC}

**Review by Tagada14 — APPROVED** [review]

**Comment by Garanas** [comment]
> "Depth charge" is confusing with the depth charge weapon. I think we should use "Anti-Torpedo Flare" because that makes sense when you know about Aeon tactical missile flares, and the name is already used by the Mermaid, Brick, Megalith, and Barracuda. UEF's display name is "Smart Charge AntiTorpedo" and Salem is an outlier with "Anti Torpedo Solution".

I agree, but we should process that in a separate pull request. It's also a little tricky because if we change the names (of the Lua classes) then we'll also break mod compatibility.

**Comment by BlackYps** [comment]
When it's just about the class name then I suggest to just add a comment to explain what the class is actually about. This way we don't break any mods

**Comment by lL1l1** [comment]
I meant it in the context of the changelog snippet, but BlackYps makes a good suggestion as well.

**Pull request merged**
