### PR TITLE
Reclaim

### PR DESCRIPTION
**Pull request by 4z0t**
Just a concept: after projecting labels we check if they are in same square of size *LabelRes*, but it requires some improvements, because labels in adjacent squares may merge and divide while moving camera in XOZ plane.
(sorry for other 44 commits, idk how to deal with those)

### CODE REVIEW

**Comment by MrRowey** [comment]
Is this just not the same as what jip was already doing on #3534 ?

**Comment by Garanas** [comment]
Not entirely - he's not further ahead. This solves the merging of labels and I can include that. It doesn't solve the performance issues underneath - I am fixing those with my PR.

**Comment by 4z0t** [comment]
Yeah, sure. But as i said, it is a little raw

**Comment by Garanas** [comment]
For some reason this branch is difficult to rebase. I don't understand why - could anyone help me out?

**Comment by Crotalus** [comment]
Seems to be 2 commits which shouldn't be in this branch.

Assuming you want to rebase to deploy/fafdevelop:

Alternative 1, rebase and remove 2 commits:
```
<checkout this Reclaim branch>
git rebase -i deploy/fafdevelop
change "pick" to "d" for the first two commits, they shouldn't be in this branch
let the third commit stay as "pick"
save/close editor

```
Alternative 2, cherry pick the commit to fresh branch:
```
git checkout deploy/fafdevelop
git checkout -b reclaim-new
git cherry-pick 28f4cd2
```

**Comment by Garanas** [comment]
Closing in favor of what we'll be brewing in https://github.com/FAForever/fa/issues/4085

**Pull request closed without merging**
