### PR TITLE
Connectivity screen now updates with thread

### PR DESCRIPTION
**Pull request by Crotalus**
This makes it possible to see ping while game paused / someone times out.

Also some usual cleanup

### CODE REVIEW

**Comment by Crotalus** [comment]
96167c35c54e2ba1487a1c76dab8b7e2041ab031

**Comment by ChrisKitching** [comment]
Why did you merge this without waiting for review?

**Comment by Crotalus** [comment]
In this case there's nothing to review, there's an illusion of alot of changes rows

AddBeatFunction -> ForkThread  + a local variable "slot" instead of "GUI.slots[index]"

**Comment by Sheeo** [comment]
Since our develop branch is relatively unstable at this point, I think it's OK to merge anything not on the `3642` release branch. Let's do the switch today.

**Pull request closed without merging**
