### PR TITLE
Separate strategic icon for SACUs

### PR DESCRIPTION
**Pull request by Strogoo**
Just a copy of ACU icon with different name. Don't want to spend any time on making icon that is good enough for main FAF patch, so let's leave this work for modders.

### CODE REVIEW

**Comment by shalkya** [comment]
fixes #2238

**Comment by shalkya** [comment]
image
i'm trouble seeing what it fixes.

**Comment by Strogoo** [comment]
It doesn't fix anything, only adds additional sacu icon so it can be changed by mods like Advanced Strategic Icons later. Currently ACU and sacu use same icon (icon_commander_generic), so spotting enemy acu at lategame stage is a pain ;)

**Comment by pwilkutowski** [comment]
> Just a copy of ACU icon with different name. Don't want to spend any time on making icon that is good enough for main FAF patch, so let's leave this work for modders.

for the love of good THANK YOU FOR THIS FIX 
Finally bad eye sight ppl will be able to snipe acu in map with lot's of sacu

**Pull request merged**
