### PR TITLE
Novax hotfix

### PR DESCRIPTION
**Pull request by Strogoo**
Moving code from terranweapons.lua to xea0002_script.lua

### CODE REVIEW

**Comment by speed2CZ** [comment]
What exactly does it fix?

**Comment by Strogoo** [comment]
novax

**Comment by speed2CZ** [comment]
That's why making an issue first is a good thing :)

**Comment by PhilipJFryFAF** [comment]
tested locally -> works
not sure how to test if it breaks mods since i don't know any mods that touch the script for the novax sat

**Comment by PhilipJFryFAF** [comment]
fixed by #2641

**Pull request closed without merging**
