### PR TITLE
Add IsAlly check to MobileUnit OnStartBuild

### LINKED ISSUE #2725: building opponent structures
if you are the same faction as your opponent you can build his structure if you ordered to build the same building at the same place in the fog of war (without you scouting his building).
This mostly happen with mexes.

### PR DESCRIPTION
**Pull request by clyfordv**
fixes #2725
## Description of the proposed changes
Prevent mobile units (engineers) from building enemy buildings. This typically happens when two engineers of the same faction are given a build order to the same resource spot.

## Testing done on the proposed changes
Spawn two engineers of a given faction, give them an order to build a mex/hydro on the same spot. Previously whichever engineer arrived second would assist with constructing the enemy structure; now they clear their command queue instead.

### CODE REVIEW

**Comment by Garanas** [comment]
This usually doesn't that often, but if it does - would it be natural to cancel the current command queue? It means your engineer would effectively be idling.

I think this is great as a first version to fixing the problem. But what if we'd extend the copy orders feature to allow you to skip the first N orders? That way you can copy the orders of the engineer but skip the current order and the queue remains functional. This extension would not be available through the sim callback

**Comment by MrRowey** [comment]
if your extending this like jip sudjest that fine when its ready for merge please add the snipit

**Review by MrRowey — APPROVED** [review]

**Comment by clyfordv** [comment]
Extension is in the works

**Comment by Garanas** [comment]
@clyfordv is it fine if I merge this in? You can make the improved version in a different branch, if you haven't already 😃

**Comment by clyfordv** [comment]
We're good to go, I'll add the improvements later.

**Comment by MrRowey** [comment]
> We're good to go, I'll add the improvements later.

Add Changes Snipit and ill merge in

**Pull request merged**
