### PR TITLE
Chat fixes

### PR DESCRIPTION
**Pull request by CodingSquirrel**
Multi-line messages no longer time out faster the more lines it's on.
New messages no longer necromance the previous line.
Line wrapping is much less stupid.

### CODE REVIEW

**Comment by quark036** [comment]
Necromance?

**Comment by CodingSquirrel** [comment]
You ever notice when your chat feed is empty and someone says something in chat, all of a sudden the previous line that was said however long ago shows up again?

**Comment by quark036** [comment]
Ah

**Comment by ChrisKitching** [comment]
Isn't that a sort of nice feature in some ways? Instant context.

**Comment by CodingSquirrel** [comment]
Except when it's not related and it looks like something old just happened. I always get confused for a moment when I see something like "RAS Completed" pop up even though it finished a few minutes ago. Plus there's the chat window for that.

**Comment by ChrisKitching** [comment]
That's true. Makes sense, then. I'll review the code when I'm not drunk, but it sounds pretty sane.

**Comment by CodingSquirrel** [comment]
Thanks. I imagine you can't do any testing from there, but I'd appreciate if anyone could try breaking the word wrap.

**Comment by ChrisKitching** [comment]
Wouldn't a central word wrap function that takes a line length and some text and returns a list of lines be useful?
I suspect specialised WrapText functions are sprinkled everywhere.

**Comment by CodingSquirrel** [comment]
That's what the function in text.lua is for. It takes a line of text, a function to calculate line length, and for calculating pixel length, and returns a list of lines.

**Pull request merged**
