### PR TITLE
Many small fixes and several new features for Scoreboard

### PR DESCRIPTION
**Pull request by KionX**
Increased the width of the window.
Added grouping of the player's team.
Added the ability to disable information about allies.
Required for https://github.com/FAForever/faf-phantomx/pull/23

### CODE REVIEW

**Comment by shalkya** [comment]
i will check it
I also got report that this new feature scoreboard also works during replay. Would it be possible to disable it for replays ? So that when you get into the view of a player, you still display the economy of al the players.

**Comment by KionX** [comment]
I do not understand what are you talking about. Need more info.

**Comment by shalkya** [comment]
talking about that : 
image
I'm watching a replay, if i get into a player view, i can't get the economic info about all players

**Comment by KionX** [comment]
The idea was to see in the replay what the player saw in the game.
Why should into a player view see the resources of all players?

**Comment by shalkya** [comment]
well people will know when watching a replay that the player didn't have knowledge of their opponent eco.
Sometimes caster want to cast by being into the view of one player, but they still want to know what is the opposing team economy (while not having to switch to global view and switching back to player view).
Anyway this request came from several players, you can discard if you want, it's not a major feature.

**Comment by Uveso** [comment]
I started a normal skirmish game and switched to observer.
Then i got this error:
```
WARNING: Error running '/lua/ui/game/gamemain.lua:OnBeat': Invalid army -1. (Use a 1-based index)
         stack traceback:
         	[C]: in function `IsAlly'
         	...\programdata\faforever\repo\fa\lua\ui\game\score.lua(573): in function <...\programdata\faforever\repo\fa\lua\ui\game\score.lua:570>
         	[C]: in function `sort'
         	...\programdata\faforever\repo\fa\lua\ui\game\score.lua(570): in function `fn'
         	...ogramdata\faforever\repo\fa\lua\ui\game\gamemain.lua(987): in function <...ogramdata\faforever\repo\fa\lua\ui\game\gamemain.lua:985>

```

**Comment by Uveso** [comment]
@KionX 
Could you do me a favor ?
The button inside the observerline has no tooltip.
(I) (B) (S) What does I,B and S mean ?

Are you able to add a tooltip for this button?

**Pull request merged**
