### PR TITLE
Improve collision interactions of projectiles

### PR DESCRIPTION
**Pull request by Garanas**
Improves the performance of checking whether projectiles should collide or not.

### CODE REVIEW

**Comment by Garanas** [comment]
image
Previous implementation, give or take 11.5 ms / tick with a base line of 2 ms (only 147 mantis remaining)

image
Current implementation, give or take 9.5 ms / tick with a base line of 1.8 ms (only 150 mantis remaining)

This one is tricky to benchmark because it also depends on the number of allied-intersections that are happening.

**Comment by Garanas** [comment]
image
Previous implementation, roughly 14 - 15ms / tick with a base line of 1.9 ms (150 mantis and an ACU)

image
Current implementation, 10 - 11 ms / tick with a base line of 2.1

This is a better test, where all mantis are on top of one another. This means that each projectile intersects with all mantis. By all means, the test is not representative for an actual game. But regardless, a 20% to 40% performance boost is decent. This pull request is based on this wiki page from a few years back:
 - https://github.com/FAForever/fa/wiki/LUA-Blueprint-and-Category-lookup-speeds

**Comment by Marc-Spector** [comment]
That's great! Good job!

**Comment by Garanas** [comment]
Not compatible with #3684 , yet.

**Comment by Garanas** [comment]
Supersedes #3684 .

**Pull request merged**
