### PR TITLE
Fix UEF SACU fire rate upgrade using inaccurate fire rate value

### PR DESCRIPTION
**Pull request by lL1l1**
## Description of the proposed changes

Changes the UEF SACU's fire rate upgrade from 1.82 fire rate to 2.00 fire rate because `1/1.82 = 0.5494` so it rounds down to 0.5 fire delay, which is equal to 2 fire rate. Also updates the localizations.

## Testing done on the proposed changes

Spawn a UEF combatant preset and step 5 ticks while paused to confirm that it does shoot 2 times per second with the 1.82x fire rate.

## Checklist

- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by Garanas** [comment]
We recently introduced a test suite for invalid fire rates, see also;

https://github.com/FAForever/fa/blob/f7420f632083217061e651e0b7097f345e6d2e29/tests/blueprint/unit.spec.lua#L278-L315

Would you be interested to enhance the test suite to catch these cases too?

**Comment by lL1l1** [comment]
This isn't a balance change, its effect is only for the UI.

**Comment by lL1l1** [comment]
There's only 4 units with fire rate enhancements, does it need a test?

**Comment by Garanas** [comment]
oh, I miss understood then. I thought this was a more broader problem!

**Comment by MrRowey** [comment]
> This isn't a balance change, its effect is only for the UI.

you have changed a Unit Fire Rate tho so that is a balance Change

**Comment by Garanas** [comment]
> > This isn't a balance change, its effect is only for the UI.
> 
> you have changed a Unit Fire Rate tho so that is a balance Change

If I'm not mistaken, practically it is the same value due to rounding 😃 ! It's now just more obvious what the value is.

**Comment by Garanas** [comment]
It appears the tests do not run on this branch 🤔 , any idea as to why that is?

**Comment by lL1l1** [comment]
Not sure why it doesn't show up in the "checks" tab of the PR, but the tests do run on my fork's page https://github.com/lL1l1/fa/actions/workflows/test.yaml

**Comment by MrRowey** [comment]
That's gin then feel free to merge then when you happy jip

**Comment by MrRowey** [comment]
@lL1l1 is this ready for review

**Comment by lL1l1** [comment]
yes

**Review by MrRowey — APPROVED** [review]

**Pull request merged**
