### PR TITLE
Add underwater vision to engis

### PR DESCRIPTION
**Pull request by Spikey84**
Adds water vision to each engi the size of their build range. This will make underwater mexes visible when attempting to build them.

### CODE REVIEW

**Comment by Spikey84** [comment]
It seems the intel values need to be double the build range values, so i doubled all values.

**Comment by Garanas** [comment]
Seems fine, but units that do not have the water vision set in the blueprint get a water vision of 10 by default. Shouldn't they already be able to see the extractors?

**Comment by Spikey84** [comment]
Oh thats strange, is this new to faf dev or always been a thing?

**Comment by Garanas** [comment]
Always been a thing.

**Comment by Garanas** [comment]
Closing this pull request as all engineers have water vision by default.

**Pull request closed without merging**
