### PR TITLE
Show player divisions in scoreboard

### LINKED ISSUE #4258: Add division to score board for matchmaker games
The latest client sends the division name of the player to the game if applicable. PR: https://github.com/FAForever/downlords-faf-client/pull/2793

Now the game needs to pick that name up to display it in the score board of the game instead of the rating. We could also or instead display a 20x40px image that petric made that visually represents the division.

The division info should also be saved in the replay. 
Can we even add more data to the replay?

### PR DESCRIPTION
**Pull request by BlackYps**
## Description of the proposed changes
Show the division of players in the scoreboard instead of rating if available (i.e. in matchmaker games)
Closes #4258 

## Testing done on the proposed changes
Tested them on a matchmaker replay, as well as a normal game to make sure that the rating still shows up when no divisions are available.

The missing space between division and subdivision is because the added space in the game options is not present in current replays. This is just an artefact of the testing process and will be fixed once the release happened.

grafik

## Checklist

- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by BlackYps** [comment]
According to this https://github.com/FAForever/fa/pull/4263 using the images causes problems with the layout. I have no experience with the ui elements of the game, so I don't feel competent to possibly address these problems.
And I would rather have a text implementation than none at all. Seeing that the linked PR is over a year old I don't think someone will show up and implement the images anytime soon.

But even if they do, it doesn't hurt to have the text solution in the meantime.

**Comment by MrRowey** [comment]
What will this show in custom games tho ?

**Comment by BlackYps** [comment]
Custom games still show the rating. UI mods are unaffected

**Comment by MrRowey** [comment]
I think it would be better to have it blank rather than it saying `unlisted`

**Comment by MrRowey** [comment]
@BlackYps How can i test this

**Comment by BlackYps** [comment]
It's a bit tricky to test. You can test the changes in score.lua by simply running replays of custom and matchmaker games. But then you have the old behaviour of autolobby.lua. I haven't found a way to test the autlobby.lua changes. For this you would have to launch an automatch with this branch, I'm not sure if this is possible. Maybe @Jip knows a way

**Comment by BlackYps** [comment]
I don't understand the "testing needed" label here. There is no further testing that can be done. We should merge it in and then see if it behaves correctly in matchmaker games. Which I believe it does.

**Comment by MrRowey** [comment]
the issue is that this is not going to be a visible change till it deplys in to main faf, then if something is broken it's going to require a hotfix as it can't be tested with out using it to the main.

**Comment by BlackYps** [comment]
Yes, I think this is an acceptable risk

**Review by MrRowey — APPROVED** [review]

**Pull request merged**
