### PR TITLE
Economy Numbers Improvement

### PR DESCRIPTION
**Pull request by aeoncleanse**
A few improvements. Rounds numbers to nearest integer to cut down on
display flickering. Performs fewer math functions. Rearranged the file a
bit for readability.

The big improvement: Attempts to prevent reclaim income from appearing
in the generated income column.

### CODE REVIEW

**Comment by CodingSquirrel** [comment]
I did a few minutes of poking around but couldn't find where the income numbers that the score uses are populated. Do you know if this will affect that? Hopefully we can stop that from showing reclaim numbers too.

**Comment by aeoncleanse** [comment]
I poked around too, same result. The Score display was the next thing I was gonna make sure of. As it is, I've no idea if it affects it or not. What I will say it that it cannot affect it negatively.

**Comment by Varaxis** [comment]
Income doesn't affect score display. It's only spending, acu death/kills, nuclear events, that seem to affect it.

**Comment by aeoncleanse** [comment]
Sorry for the misunderstanding Varaxis, should have been clearer: We're talking about the mass counter for each player which shows up in the score area when in neutral. Casters keep an eye on it to see how the players are doing, and reclaim really messes around with it.

**Comment by Varaxis** [comment]
Ah. No, it's my misunderstanding. Noticed that it was tackled in the eco window, sort of. I see what you mean. Now you got me interested. Noticed someone did a mod that has played around with that window, called ally overflow.

**Comment by Crotalus** [comment]
e01ebc73ef941d59bc8393032af28be8be747dc7

**Pull request closed without merging**
