### PR TITLE
Changed hitboxes for SCUs

### LINKED ISSUE #552: sACU hitboxes
When you move sACU from side to side, GC and ML (and other beam weapon i assume) won't target them well.

content.faforever.com/faf/vault/replay_vault/replay.php?id=3105472
from 4:50 to 6 min

here are the logs : http://forums.faforever.com/forums/viewtopic.php?f=3&t=9446

### PR DESCRIPTION
**Pull request by Crotalus**
The hitbox changes for SCUs

Fixes #552

### CODE REVIEW

**Comment by aeoncleanse** [comment]
These numbers are pulled from my changes? Cool

**Comment by Crotalus** [comment]
Yes, git is awesome :)

```
git checkout -b scu-hitboxes release/3641
git cherry-pick -X renormalize -n 1a7a55c3ae2276a4f416cbc11e41af16ded8e556
git reset HEAD
git add units/UAL0301/UAL0301_unit.bp units/UEL0301/UEL0301_unit.bp units/URL0301/URL0301_unit.bp units/XSL0301/XSL0301_unit.bp
git commit
git push origin scu-hitboxes
```

**Comment by Crotalus** [comment]
891a2cf8236e653a4e085b823565303374f23610

**Comment by aeoncleanse** [comment]
Oops. Yes, any target-bone changes should go with it.

**Pull request closed without merging**
