### PR TITLE
Fix small details of the Beacon Class

### PR DESCRIPTION
**Pull request by Garanas**
We add proper targeting bones to the Beacon Class. On top of that we fix the RackBone reference. For your idea, the old reference did this:

https://github.com/FAForever/fa/assets/15778155/2198a644-863d-4263-a829-7e072db48cf5

### CODE REVIEW

**Comment by Garanas** [comment]
@MadMaxFAF would you be available to fix the mesh-to-bone references? It appears there's no mesh attached to `Turret_Front_Muzzle` and `Turret_Back_Muzzle`. Shouldn't that be the 'barrel' part of the weapon?

**Comment by MadMaxFAF** [comment]
i'll have a look and see what feels right

**Comment by Garanas** [comment]
https://github.com/FAForever/fa/assets/15778155/65d47d56-5c11-47da-bc34-bed32570984b

**Comment by Garanas** [comment]
https://github.com/FAForever/fa/assets/15778155/d9e33b33-0419-46be-a042-3646bb7d0165

**Pull request merged**
