### PR TITLE
Prevent Cybran drones leaving wrecks

### PR DESCRIPTION
**Pull request by aeoncleanse**
#949 

There's some support there, and aeolus has been positive too. Let's get this in. They still die, crash, explode, all the visual glitter, they just don't leave a wreck.

### CODE REVIEW

**Comment by Crotalus** [comment]
Hmmm, maybe we should add a check to general wreckage code never to spawn a wreck that has mass value of 0?

**Comment by Sheeo** [comment]
I'm sure that would make a lot of players happy :)

Though some maps are built with wrecks of 0 value. Might be worth looking into making this either not reclaimable or remove it.

**Comment by aeoncleanse** [comment]
Or just do what I've done... Use the existing overkill code to prevent a pointless and unique annoyance.

**Comment by ChrisKitching** [comment]
You could just make them leave nonzero-valued wrecks.

Subtract a bit from the engineer wreck, add it to the drone wrecks, job done.

**Comment by Crotalus** [comment]
`release/3652`

**Pull request closed without merging**
