### PR TITLE
Unit restrictions Hotfixes

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
Fixes a few items reported in issue #1981 

**1 -** Restricting air does restrict the Fatboy as noted, but it's inconsistent in other ways too. It restricts the Cybran T3 mobile AA which can attack air and land, but not the Seraphim version which can also attack air and land. It also allows the Shard while restricting all other AA only units.
- [x] include Seraphim T3 mobile AA in the restriction

**2 -** Restricting amphibious units doesn't affect Fatboy or Scathis and does restrict Harbinger Mark IV.
- [x] include Fatboy and Scathis in the restriction and exclude Harbinger

**5 -** Restricting mobile stealth affects Rhino, Fire Beetle, Loyalist, and Brick. The description also seems to apply only to stealth fields but it affects personal stealth.
**BLUEPRINTS for these units should not have COUNTERINTELLIGENCE category**
- [x] update description with personal stealth**

**6 -** Restricting air snipe units affects T2 torpedo bombers but not T3. and T2/T3 gunships but not T1.
- [x] include T3 bombers in the restriction, T1 gunships are excluded by design

### CODE REVIEW

**Comment by PhilipJFryFAF** [comment]
you might want to take a look at nomads too since they have some multi purpose units like mobile arty with AA

**Comment by HUSSAR-mtrela** [comment]
Yes, I will and nomands mod should just re-use these unit restriction instead of replacing them.

**Comment by CookieNoob** [comment]
nomads is just using the file from FA, the unitmanager and unitrestrictions files were removed in the last nomads upgrade.

**Comment by aeoncleanse** [comment]
81c36820094d9f4f99f2921a646f4a2dc5a72063

**Pull request closed without merging**
