### PR TITLE
Add decimal places for the BuildRate stat in the UI

### LINKED ISSUE #5814: Unit stats (UI): Add decimal places where it makes sense
**Example:** 
A Tech 3 Engineer has 32.5 build power, but the in-game ui only shows 32.

### PR DESCRIPTION
**Pull request by Basilisk3**
Closes #5814

### CODE REVIEW

**Comment by Garanas** [comment]
Is there a reason you multiply by 10, just to divide it by 10 again after flooring it?

**Comment by Basilisk3** [comment]
> Is there a reason you multiply by 10, just to divide it by 10 again after flooring it?

Without it, it would only show 32 instead of 32.5.

**Review by lL1l1 — CHANGES_REQUESTED** [review]

**Comment by Basilisk3** [comment]
Thanks! This is ready to merged now.

**Comment by Garanas** [comment]
@Basilisk3 what is your name in Discord? 😃 , I'd love to discuss with you to give you more rights to the repository so that you can merge small pull requests such as these yourself in the future

**Pull request merged**
