### PR TITLE
Allow game to be rehosted

### PR DESCRIPTION
**Pull request by micheljung**
Provide a "Rehost" button in the game menu that sends a GpgNet-Command "Rehost" and closes the game.
The server (or client) can then trigger a new game and start it with `/rehost`. This causes the lobby to automatically restore all settings (even if someone else rehosts) and moves players to their previous slots as they join. Also restores AIs.

If a slot is occupied by a new player, this player will be moved away if possible, otherwise to observers.

I tested it in a LAN game and it worked well. I could *not* test the behavior when a slot was already occupied.

### CODE REVIEW

**Comment by duk3luk3** [comment]
That sounds awesome. What happens if more than one player clicks "rehost"? Are they all connected to one lobby?

**Comment by micheljung** [comment]
Hmm I guess this could be difficult due to race conditions, but it would be nice.
So far the plan is that only one player rehosts and the others automatically get invited

**Comment by duk3luk3** [comment]
Maybe the button should only show up for host then?

**Comment by micheljung** [comment]
I also thought about this, but see no real reason why restricting it would be better.

**Comment by Sheeo** [comment]
Why is this needed?

**Comment by micheljung** [comment]
A lot of games get rehosted because of various reasons (someone's connection dropped, game crashed, someone is AFK, team mates die within 5min, a game setting was wrong, you name it).

But rehosting is tedious; not all previous players join the newly created game (addressed by "auto-invite"), the balancing, spot assignment and faction selection needs to be redone (solved by auto slot-assignment), people who join that were not in the previous game and therefore block slots (solved as well by auto slot-assignment), 

Every player who wasted a lot of time and nerves because of these reasons will welcome this feature :-)

**Comment by visionik** [comment]
Speaking as "a player who wasted a lot of time and nerves because of these reasons", I would really welcome this addition.

**Comment by zlo-faf** [comment]
Probably unpopular desigion would be to not implement something tike this...
As zep said once, many of FAFs issues were never fixed cause people would just restar client as soon as they encounter any issue, and client restart used to take little less time than now (i think)

**Comment by duk3luk3** [comment]
I am in favour of this feature.

**Comment by Sheeo** [comment]
All right :+1:

**Comment by micheljung** [comment]
I'll have to update it so that rehosting is only possible for custom games. Any idea how to do this best? I thought about passing a flag `rehostingPossible` from the lobby to the game, then I guess I can check whether it's autolobby -> no rehost allowed, otherwise rehost allowed?

**Comment by Sheeo** [comment]
We should just have autolobby set `ScenarioInfo.AutoMatch = True` or such, yeah.

**Comment by micheljung** [comment]
I used the existing `ScenarioInfo.Ranked`. If it is set, the button will not be displayed.

**Comment by micheljung** [comment]
Why closed?

**Comment by aeoncleanse** [comment]
3652 branch was deleted thanks to merge. An issue to continue tracking this feature? It now needs client/server support right?

**Comment by micheljung** [comment]
Well it needs to be merged first. It's in feature/rehost.

Issues for client/server exists afaik.

**Comment by aeoncleanse** [comment]
Right kk. If it wasn't merged, it needs retargeting at develop

**Comment by Sheeo** [comment]
Right; noteworthy in the future: only ever target feature branch pr's at develop.

release branches are feature-frozen, and so should never have feature merges targeted at them.

**Comment by micheljung** [comment]
Well, I was told to base on 3652 - which made sense since `develop` AFAIK was far behind and I had to touch files that changed.
If this branch would've been based on master, merging would now be a nightmare.

Could we please merge this branch?

**Comment by aeoncleanse** [comment]
Sure. Can you rebase onto present develop please

**Pull request closed without merging**
