### PR TITLE
Fix/improve resource sharing

### PR DESCRIPTION
**Pull request by speed2CZ**
It's no longer possible to send resources to yourself or send negative
values

Untested

### CODE REVIEW

**Comment by speed2CZ** [comment]
Maybe test what happens if you try sending to yourself 0 instead of negative values

**Comment by norraxx** [comment]
And -0 too

**Comment by Strogoo** [comment]
Works fine for me. Tried to send negative mass to myself and to other player, both were rejected.

Also sending `0` and `-0` doesn't affect anything

**Comment by rjy7wb** [comment]
add a team resource feature that shows the amount of mass/energy being overflowed by the team

**Comment by speed2CZ** [comment]
Make a new issue for other features/requests. This was a bug fix.

**Pull request merged**
