### PR TITLE
Exterminate skinning.lua

### PR DESCRIPTION
**Pull request by ChrisKitching**
The only remaining use for this utter insanity was to try and draw a nine-patch background around the hotstats screen.

This use didn't work anyway, and fixing it isn't straightforward because of how amusingly mangled the layouts are in hotstats. So, this PR doesn't produce any visible changes, it just deletes a small nightmare from the codebase.
Ultimately, we might want to use the NinePatch class to build the feature ZeP was trying to get here, but with four lines not 822.

### CODE REVIEW

**Comment by Sheeo** [comment]
How does this look now?

**Comment by ChrisKitching** [comment]
Unchanged.

**Comment by Sheeo** [comment]
:+1:

**Comment by ChrisKitching** [comment]
To clarify: I haven't replaced a stupidly-implemented thing with a more sensibly-implemented equivalent, I've thrown away a stupid broken thing. :P

**Pull request merged**
