### PR TITLE
Separate t2 tanks icons

### PR DESCRIPTION
**Pull request by 4z0t**
Add new icon path for t2 amphibian tanks (also hover), but textures are the same, so it opens possibilities for modded icons.

### CODE REVIEW

**Comment by Garanas** [comment]
I'd say to rebase this to the FAF Beta branch but then it may take several months for it to emerge. I do think this is a balance related issue - I'm going to let @Petricpwnz / @Tagada14 decide on this.

**Comment by 4z0t** [comment]
Found better solution, PR not needed 🙂

**Comment by Garanas** [comment]
Enlighten us - what other solution did you find?

**Comment by 4z0t** [comment]
> Enlighten us - what other solution did you find?

I don't think it's a good idea to do such a change in icon structure, because a lot of people using icon mods will have problems. 
I noticed that i can specify for unit what icon to use through **mod_icons.lua**

**Comment by Garanas** [comment]
Sounds good - means the implementation Balthazar and I made is robust.

**Pull request closed without merging**
