### PR TITLE
Prevent Chrono Dampener affecting allies by using a timer

### PR DESCRIPTION
**Pull request by aeoncleanse**
This needs serious review. Sheeo and I wrote this a long time back, but lost it. I found this in an old mod on my hdd, but looking at it, it seems to be an old version. The timer code in particular... Will that not always yield wait == 50 no matter the input?

### CODE REVIEW

**Comment by aeoncleanse** [comment]
Confirmed working by test, timer now functional.

**Comment by Crotalus** [comment]
Looking good :+1:

**Comment by Crotalus** [comment]
Maybe rebase this onto release/3652? Doesn't seem to be updated with the latest changes you have in:

https://github.com/aeoncleanse/fa/tree/feature_ChronoTimer

**Comment by aeoncleanse** [comment]
Retargeting

**Comment by Crotalus** [comment]
No need, it's merged :)

**Comment by Crotalus** [comment]
Merged it into `release/3652`
0e7635f531aa663ca5e0f3eb12e69c1016354c68 .. 5dd915b65faaf0631d61df9cd41bdc384717cf6f

Did some linting cleanup in aeonweapons.lua:
557655d9bdffa392ccd8e13866a7aa8cf1fa5c80

and moved filtering of units to GetUnitsAroundPoints()
3ca8b5f19b93c8e34db8591a178ef90b81dd0318

**Pull request closed without merging**
