### PR TITLE
added "CQUEMOV" cat

### PR DESCRIPTION
**Pull request by shalkya**
allow the ability to select experimental and offensive/defensive structure while being built.
need to be use in combination of the https://github.com/FAForever/FAPatch/pull/6

### CODE REVIEW

**Comment by Exotic-Retard** [comment]
is it possible to rename the cat to something more obvious?
i have no idea what CQUEMOV might be, but SELECTWHILEBUILDING is a lot more self explanatory

**Comment by HUSSAR-mtrela** [comment]
yes, please use `SELECTWHILEBUILDING` for this new category

**Comment by FAETHER** [comment]
No, I need the category to be the same length as factory.

**Comment by Exotic-Retard** [comment]
in that case would this work? its the same length:
BUILDSLCT
CQUEMOV

**Comment by HUSSAR-mtrela** [comment]
@FAETHER please explain why does it have to be the same length as `FACTORY `category?

**Comment by FAETHER** [comment]
It has to be the same length because it is easier to implement, leaves no chance of a bug to occur. Because the stack would be on identical memory adresses as the previous call. My goal is to ensure 100% bug free solution. Also - I don't understand why cquemov is not descriptive for you. C - construction. Que - que a command. Mov - anything related to movement.

**Comment by Exotic-Retard** [comment]
yeah its all a case of how people think i guess xD for example i had no idea what the C could stand for. its not super important as long as it works. i think the only way to get something that most can understand is simply to ask a lot of people what they think the best one is, for me its BLDSLCT since its to do with building and selecting, rather than queueing and moving, which are more specific uses of the category

**Comment by HUSSAR-mtrela** [comment]
@shalkya thanks for explaining and maybe we should drop "C" and append "E":
`QUEMOVE` instead of
`CQUEMOV`

**Comment by HUSSAR-mtrela** [comment]
btw, I think this PR should be merged to FAForever:development/balance  and not develop branch

**Comment by FAETHER** [comment]
Actually. Should be mergedon both ends and also new .exe file as well. So that nothing will get regressed. Similar to what has happened to wall selection fix.

**Comment by FAETHER** [comment]
It probably tested for lua or something, idk. This is only blueprint changes, so should not be a hassle. Keyser did this pr, so he probably tested this very well. Can we just ignore travis build? I don't see any errors.

**Comment by shalkya** [comment]
there was indeed 4 missing commas, though i'm not entirely sure, it was my fault. (might be completely wrong though)

**Comment by CookieNoob** [comment]
it would be a good idea to add a comment that explains this category somewhere. This can be in the blueprints (just do a file search and replace) or at some other location (where it is easy to find).

**Comment by shalkya** [comment]
something like -- CQUEMOV means "construction queue movement"

**Comment by Sheeo** [comment]
Where's the corresponding exe patch code?

I am strongly against using this category name and I'm not convinced the length of it makes the binary patch any more "bug free" than not -- if it relies on the length of the category name it is by definition bugged.

**Comment by HUSSAR-mtrela** [comment]
@shalkya did you forget to reference issue # 2288 in this PR?

**Comment by shalkya** [comment]
ah yeah, it fixes #2288

**Pull request merged**
