### PR TITLE
Move visioning change to unit Bp File

### PR DESCRIPTION
**Pull request by MrRowey**

### CODE REVIEW

**Comment by Hdt80bro** [comment]
It'd be better to put this in the actual unit blueprints I think

**Comment by Garanas** [comment]
Yes, but it is a lot of work to do that 😄 !

What would be ideal is to start using that blueprint read / write tool that @The-Balthazar wrote, so that we can start migrating a lot of this to just into the blueprints

**Comment by MrRowey** [comment]
@Garanas & @Hdt80bro are we merging this in or not ?

**Comment by Hdt80bro** [comment]
The code is already there - this PR just moves it around. We can do more blueprint work in the future.

**Comment by MrRowey** [comment]
ill close it for now

**Pull request closed without merging**
