### PR TITLE
uef lod1 fixed

### PR DESCRIPTION
**Pull request by MrRowey**
fixed toward #2834

## Checklist

- [ ] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

### CODE REVIEW

**Comment by MrRowey** [comment]
yes i checked the steam files

**Comment by Garanas** [comment]
Can you make a screenshot of what the LODs look like? Just for documentation purposes

**Comment by MrRowey** [comment]
sure will do this when at desktop

**Review by Garanas — CHANGES_REQUESTED** [review]
I'm not convinced that these are improvements 😃 !

image

image

**Pull request closed without merging**
