### PR TITLE
Aeon air factories rework

### PR DESCRIPTION
**Pull request by MadMaxFAF**

### CODE REVIEW

**Comment by Garanas** [comment]
I merged these the other day: https://github.com/FAForever/fa/pull/4486

**Comment by Garanas** [comment]
I think these should be the Cybran air factories

**Comment by MadMaxFAF** [comment]
yeah you merged it before i had done the lod 1 scm

**Comment by MadMaxFAF** [comment]
Noted

**Review by Garanas — APPROVED** [review]

**Pull request merged**
