### PR TITLE
Ilshy Turn Rate Buff

### PR DESCRIPTION
**Pull request by MrRowey**
Improve the microabilty of the ilshy

```
TurnRate: 45 > 90
```

### CODE REVIEW

**Comment by Garanas** [comment]
Wouldn't this make it a very strong unit? It has more range, health and damage output than the average counter part - the only downside is that it's more difficult to micro.

If the idea is to make it better, what if instead of 90 we go with 60?

**Comment by MrRowey** [comment]
https://github.com/FAForever/fa/assets/20344151/07416307-1074-44da-9eb9-2029be920b3a

As Farms Shows here how one when trying to micro/ turn the ilsy it looks complete odd and 2 is really slow

**Comment by lL1l1** [comment]
Ilshie is weak vs ACU (teamgames), and strong vs other units (1v1). Other units can catch up with ilshies pretty easily due to the speed difference and fight for a long time so the turn rate doesn't have a huge impact. In stark contrast, ACUs are slow and their overcharge is a one shot kill so the turn rate can help a lot with avoiding them.
The actual difficult part of ilshies when fighting other units is that they're slow and expensive, so they're more prone to getting swarmed and bad at catching raids.

There's also the nuance that `TurnRadius = 2` for ilshie gives it 74.5 turn rate when the nav waypoint is further than 2 away (just set TurnRadius to 0 to see how slow 45 TurnRate actually is), so your gut instinct to go with a small +15 buff would result in 75 -> 90 turn rate and not 45 -> 60.

**Review by lL1l1 — APPROVED** [review]
From an aesthetic POV, nothing seems wrong with buffing the turn rate.

**Pull request merged**
