### PR TITLE
moholog settings switched off by default

### PR DESCRIPTION
**Pull request by KionX**
#3506

### CODE REVIEW

**Comment by Garanas** [comment]
I was not aware that this was part of the preferences too. What if we just set it to false during each time the game starts? There is no reason for typical people to have all that going on in the background.

**Comment by KionX** [comment]
I propose a compromise.
We will disable LOG for everyone in the next update.
Then we will disable only for new profiles.

**Comment by Garanas** [comment]
And how would that value be set? Through a command line argument?

**Comment by KionX** [comment]
The readme FAF says:
To start several processes of the game you need to add a line
debug = { enable_debug_facilities = true }
to %userprofile%\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance\Game.prefs

**Pull request merged**
