### PR TITLE
Rotate towards enemy logic redo

### PR DESCRIPTION
**Pull request by Garanas**
The original function first gathers all the units in radius, sorts them and then chooses the unit with the most threat. That is O(n) space and O(n * lg(n)) computation time, where _n_ is the number of units found. Since we're only interested in the unit with the most threat we can store it in O(1) space and run it in O(n) complexity.

It doesn't happen often that this function runs on a large amount of units - but when building artillery pieces it can happily sort all hostile units on the map and that may cause a stutter.

### CODE REVIEW

**Review by speed2CZ — APPROVED** [review]
Looking good

**Comment by Garanas** [comment]
Refactored the code to prevent table allocations (and de-allocations) for each threat update.

**Comment by Garanas** [comment]
As far as I can see the code is stable and functional. See also:
image

I am merging it on Monday morning.

**Comment by Garanas** [comment]
Tested one last time and all is good.

**Pull request merged**
