### PR TITLE
update english setup to explain how to install the vscode extension

### PR DESCRIPTION
**Pull request by hahn-kev**
I've updated the dev setup file to explain how to install the vscode extension. 

I also added info about the debugger from https://github.com/FAForever/fa/pull/3938 so that doesn't get lost and people know how to use it.

Also, added some tips that I felt should be explained for people who might not be aware, please correct as needed. Also, how can someone open the perf view to see the current sim speed?

### CODE REVIEW

**Comment by Garanas** [comment]
Via console commands:

- `ren_ShowNetworkStats` for the sim rate / package drops, on the top right
- `ShowStats` for engine stats, on the left

**Comment by Garanas** [comment]
Pull request looks good! @4z0t would you have time to update the russian translation once this pull request is nearly finalized?

**Comment by hahn-kev** [comment]
@Garanas I'm done with this now.

**Comment by Garanas** [comment]
@4z0t Can you add the changes to the Russian version?

**Comment by Garanas** [comment]
I'll be merging this in so that it exists. We'll update the translations another time

**Pull request merged**
