### PR TITLE
Add new translations

### PR DESCRIPTION
**Pull request by Yuchenjimmy**

### CODE REVIEW

**Comment by Garanas** [comment]
I've re-translated a few back to english using Google Translate - looks good! If more is coming, could you make those in a separate pull request? Then we can merge this one in

**Review by Garanas — APPROVED** [review]

**Comment by Yuchenjimmy** [comment]
I’m still working on it, but kind of busy these three days, next update may not be too soon. I also translate for the download client, both simplified Chinese and traditional Chinese had been updated, please apply them at next announcement, thank you!

**Comment by Yuchenjimmy** [comment]
An new update, a new pull request? Understood.

**Comment by Garanas** [comment]
Yes - a separate pull request for each would be perfect

**Pull request merged**
