### PR TITLE
Added personal stealth unit desc to T2 torp launcehrs - uef and cybran

### PR DESCRIPTION
**Pull request by Exotic-Retard**
t2 torp launchers have personal stealth - updated unit description to match this

hope i dont break anything :|

### CODE REVIEW

**Comment by aeoncleanse** [comment]
I'd rather remove the stealth! 
1 - How long have they had it?
2 - Why do they have it and the others don't?
3 - Why do they have it for free (No E drain)?
4 - Why can't it be toggled?

Basically... WTF!!!!

**Comment by Sheeo** [comment]
They've had it since the first commit in this repo. Don't know if it was present in the base game, but it's likely.

**Comment by Sheeo** [comment]
Either way, bugfixing is the motivation for 3641, so this PR is good.

**Comment by shalkya** [comment]
we don't know since when they had it, but i don't remember of someone that changed it.
All T2 torpedo launcher does have it (exotic retard and I wanted to make the change, so we split up the work)
yes no E drain, and no toggle. I think we should remove that, they are already under build.

**Comment by Crotalus** [comment]
6c7fafcba09f7e81521bfe33ebdadbffb1fdc56e

**Pull request closed without merging**
