### PR TITLE
Clarify licenses

### PR DESCRIPTION
**Pull request by Hdt80bro**
I've now added licenses to all of the files I've added, and clarified the license in our `luft` unit tester.

### CODE REVIEW

**Comment by Garanas** [comment]
Looks good, I'll add some of my files too.

**Comment by Garanas** [comment]
@Hdt80bro please confirm it is okay to license the profiler with MIT

**Comment by Hdt80bro** [comment]
Confirming that it is okay to license the profiler with the MIT license.

**Comment by Garanas** [comment]
🤔 , I feel like I missed out on a conversation 😄

**Comment by Hdt80bro** [comment]
@Garanas does this meet your understanding of licensing?

**Comment by Garanas** [comment]
Yes, but I think it is best to just write out the license like we did in `navgenerator.lua` - @Sheikah45 what are your thoughts on that?

**Pull request merged**
