### PR TITLE
Improve performance of build animation of UEF Naval factory

### PR DESCRIPTION
**Pull request by Garanas**

### CODE REVIEW

**Comment by ageekhere** [comment]
Would the following code optimizations work? (still new to lua)
`UEB0103 = ClassUnit(TSeaFactoryUnit) 
{
    StartArmsMoving = function(self)
        TSeaFactoryUnit.StartArmsMoving(self)
        local armSlider = self.ArmSlider
        if not armSlider then
            armSlider = CreateSlider(self, 'Right_Arm')
            self.ArmSlider = armSlider
            self.Trash:Add(armSlider)
        end
        self.armSlider = armSlider --cache data
    end,

    MovingArmsThread = function(self)
        local armSlider = self.armSlider
        while true do
            armSlider:SetGoal(0, 0, 40)
            armSlider:SetSpeed(40)
            WaitFor(armSlider)
            armSlider:SetGoal(0, 0, 0)
            WaitFor(armSlider)
        end
    end,

    StopArmsMoving = function(self)
        TSeaFactoryUnit.StopArmsMoving(self)
        local armSlider = self.armSlider
        armSlider:SetGoal(0, 0, 0)
        armSlider:SetSpeed(40)
    end,
}`

1 Removed TSeaFactoryUnit.MovingArmsThread(self) as it is already called in StartArmsMoving
2 Removed  if not armSlider then return end since the armSlider variable is initialized in the StartArmsMoving function and should always exist if StopArmsMoving is called.
3 Cache data In the StartArmsMoving function, the self.ArmSlider variable is accessed multiple times.

**Comment by Garanas** [comment]
Yes 👍 , there's more though. This pull request is part of an article:

- https://github.com/FAForever/fa/wiki/Performance-and-hash-operations

Have you read it? I'd love your thoughts on it

**Comment by ageekhere** [comment]
@Garanas Very interesting I wonder how much more this can be optimized. It is a very good workflow (though I must admit a bit over my skill level, though something cool to learn).

**Comment by Garanas** [comment]
Closing this until I have time to finish the article

**Pull request closed without merging**
