### PR TITLE
rebalance_T1_Maa

### PR DESCRIPTION
**Pull request by PhilipJFryFAF**
reduce aeon/uef T1 maa dmg to avoid killing one t1 bomber with a single t1 maa
increase sera T1 maa muzzle velocity to avoid missing shots on targets that move away from it

### CODE REVIEW

**Comment by PhilipJFryFAF** [comment]
disclaimer: needs some more work so pls don't merge yet

**Comment by PhilipJFryFAF** [comment]
changed the dmg nerf on aeon/uef to be less significant and buffed the sera since it doesn't shoot 2 projectiles

**Comment by CookieNoob** [comment]
ProjectilesPerOnFire is an unused property and changes nothing.

http://supcom.wikia.com/wiki/Blueprint (scroll down to ProjectilesPerOnFire)

**Comment by PhilipJFryFAF** [comment]
reverted the pointless change
ty for the information @CookieNoob

**Pull request merged**
