### PR TITLE
Set Salvo Size to 3 across the board

### PR DESCRIPTION
**Pull request by MrRowey**
#5045

### CODE REVIEW

**Comment by Garanas** [comment]
By increasing the salvo size you also increase the total damage output. You'll need to tweak the damage values too, unless that is intended

**Comment by MrRowey** [comment]
> By increasing the salvo size you also increase the total damage output. You'll need to tweak the damage values too, unless that is intended

oh, interesting I just thought that it would split the damage across the 3 so damage is the value of each torp then?

**Comment by Garanas** [comment]
Yes, it should be. You can test it in-game

**Comment by Garanas** [comment]
@The-Balthazar can renaming the label of the weapon cause issues for mods?

**Comment by The-Balthazar** [comment]
It would break any mod that's trying to hook the units weapon script directly, or that's trying to refer to the weapons by label. Modifying them with a bp merge would be unaffected since that would use table index. While I think it's unlikely that a mod would do those things, it's not outside of the realms of possiblity, and I see no actual benefit in changing the labels.

**Comment by Hdt80bro** [comment]
@The-Balthazar have you noticed a difference with changing `EffectiveRadius`? The engine uses the value somehow, but I'm not sure where. Just noticed that this PR changes that.

**Pull request merged**
